### ISSUE TITLE
Sometime does not resume Wi-Fi after sleep

### ISSUE THREAD

**Issue by Khariton** [tomaspinho/rtl8821ce#10]
This issue occur not often. 
I have tried reload networking/module/wpa_supplicant - does not help. Only reboot helps.
Might you can advice me what I need to check and investigate issue?

**Comment by tomaspinho** [comment]
I sometimes have issues with this, but using the Wi-Fi applet to turn off the card and turning it on again usually solves the problem. This is related to the absence of decent power management in this driver. Unfortunately there's nothing I can do about this since the code is Realtek's. I'm closing this issue.

**Comment by Khariton** [comment]
Dear Tomás Pinho,

The email sent to sasha@mishchenko.tk with subject
"Re: [tomaspinho/rtl8821ce] Sometime does not resume Wi-Fi after sleep"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to sasha@mishchenko.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by elmys** [comment]
I can add, that this issue on my laptom every time after sleep... and Turning off-on don't get solution

**Comment by Khariton** [comment]
Dear elmys,

The email sent to sasha@mishchenko.tk with subject
"Re: [tomaspinho/rtl8821ce] Sometime does not resume Wi-Fi after sleep"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to sasha@mishchenko.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by tomaspinho** [comment]
@elmys have you tried following the steps here? https://github.com/tomaspinho/rtl8821ce#possible-issues

**Comment by elmys** [comment]
Off course! Just after reading of all issues. Need only reboot my system... Tnx

**Comment by Khariton** [comment]
I have add to lid acpi event script when lid opened:
modprobe -r 8821ce
sleep 1
modprobe 8821ce

Also add this to .bash_profile, because when I have logout from one user and login to another, I have brocken WiFi.
