### ISSUE TITLE
Linux Mint 19.2, WiFi doesn't work on kernel 5.3

### ISSUE THREAD

**Issue by pyroxar** [tomaspinho/rtl8821ce#100]
WiFi doen't work on kernel 5.3.0-19-generic.
https://pastebin.com/y2Pg9aGS
WiFi work fine on kernel 5.0.0-32-generic
https://pastebin.com/WCBTTv9a

It's the same driver (the last version), I use DKMS to install this. Module for kernel 5.3 dosen't work and do work 5.0.

**Comment by tomaspinho** [comment]
Do you have the latest version of the module? Do a full removal as per instructions in the README, make sure you have the latest version of the repository and reinstall.

**Comment by pyroxar** [comment]
OK, I have the lastest version of the module. WiFi and Bluetooth works for me but I can't build dkms module. I must compile it manually.
![dkms](https://user-images.githubusercontent.com/23406555/68608156-8a590100-04b2-11ea-8129-e0890c7fe9a4.png)

**Comment by tomaspinho** [comment]
Are you sure you're running the latest commit? Can't reproduce this.
Please run `git rev-parse HEAD` and paste the output

**Comment by pyroxar** [comment]
I download now by git clone (not zip file) and now it work fine.

When i download form zip file I have this:
![obraz](https://user-images.githubusercontent.com/23406555/68753940-17f93580-0606-11ea-916d-407318392e84.png)

**Comment by pyroxar** [comment]
Never mind. It works.

**Comment by zekena** [comment]
The same Issue with kernel 5.4.0-39 ,40 and 42 all of them the wifi doesn't work on them but it works with 5.3.0-53-generic I removed driver and installed it again with the shell scripts but still doesn't work

**Comment by tomaspinho** [comment]
@zekena are you sure you have the latest version of the repository for a fresh installation of the driver? Can you post the commit hash of your current git checkout as per commands above, your dmesg and the output of `lsmod` while you're running the offending kernels?

**Comment by zekena** [comment]
@tomaspinho never mind I rebooted right now and it worked don't know why and how but it works :sweat_smile:

**Comment by tomaspinho** [comment]
> @tomaspinho never mind I rebooted right now and it worked don't know why and how but it works :sweat_smile: Thanks for your attention :heart: 

Glad it worked out! 😄
