### ISSUE TITLE
ERROR adding monitor mode interface...

### ISSUE THREAD

**Issue by serpunja** [tomaspinho/rtl8821ce#101]
Thank you very much for driver! 
Now on my ASUS505D there is wifi. 
Help. 
How to transfer a card to monitor mode?

`toor@KALI:~$ sudo airmon-ng start wlan0`
`   PHY	Interface	Driver		Chipset
  phy0	wlan0		rtl8821ce	Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
 ERROR adding monitor mode interface: command failed: Operation not supported (-95)`
`toor@KALI:~$`
(((.

**Comment by serpunja** [comment]
p.s.
O.S. - Kali Linux

**Comment by tomaspinho** [comment]
There is no monitor mode support in this module.

**Comment by alchemist18** [comment]
Thank you for your work. Now I too have wifi on my HP 255 G7 Notebook!
Is there any hope to have monitor mode support developed?

**Comment by dallenwilson** [comment]
You'd have to follow up with RealTek for that. No one here does development, just basic packaging and some minor maintenance.
