### ISSUE TITLE
Ubuntu 19.10 no 5GHz Wifi

### ISSUE THREAD

**Issue by tschorle** [tomaspinho/rtl8821ce#103]
I'm using a clean install of ubuntu-budgie 19.10. i enrolled the driver in the shim menu. i see only 2,4GHz networks in the network menu. im using a hp dk0101ng notebook. i'm fairly new to linux. i don't know which information i need to supply

**Comment by Fivizzz** [comment]
This driver is no longer functional on Kernel version 5.3, but there is a functional driver in the Ubuntu repos from 19.10 onwards, but it has to be installed manually.

If necessary, run `sudo ./dkms-remove.sh` in the relevant folder to remove this driver then simply install the official driver:
`sudo apt-get install rtl8821ce-dkms`

Works like a charm ;)

**Comment by dallenwilson** [comment]
It's worth noting that the rtl8821ce-dkms package provided by the ubuntu repos is based on a beta release of an older version of the driver: v5.2.5.2.1_xxxx.20181112_beta_COEX20170310-1212. The one in this repo is v5.5.2_34066.20190614_COEX20180712-3232. There is an even newer version floating around, but it doesn't add or fix much.

If the newer version here isn't functional with kernel 5.3, it's likely something wonky with ubuntu. I had it working just fine on a Gentoo system with kernel 5.3.18, before updating to 5.4.8.

**Comment by justcomplaining** [comment]
I have this issue with the official ubuntu package, so this will probably not help.

**Comment by vicamo** [comment]
Would like to share that [v5.5.2.1 is being updated to Focal, Eoan and Bionic](https://bugs.launchpad.net/ubuntu/+source/rtl8821ce/+bug/1861669).
