### ISSUE TITLE
Debian 10 Compile Issue

### ISSUE THREAD

**Issue by chickazama** [tomaspinho/rtl8821ce#106]
Hi, when I run sudo ./dkms-install.sh, I receive an error. It generates a DKMS make.log file, but I'm afraid I'm getting a bit out of my depth here as to what to do next. I have a feeling that a similar issue (if not the same one) was resolved previously. If that is the case, a link to that would be much appreciated!

I've attached the make.log file. If someone could take a look and help me out, that would be fantastic! Thanks
[make.log](https://github.com/tomaspinho/rtl8821ce/files/3941176/make.log)

**Comment by dallenwilson** [comment]
The log shows that bc cannot be found, among other errors. Can you verify you've got all the prerequisites installed?

Something along the lines of
``sudo apt install bc module-assistant build-essential dkms``
``sudo m-a prepare``
should do the job, as detailed in the readme.

**Comment by chickazama** [comment]
Haha thanks, I think I must just have been so tired, I literally missed that I hadn't got bc installed. Everything works now! Thanks for your help
