### ISSUE TITLE
Are there plans to mainline this? 

### ISSUE THREAD

**Issue by Newbytee** [tomaspinho/rtl8821ce#107]
Hi! This isn't much of an issue but rather a question: what's the prospect of this getting into mainline Linux? Can't seem to find anything in this repo regarding that.

**Comment by tomaspinho** [comment]
There are no plans of getting this mainlained, the Kernel maintainers are waiting for a general module by Realtek, rtw88 which should support this chipset. See the maintainership issue for more details.
