### ISSUE TITLE
Random crashes on Fedora 31

### ISSUE THREAD

**Issue by Electron-007** [tomaspinho/rtl8821ce#111]
I am getting random kernel crashes reported, although nothing seems wrong with the functionality of the wifi. I had to turn off secure boot in the BIOS, and now the kernel is tainted because an insecure module has been loaded ...

![Screenshot_20191214_101809](https://user-images.githubusercontent.com/58578180/70853560-d0133b80-1e5b-11ea-884d-0b1ff6d8d493.png)
![Screenshot_20191214_102803](https://user-images.githubusercontent.com/58578180/70853597-79f2c800-1e5c-11ea-8f4e-6a81a17f75ae.png)

**Comment by tomaspinho** [comment]
None of these screenshots are evidence of this module causing the kernel panic. It's expected for the kernel to be tainted as this module is not signed.

**Comment by Electron-007** [comment]
It definitely is this module causing the problem.

To wit: https://github.com/tomaspinho/rtl8821ce/blob/master/hal/hal_com.c
Line number 11447

Technically it is a WARNING, not a PANIC, thrown by a function call `rtw_warn_on(1)`. The referenced source file, which appears unchanged since it was imported from endlessm. Very annoying, even though nothing is actual "crashing" ...

```
#define LPS_ACTIVE_TIMEOUT      10 /*number of times*/
void rtw_lps_state_chk(_adapter *adapter, u8 ps_mode)
{
        if (ps_mode == PS_MODE_ACTIVE) {
                u8 ps_ready = _FALSE;
                s8 leave_wait_count = LPS_ACTIVE_TIMEOUT;

                do {
                        if ((rtw_read8(adapter, REG_TCR) & BIT_PWRBIT_OW_EN) == 0) {
                                ps_ready = _TRUE;
                                break;
                        }
                        rtw_msleep_os(1);
                } while (leave_wait_count--);

                if (ps_ready == _FALSE) {
                        RTW_ERR(FUNC_ADPT_FMT" PS_MODE_ACTIVE check failed\n", FUNC_ADPT_ARG(adapter));
                        rtw_warn_on(1);
                }
        }
}
```

**Comment by tomaspinho** [comment]
Can you remove that line, rebuild and reinstall the driver to see if the issue persists? We could then merge the change. :blush:

**Comment by Electron-007** [comment]
I am curious about the previous line. There is a strange C macro that is supposed to expand.

`RTW_ERR(FUNC_ADPT_FMT" PS_MODE_ACTIVE check failed\n", FUNC_ADPT_ARG(adapter));`

It is supposed to generate an actual message for the warning that I am not getting.

Or perhaps it would be better to increase `LPS_ACTIVE_TIMEOUT` or the `rtw_msleep_os()` time.

I've got to go. I will have to look at it more tomorrow or next week.

**Comment by Electron-007** [comment]
To be more clear: now that I've thought about it some more I believe it's just a low-level hardware timeout intended to be logged at a debug level rather than generate an obnoxious user-interface kernel crash or panic warning.

Somehow the warning is being escalated out of proportion on the Fedora system, because it's from an unsigned or "tainted" kernel module.

Low priority to-do if you care to keep the issue open.

I am somewhat caught between a rock and a hard place on this one since Microsoft bought out Github and IBM bought out Red Hat and Fedora. Both proprietary software companies are based in the U.S., as am I, and unfortunately they have the means, through law enforcement, military, and other channels, to seek and obtain revenge against me for meddling or dabbling in "open source" which they really want quashed in favor of their own proprietary SaaS and shelf product software offerings.

We really don't have the freedom to "work" on this kind of stuff in corporate-state fascist USA without official authorization from the big tech cartel.

I've got to go, as I said, and Big Tech needs to stop being so full of $#!+.
-------- Original Message --------

**Comment by tomaspinho** [comment]
I'm not sure what kind of weird work contract you have that disables you from working on unrelated open source  software, but I'm willing to help you out by setting up a branch with the change so you can test it for yourself. How does that sound?

**Comment by Electron-007** [comment]
>>> weird work contract you have that disables you from working on unrelated open source software

1. I am working at public libraries and other places surrounded by pickpockets and thieves who work in collaboration with local police. My private keys and passwords are not in reality private.

2. I have political enemies, and I am subject to numerous arbitrary criminal trespass orders at libraries, coffee shops, universities and other places where one might ordinarily work on these kinds of projects.

3. The cops are busting in the door at all hours of the day and night everywhere I might otherwise stay or maintain a residence. Vicious gangs of cop-calling whores are seething with a criminal bloodlust and desire to either kill me or put me in prison no matter what on any kind of charge or excuse, and Male cops who pander to the ladies of the street in a protector // bodyguard role are all too eager to do their bidding.

4. It's a plant-and-bust district. The ladies of the street are busy picking my pockets and stealing USB thumb drives and any other backups I might have of any files, and the cops are all too eager to plant something unrelated and file false charges for possession of some copyrighted content, DMCA violation, child pornography, or anything else that might be a felony offense they could trump up against me in their seething anger and desire to punish me for refusing to cooperate with the mainstream proprietary software cartel.

NO, I would not be allowed to keep possession of any real property or money, not even if I were allowed in theory to work for one of those companies.

HAVING SAID ALL THAT, the changes proposed are unnecessary and untestable at this time. The malicious wifi interference that was either causing or being allowed to cause the low-level hardware timeout problem has stopped without explanation, and the driver is working without any problems now.
