### ISSUE TITLE
Does not work on fedora 31

### ISSUE THREAD

**Issue by nikoshatzivag** [tomaspinho/rtl8821ce#114]
I have a lenovo laptop and tried to install this driver but it doesn't work. It still doesn't show up wifi

**Comment by image357** [comment]
I am using fedora 31 and it does work for me. Maybe I can help you. Can you give more details on the problem and what you have already tried?

**Comment by DECsystem20** [comment]
Hello! I ran into this problem too. I use Fedora 31; kernel 5.4.7-200.fc31.x86_64. I was able to fix it by running dkms-remove.sh first, and then dkms-install.sh.
