### ISSUE TITLE
Zorin OS 15.1

### ISSUE THREAD

**Issue by Electrocze** [tomaspinho/rtl8821ce#115]
Hi I cant install driver rtl8821ce ... Error in installing with dkms or make command
.
.
sudo ./dkms-install.sh
About to run dkms install steps...

Creating symlink /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/source ->
                 /usr/src/rtl8821ce-v5.5.2_34066.20190614

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.4.8-050408-generic.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.8-050408-generic (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.4.8-050408-generic....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.8-050408-generic (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.
Finished running dkms install steps.

**Comment by dallenwilson** [comment]
Can you please consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information, and share it with us?

**Comment by Electrocze** [comment]
Yeah Sure 
[make.log](https://github.com/tomaspinho/rtl8821ce/files/4046501/make.log)

**Comment by Electrocze** [comment]
So I look in older issues and find solution only I need to install 

> apt install gcc-8
And add 
CC = gcc-8  rtl8821ce/Makefile folder
(thanks Syniurge :) )
