### ISSUE TITLE
802.11ac mode with hostapd.

### ISSUE THREAD

**Issue by smekkley** [tomaspinho/rtl8821ce#116]
Did anybody manage to make 802.11ac accesspoint with this driver?
The hardware seems to support it, so it should be possible, but I'm getting an error as soon as I enable ac.

**Comment by tomaspinho** [comment]
This seems to be related to the lack of support of 5GHz in this driver. Could you make 802.11bgn access point with this driver?

**Comment by smekkley** [comment]
With `g`, it's running stably.

**Comment by bragma** [comment]
Hi, I'm trying to run hostapd with this driver. Can you please share your configuration? Thanks!

**Comment by smekkley** [comment]
@bragma 
From kernel 5.19, the official driver works fine with 802.11ac AP mode as well. But this is the 802.11g config.
```
bridge=br0
ssid=ssid
wpa_passphrase=pass
country_code=US
ctrl_interface_group=0
interface=wlp2s0
driver=nl80211
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
ctrl_interface=/var/run/hostapd
ctrl_interface_group=wheel
wmm_enabled=1
wpa=3
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
hw_mode=g
channel=3
```

**Comment by bragma** [comment]
Hi @smekkley, thanks for sharing. Can you also run AP+STA at the same time?
