### ISSUE TITLE
wifi doesn't come up on Yoga 530 14-ARR

### ISSUE THREAD

**Issue by 9Lukas5** [tomaspinho/rtl8821ce#12]
Hey, I have a Lenovo Yoga 530 here with a RTL8821ce. Ubuntu 18.10 installed, tried with the installation kernel which was 4.18.0 and the latest stable upstream kernel which is at time of writing this 4.19.1.

I can't seem to get the module bring me online, and I have no clue what to try now. attached is my dmesg and lspci output. Hope you can help me somehow.
If there's some specific sort of information / log I should provide, I'll try my best

[lspci-vnvn.log](https://github.com/tomaspinho/rtl8821ce/files/2567667/lspci-vnvn.log)
[dmesg.log](https://github.com/tomaspinho/rtl8821ce/files/2567669/dmesg.log)

Regards, Lukas

**Comment by tomaspinho** [comment]
Hello, Lukas

Your logs don't have anything out of the ordinary. However, I see no Wi-Fi association attempts. Have you tried to connect manually? Does the NetworkManager applet allow you to do so?

**Comment by 9Lukas5** [comment]
Hey Tomas,

without your driver I can't see in the networkmanager a wifi at all. Also `ip` doesn't show the interface.

If I install your driver, I get the wifi in the ui, but if I click to enable it, the switch goes to on, but nothing happens.
Closing the window and reopen it, the on/off switch is back to off.

looking to the `ip` command, I can see the interface, but it's marked as down. `ip link xy set up` also doesn't work.
In dmesg I can only see as last line 'wlp1s0 is not ready'.

Besides this: if I have your driver installed, my touchpad doesn't work anymore. Which only works using [this](https://github.com/Syniurge/i2c-amd-mp2) additional driver.
According to [this bug on launchpad](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1787775), your driver seems to work on the yoga 530-15, but not on the yoga 530-14

**Comment by tomaspinho** [comment]
From what I've read on the link you posted, there seems to be an incompatibility between your touchpad module and this one. Unfortunately, I don't think I can help you out with this 😕

**Comment by 9Lukas5** [comment]
hm, ok thank you for checking my information.
Do you see a chance that it'll work in the future?

**Comment by Syniurge** [comment]
It's actually a bug with the ideapad-laptop driver, wrongly reporting radio devices as hardware-blocked.

Just rmmod or blacklist the ideapad-laptop module and WiFi and Bluetooth will show up and work with this driver:

```bash
sudo modprobe -r ideapad-laptop
```

**Comment by tomaspinho** [comment]
@9Lukas5 can you confirm @Syniurge's fix works for you, so I can add that to the docs?

**Comment by 9Lukas5** [comment]
Yep, I can confirm @Syniurge's fix. Installing the driver, reboot and kick the ideapad_laptop (it was underscore^^) got the wifi up and working fine. Huge thanks.

**Comment by tomaspinho** [comment]
Ok, I'm closing this. @Syniurge thank you again, I'm adding the fix to the docs.

**Comment by 9Lukas5** [comment]
@tomaspinho just noticed, that removing the ideapad_laptop causes the hotkeys for backlight control to stop working.
The backlight changes fine through the ui, just the hotkeys don't work. Not a big issue, but should be noted.
