### ISSUE TITLE
Does not compile for kernel 5.6rc1 in Kubuntu 18.04

### ISSUE THREAD

**Issue by sashamishchenko** [tomaspinho/rtl8821ce#125]
CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/hal/hal_com.o
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/rtw_proc.c: In function 'rtw_proc_create_entry':
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/rtw_proc.c:70:71: error: passing argument 4 of 'proc_create_data' from incompatible pointer type [-Werror=incompatible-pointer-types]
  entry = proc_create_data(name,  S_IFREG | S_IRUGO | S_IWUGO, parent, fops, data);
                                                                       ^~~~
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/../os_dep/linux/rtw_proc.h:18,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_intf.h:128,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:106,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/rtw_proc.c:17:
./include/linux/proc_fs.h:59:31: note: expected 'const struct proc_ops *' but argument is of type 'const struct file_operations *'
 extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
                               ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:267: recipe for target '/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/rtw_proc.o' failed
make[2]: *** [/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/rtw_proc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1681: recipe for target '/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build' failed
make[1]: *** [/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.6.0-050600rc1-lowlatency'
Makefile:2245: recipe for target 'modules' failed
make: *** [modules] Error 2

Kernel 5.5* can be compiled. gcc preconfigured:
# head Makefile 
CC = gcc-8
...

**Comment by tomaspinho** [comment]
Mind testing the fix in https://github.com/tomaspinho/rtl8821ce/pull/126 ?

**Comment by rgsouthall** [comment]
#126 works for me on 5.6-rc1

**Comment by sashamishchenko** [comment]
Thanks!
It work better than with kernel 5.5.
I can see wi-fi level indication in widgets. On 5.5 I can saw level like 0 - w/o indication, but wi-fi worked as well.

Ticket can be closed.

**Comment by tomaspinho** [comment]
Great news regarding the wi-fi level indication. Merged my PR. Closing this one.
