### ISSUE TITLE
Not working on v5.5.2 Manjaro

### ISSUE THREAD

**Issue by 7aske** [tomaspinho/rtl8821ce#127]
Driver worked okay on Manjaro up until and including kernel version 5.4.18. I just updated to 5.5 and reinstalled kernel modules using 5.5.2 branch with no errors but the card is not active after reboot. Its is being listed as recognized in `lspci` but `ifconfig` shows only the loopback adapter. I'm using Lenovo S540-14API. Tell me if there is more info I can provide.

**Comment by Flygrounder** [comment]
I have recently updated my Manjaro installation from 5.5.0 to 5.5.2 and it stopped working. But in my case, card is not listed in `lspci`
