### ISSUE TITLE
Inconsistent connection issues

### ISSUE THREAD

**Issue by StaticRocket** [tomaspinho/rtl8821ce#128]
Asus GA502DU has inconsistent errors. Looking for help troubleshooting. WiFi works fine on some boots and is broken on others. Occurs using `iwd` and `NetworkManager`. Will not recover from restarting the systemd service in either case. Device is displayed as `DOWN` & `DORMANT` when unable to connect (via `ip link`). `iwctl` shows access points when in this broken state but the signal strength is extremely low. Attempting to connect results in an operation failed message and usually with all displayed access points vanishing soon after.

While this is a coin toss for the initial boot, occasionally the device seems to recover and reconnect. All signs point to PCIe Activate State Power Management, but the solutions outlined in the README and another issue do not seem to have any effect on this behavior.

OS - Arch Linux
Kernel - 5.5.4-arch1-1
I've checked journal and dmesg but haven't seen anything out of the ordinary.

**Comment by StaticRocket** [comment]
Resolved by enabling early kms for `r8169`

**Comment by tomaspinho** [comment]
Does
```
sudo modprobe -r 8821ce
sudo modprobe 8821ce
```
fix the issue on a broken boot?

**Comment by StaticRocket** [comment]
Nope. I should have mentioned that. It removes all networks from iwd. After restarting iwd and scanning no networks can be found.

**Comment by StaticRocket** [comment]
Sorry that my responses keep changing but this is a testament to the inconsistency of these issues. It's hard to troubleshoot what can only be replicated by chance.

**Comment by StaticRocket** [comment]
Well I managed to collect logs for a common working occurrence:
http://ix.io/2cxX

And a common broken occurrence:
http://ix.io/2cxU

**Comment by StaticRocket** [comment]
Status Update:
Kernel update and some tinkering on my end (not sure which actually addressed it) has resolved some of the inconsistencies. Now the driver will fail on soft reboot but will succeed on cold reboot. Could this be a firmware issue?

**Comment by StaticRocket** [comment]
Status Update:
Kernel update and some tinkering on my end (not sure which actually addressed it) has resolved some of the inconsistencies. Now the driver will fail on soft reboot but will succeed on cold reboot. Could this be a firmware issue?

**Comment by tomaspinho** [comment]
What do you mean by soft reboot? This module doesn't properly support suspend

**Comment by StaticRocket** [comment]
@tomaspinho soft reboot as in simply using the command `reboot`, which technically invokes `shutdown` but the point is the system immediately comes back online. (I may have the wrong term here so feel free to correct me).

**Comment by tomaspinho** [comment]
Issuing `reboot` should trigger a motherboard ACPI reboot, if that isn't forcing a reset of your chip, then there's something really weird going on with your BIOS... Sorry, I can't be of help here, don't have the same hardware and what you're describing seems to be very specific to your hardware setup.

**Comment by StaticRocket** [comment]
Yeah, ASUS has really been missing the mark with this things previous BIOS releases so I wouldn't be surprised, but I recently built the package manually (circumventing the `PKGBUILD` and instead just running `dkms-install.sh` directly) and it seems to be more stable at the moment (though I know this shouldn't have any effect). Given this things history I don't know if it will last. If I don't see any problems in the next few days I'll close the issue as its probably outside of the scope of this project. Thanks for your help thus far.

**Comment by StaticRocket** [comment]
Oh cool. Something broke during an uninstall/install. Upon running `dkms-remove.sh` and checking to be sure the AUR package was not installed. I still found that the network device was still being managed by iwd.

**Comment by tomaspinho** [comment]
To make sure you have fully removed the package, check `dkms status`. It shouldn't output any lines. If it does, run  `dkms remove` for all modules. If you have zombie modules being built when you upgrade the Kernel, make sure your `/var/lib/dkms/` directory is empty.

**Comment by StaticRocket** [comment]
Just cleaned it all out and reinstalled it. Now I'm back to the time based failure. Looking at the new logs it appears to be powering on and off quite a bit.

**Comment by AndreasTPC** [comment]
Just to add that the soft reboot vs. hard reboot thing isn't an isolated issue with that guy: Bluetooth sometimes breaks for me with this drivers, and when it does a soft reboot (shutdown -r now) never fixes it, but doing a shutdown -h now and powering it back on does fix it.

**Comment by StaticRocket** [comment]
Alright, I think I've narrowed it down to being an issue with the wireless authentication type, specifically EAP-PEAP. Each failed attempt to connect to the network results in the driver slowly loosing functionality until it dies. Apparently having a known network in range to fall back to upon a failed attempt will keep the driver in basic operation until a successful connection attempt can be made.

What happens on each attempt when in range of a known network:
(Each failure results in iwd switching back to the known network which in my case is unsecured)
| # | Result | Driver response |
|---|---|--- |
| 1 | Failure | Report weaker (approximately 1/2 of previously reported) signal strength on all available networks |
| 2 | Failure | Report lowest signal strength possible |
| 3 | Success | Report lowest signal strength possible |

**Comment by StaticRocket** [comment]
In some cases the driver is unable to connect to an open network resulting in the same log reported above but without the iwd 4-Way handshake message. A new kernel came out yesterday. I'm hoping that either this update or the 5.6 release will help with this issue.
