### ISSUE TITLE
getting issue no : #60 

### ISSUE THREAD

**Issue by chaitanyaGa** [tomaspinho/rtl8821ce#132]
still getting same issue on Ubuntu

ERROR (dkms apport): binary package for rtl8821ce: v5.5.2_34066.20190614 not found

Machine Details:
sherlock@success-Lenovo-IdeaPad-S145:/Downloads/rtl/rtl8821ce$ uname -r
5.3.0-40-generic
sherlock@success-Lenovo-IdeaPad-S145:/Downloads/rtl/rtl8821ce$ uname
Linux
sherlock@success-Lenovo-IdeaPad-S145:/Downloads/rtl/rtl8821ce$ uname -a
Linux success-Lenovo-IdeaPad-S145 5.3.0-40-generic #3218.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SatanicRaw** [comment]
Need dkms logs

**Comment by tomaspinho** [comment]
Please share `dkms` logs. Or try building manually via `make` and post results here.

**Comment by chaitanyaGa** [comment]
DKMS make.log for rtl8821ce-v5.5.2_34066.20190614 for kernel 5.3.0-40-generic (x86_64)
Sun Mar 15 18:38:25 IST 2020
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.3.0-40-generic/build M=/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-40-generic'
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_security.o
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
scripts/Makefile.build:288: recipe for target '/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_cmd.o' failed
make[2]: *** [/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_cmd.o] Error 1
make[2]: *** Waiting for unfinished jobs....
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.o
scripts/Makefile.build:288: recipe for target '/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_security.o' failed
make[2]: *** [/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_security.o] Error 1
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_io.o
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
scripts/Makefile.build:288: recipe for target '/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.o' failed
make[2]: *** [/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.o] Error 1
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
scripts/Makefile.build:288: recipe for target '/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_io.o' failed
make[2]: *** [/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_io.o] Error 1
Makefile:1655: recipe for target '_module_/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build' failed
make[1]: *** [_module_/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-40-generic'
Makefile:2244: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by SatanicRaw** [comment]
Maybe the old version of GCC, show the output of the `gcc -v` command

**Comment by chaitanyaGa** [comment]
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-4ubuntu8' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu8)

**Comment by chaitanyaGa** [comment]
![Screenshot from 2020-03-15 23-15-26](https://user-images.githubusercontent.com/7933528/76707159-f4a8d900-6712-11ea-84f8-0376319f11c3.png)

**Comment by chaitanyaGa** [comment]
actually I ran 
sudo apt-get update && upgrade command and after that I started facing this issue, earlier it was working fine.

**Comment by tomaspinho** [comment]
Your logs say you are running Ubuntu 18.04, which has GCC `7.5`, but your GCC version is `4.8.5`. Don't know how you ended up in this situation, but upgrading GCC to the version in the official repos should fix the issue.

**Comment by chaitanyaGa** [comment]
thanks indeed it is the issue.
