### ISSUE TITLE
Error from running dkms-install.sh

### ISSUE THREAD

**Issue by dannydevilteo** [tomaspinho/rtl8821ce#136]
Hi Sir,
Encountered the error below when i tried running dkms-install.sh on my CENTOS 8. I hope you can give a workaround solution because I dont have a wireless network installed on my laptop. 

**lspci**
05:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter

**Log**
[make.log](https://github.com/tomaspinho/rtl8821ce/files/4432760/make.log)

**Error** output
sudo ./dkms-install.sh 
About to run dkms install steps...
Error! DKMS tree already contains: rtl8821ce-v5.5.2_34066.20200325
You cannot add the same module/version combo more than once.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j2 KVER=4.18.0-147.5.1.el8_1.x86_64...................(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.18.0-147.5.1.el8_1.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j2 KVER=4.18.0-147.5.1.el8_1.x86_64...................(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.18.0-147.5.1.el8_1.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/make.log for more information.
Finished running dkms install steps.

**Comment by tomaspinho** [comment]
Please search before you report issues. https://github.com/tomaspinho/rtl8821ce/issues/133

**Comment by dannydevilteo** [comment]
Thanks a lot sir. It solved my issue. You are a legend!

**Comment by csongit** [comment]
it didn't work for me. how can I solve this problem?
[make.log](https://github.com/tomaspinho/rtl8821ce/files/5603339/make.log)
