### ISSUE TITLE
Compiling error with linux 5.6.0

### ISSUE THREAD

**Issue by etty82** [tomaspinho/rtl8821ce#137]
Hi, 
after kernel upgrade to 5.6.0 I got this error compiling during dkms build.
Here's the last part of the log:

> CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/hal/hal_com.o
>/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/rtw_proc.c: In function ‘rtw_proc_create_entry’:
>/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/rtw_proc.c:70:71: error: passing >argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
>   70 |  entry = proc_create_data(name,  S_IFREG | S_IRUGO | S_IWUGO, parent, fops, data);
>     |                                                                       ^~~~
>     |                                                                       |
>     |                                                                       const struct file_operations *
>In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/../os_dep/linux/rtw_proc.h:18,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_intf.h:128,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:106,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/rtw_proc.c:17:
/usr/src/linux-5.6.0-1/include/linux/proc_fs.h:59:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
   59 | extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
      |                               ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-5.6.0-1/scripts/Makefile.build:269: /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/rtw_proc.o] Error 1
make[3]: *** Attesa per i processi non terminati....
make[2]: *** [/usr/src/linux-5.6.0-1/Makefile:1698: /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build] Error 2
make[1]: *** [../../../linux-5.6.0-1/Makefile:180: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-5.6.0-1-obj/x86_64/default'
make: *** [Makefile:2244: modules] Error 2

Thank you very much!

**Comment by tomaspinho** [comment]
This one has already been fixed. Completely remove the driver following instructions in the readme and reinstall.

**Comment by etty82** [comment]
Thanks, it builds fine!
