### ISSUE TITLE
Arch 5.6.3

### ISSUE THREAD

**Issue by shakna-israel** [tomaspinho/rtl8821ce#139]
I downloaded the latest master before the kernel upgrade, and then ran through upgrading the driver.

It now appears to be "broken". 75% of packets are dropped, the network seems to be going up and down constantly.

I do have some kind of dmesg trace, but getting it onto GitHub whilst we're in lockdown may take some effort.

It starts with a warning about net/wireless/sme.c:756

**Comment by shakna-israel** [comment]
Trace, hopefully helpful: https://shakna.keybase.pub/trace

(Thank goodness _some_ packets can get through)

**Comment by shakna-israel** [comment]
Remove driver, update to 5.6.4, make clean, install driver removes the error from dmesg, but doesn't fix the wifi behaviour.

**Comment by shakna-israel** [comment]
Completely removing any trace of the driver, running with 5.6.4-arch1-1, and the WiFi card is working perfectly...

Has this gone mainline? I know they were working on it, but it wasn't there yet. (And I previously needed this driver to get any connectivity...)

**Comment by deathowl** [comment]
> Completely removing any trace of the driver, running with 5.6.4-arch1-1, and the WiFi card is working perfectly...
> 
> Has this gone mainline? I know they were working on it, but it wasn't there yet. (And I previously needed this driver to get any connectivity...)

How so? For me not. Removed the package and from dkms too, but still  nothing

**Comment by shakna-israel** [comment]
I don't have the driver:

> sudo dkms status

> i2c-ch341, 20190628: added

Unrelated driver in dkms.

I do have WiFi connectivity via dhcpd.

And dmesg reports things working as expected.

> IPv6: ADDRCONF(NETDEV_CHANGE): wlp3s0: link becomes ready

And in depmod: rtw8821ce_hw_spec rtw88

Which suggests that rtw88 (mainline) is now handling the WiFi for me.

---

If this isn't the case for you, I'd try checking if everything is up to date. This is with Arch 5.6.4. Updating to 6.4, from 6.3 seemed to make the difference for me.

**Comment by deathowl** [comment]
Mainline did not support my wifi card with 5.6., so I downloaded the zip for rtl8821ce from github. Ran dkms install, and wifi card works, also I dont experience the packet loss issue

**Comment by deathowl** [comment]
Will send you dmks status and everything else in the afternoon, if it provides valuable information

**Comment by userofryzen** [comment]
> I don't have the driver:
> 
> > sudo dkms status
> 
> > i2c-ch341, 20190628: added
> 
> Unrelated driver in dkms.
> 
> I do have WiFi connectivity via dhcpd.
> 
> And dmesg reports things working as expected.
> 
> > IPv6: ADDRCONF(NETDEV_CHANGE): wlp3s0: link becomes ready
> 
> And in depmod: rtw8821ce_hw_spec rtw88
> 
> Which suggests that rtw88 (mainline) is now handling the WiFi for me.
> 
> If this isn't the case for you, I'd try checking if everything is up to date. This is with Arch 5.6.4. Updating to 6.4, from 6.3 seemed to make the difference for me.



> I don't have the driver:
> 
> > sudo dkms status
> 
> > i2c-ch341, 20190628: added
> 
> Unrelated driver in dkms.
> 
> I do have WiFi connectivity via dhcpd.
> 
> And dmesg reports things working as expected.
> 
> > IPv6: ADDRCONF(NETDEV_CHANGE): wlp3s0: link becomes ready
> 
> And in depmod: rtw8821ce_hw_spec rtw88
> 
> Which suggests that rtw88 (mainline) is now handling the WiFi for me.
> 
> If this isn't the case for you, I'd try checking if everything is up to date. This is with Arch 5.6.4. Updating to 6.4, from 6.3 seemed to make the difference for me.

Can you try the ISO of manajro in live cd to see if it's supporting the kernel indriver for this card? It has 5.6.7 so...

**Comment by dubhater** [comment]
@shakna-israel There is no 8821ce driver in the Arch Linux kernel: https://www.archlinux.org/packages/core/x86_64/linux/files/

`lspci -k` will tell you what kernel module is handling your wifi card. And then `modinfo <name>` will tell you where the module is in the filesystem. And then `pacman -Qo <file>` will tell you what package owns that file, if any.

Please share this info.

**Comment by tomaspinho** [comment]
RTW88 does not support this card yet. rtl8821ce is definitely being used, even if just as a remnant of a bad uninstallation via DKMS.

**Comment by MarcoIeni** [comment]
I am currently on LTS kernel on arch because this driver stopped working for me with Arch 5.6.2.
When I updated today I got an error and I thought it might be useful to share it here:

```
$ sudo pacman -Syu
...
==> dkms install rtl8821ce/1.0.5.r56.gfadb416 -k 5.6.13-arch1-1
Error! Bad return status for module build on kernel: 5.6.13-arch1-1 (x86_64)
Consult /var/lib/dkms/rtl8821ce/1.0.5.r56.gfadb416/build/make.log for more information.
...
```

The file /var/lib/dkms/rtl8821ce/1.0.5.r56.gfadb416/build/make.log does not exist.

```
$ ls /var/lib/dkms/rtl8821ce/1.0.5.r56.gfadb416
5.4.41-1-lts  source
```

**Comment by albatrossturkey1** [comment]
I think this is all good in 5.6.13-arch1-1  @MarcoIeni but it needed to be reinstalled for some reason.

```
$ dkms status
rtl8821ce, 1.0.5.r95.g69765eb, 5.6.13-arch1-1, x86_64: installed

```
**I don't recommend trying to fix this if you don't have an Ethernet cable or Hot-Spot available.**

Uninstalled rtl8821ce-dkms-git.
Rebooted
Reinstalled  using yay (warning, you can't use wifi to reinstall)

This fixed my tun error too and 1:30 boot up issue. 

Wrote a lot more about it it here:

[https://sick.codes/linux-lenovo-wifi-card-linux-not-working-rtl8821ce-slow-boot-process-a-job-is-running-1-minute-30-seconds/](url)

**Comment by MarcoIeni** [comment]
> Uninstalled rtl8821ce-dkms-git.
Rebooted
Reinstalled using yay (warning, you can't use wifi to reinstall)

Fixed! Thanks 😀

If this is the solution maybe this issue should be closed
