### ISSUE TITLE
-Werror=incompatible-pointer-types kernel 5.6.15

### ISSUE THREAD

**Issue by hwpfeil** [tomaspinho/rtl8821ce#144]
A struct type has changed in linux-5.6.15/include/linux/proc_fs.h or earlier, from file_operations to proc_ops. This affects rtl8821ce/os_dep/linux/rtw_proc.c, line 70, the call to proc_create_data. Instead of a struct file_operations pointer, they changed the parameter to a struct proc_ops pointer.

Sorry, I'm not smart enough to offer a patch.

**Comment by tomaspinho** [comment]
This was fixed a while ago. The code in master builds for 5.6. Mind reinstalling the driver following the instructions in the readme?

**Comment by hwpfeil** [comment]
Sorry about that! I am not using any of the "popular" distributions, no dkms. I copy the rtl8821ce folder into the kernel realtek folder, fix the Kconfig and Makefile, then`make modules`. In rtw_proc.c, each use of "fops" where a proc_ops pointer is supposed to be generates the above error. How does dkms get around that, can I delete the os_dep folder and forget about the /proc entries?

**Comment by tomaspinho** [comment]
Are you sure you have the most recent version of the repository? Following the procedure you described with the latest version should work.

**Comment by hwpfeil** [comment]
Thank you for reminding me to get a fresh git clone! Indeed, I was not using the Feb10 master. I'll go away now.

**Comment by tomaspinho** [comment]
Ahaha no worries!
