### ISSUE TITLE
Doesn't build for Kernel 5.8

### ISSUE THREAD

**Issue by tomaspinho** [tomaspinho/rtl8821ce#148]
I have the DKMS build log: https://pastebin.com/raw/T5dkTJnf

_Originally posted by @mthw0 in https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-644043229_

**Comment by ObserverOfTime** [comment]
That error can be fixed by renaming the struct but then [another error](https://clbin.com/gbDK0) occurs.
I'm also attaching my [kernel config](https://clbin.com/cOTLs) in case it's relevant.

**Comment by mthw0** [comment]
The new driver from https://github.com/lwfinger/rtlwifi_new/tree/rtw88 does work with Kernel 5.8, so it's possible to use this kernel with this card.

**Comment by tomaspinho** [comment]
Yes, this will most likely be a bridge version (5.8) for this driver. Once rtw88 is proven to be working well, I'll archive this repository and stop maintaining it.

**Comment by tomaspinho** [comment]
For people who can test the hardware on 5.8, here's a fix:
https://github.com/tomaspinho/rtl8821ce/pull/149

**Comment by ObserverOfTime** [comment]
The pull request works on RC2 while rtw88 fails to connect.

**Comment by juliokarl** [comment]
> The new driver from https://github.com/lwfinger/rtlwifi_new/tree/rtw88 does work with Kernel 5.8, so it's possible to use this kernel with this card.

Confirmed. I am running kernel 5.8.0-rc2+ with Chipset rtl8821ce and it works perfectly.
Thanks to @tomaspinho for running this repo, it has been very useful.

**Comment by mthw0** [comment]
There are now two AUR packages for the new driver, rtlwifi_new-rtw88-dkms and rtlwifi_new-rtw88-dkms-git does anybody know if there is any difference? They seem to be the same.

**Comment by NathanHannon** [comment]
> There are now two AUR packages for the new driver, rtlwifi_new-rtw88-dkms and rtlwifi_new-rtw88-dkms-git does anybody know if there is any difference? They seem to be the same.

isn't the git version just pulled straight from source, while the other one is just a binary blob?

**Comment by mthw0** [comment]
> > There are now two AUR packages for the new driver, rtlwifi_new-rtw88-dkms and rtlwifi_new-rtw88-dkms-git does anybody know if there is any difference? They seem to be the same.
> 
> isn't the git version just pulled straight from source, while the other one is just a binary blob?

No, they both pull from source, one of them uses custom dmks.conf for some reason.

**Comment by tomaspinho** [comment]
Closing this one as PR has been merged.

**Comment by smekkley** [comment]
Good news that the official support is coming to 5.9. 
But I'd like to thank @tomaspinho for maintaining this up until 5.8.  
The device I bought would have been useless without your effort on my Fedora!
