### ISSUE TITLE
Interface mode "monitor"

### ISSUE THREAD

**Issue by andreas-doubrava** [tomaspinho/rtl8821ce#15]
I am using Ubnutu 18.04.1 LTS.
Installation of the driver works fine.

Current supported interface modes are:
`# iw list`
(...)
`    Supported interface modes:`
`       * IBSS`
`       * managed`
`       * AP`
`       * P2P-client`
`       * P2P-GO`
(...)

What about implementing a support for `monitor` mode?

**Comment by tomaspinho** [comment]
Ask Realtek to do it, they may be open to it :smile:. I'm not developing the module, just maintaining the package. Closing this.
