### ISSUE TITLE
Ubuntu 20.04 with kernel 5.7.7

### ISSUE THREAD

**Issue by Electrocze** [tomaspinho/rtl8821ce#152]
Hi I have error in flashing linux kernel 5.7.7 (downloaded from https://kernel.ubuntu.com/~kernel-ppa/mainline/)
[make.log](https://github.com/tomaspinho/rtl8821ce/files/4883009/make.log)

**Comment by tomaspinho** [comment]
Make sure you're using the latest version of the driver. Uninstall and reinstall with the instructions in the Readme.
