### ISSUE TITLE
Как скачать с телефона?

### ISSUE THREAD

**Issue by sfhtthfs** [tomaspinho/rtl8821ce#154]
На телефоне нет кнопки «download zip”, можете залить этот архив на какой-нибудь файлообменник и скинуть сюда ссылку?

**Comment by sfhtthfs** [comment]
There is no download zip button on the phone, can you upload this archive to some file hosting service and send a link here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sfhtthfs** [comment]
Please also tell me how can I install this driver on the latest version of Ubuntu? Installation requires dkms, but Ubuntu does not have it and I don't know how to install it without internet

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sfhtthfs** [comment]
sorry for poor knowledge of english and linux

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sfhtthfs** [comment]
I tried to download dkms.deb, but I also need internet to install dkms

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sfhtthfs** [comment]
still in ubuntu there is no make command, I also do not know how to install without the Internet

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sfhtthfs** [comment]
help please I will be very grateful

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomaspinho** [comment]
I'm afraid you'll have to connect that computer to the internet somehow (ethernet?) and follow the instructions in the Readme.
