### ISSUE TITLE
wifi is not working

### ISSUE THREAD

**Issue by police-ice** [tomaspinho/rtl8821ce#155]
Hi, i'm use ideapad 320 and my networkcard version 8821ce but i cant install itz and my error:[ Error! DKMS tree already contains: rtl8821ce-v5.5.2_34066.20200325
You cannot add the same module/version combo more than once.
Error! echo
Your kernel headers for kernel 4.4.0-18362-Microsoft cannot be found at
/lib/modules/4.4.0-18362-Microsoft/build or /lib/modules/4.4.0-18362-Microsoft/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Error! echo
Your kernel headers for kernel 4.4.0-18362-Microsoft cannot be found at
/lib/modules/4.4.0-18362-Microsoft/build or /lib/modules/4.4.0-18362-Microsoft/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Finished running dkms install steps.]
Help Me Please :(
Kernel version 4.4.0-18362-Microsoft

**Comment by tomaspinho** [comment]
The answer is in the error message. You're missing headers for your Kernel.

**Comment by police-ice** [comment]
> 
> 
> The answer is in the error message. You're missing headers for your Kernel.
> 
> Edit: 4.4.0 is a very old Kernel. This driver may not work with it. Consider updating your system.

ok
How can i update kernel and system?

**Comment by police-ice** [comment]
im go to the https://www.kernel.org/ and see the 5.7.10 kernel on Lastest Release I should download itz?

**Comment by tomaspinho** [comment]
What's your Linux distribution?

**Comment by police-ice** [comment]
> What's your Linux distribution?

debian

**Comment by police-ice** [comment]
Tnx
For
Ever

**Comment by police-ice** [comment]
but it not has monitoring option :(

**Comment by tomaspinho** [comment]
Glad you found your way through installing this driver. Yes, it doesn't support monitoring mode.
