### ISSUE TITLE
Driver is not working on Kernel 5.8

### ISSUE THREAD

**Issue by furkn41** [tomaspinho/rtl8821ce#157]
![Screenshot_20200803_184652](https://user-images.githubusercontent.com/69159937/89201671-87f78380-d5ba-11ea-9ab6-995c9f41a465.jpeg)

**Comment by buboleck** [comment]
Compiles (Gentoo kernel 5.8.0) but there are some complains about missing symbols:

>>> Original instance of package unmerged safely.
 * Updating module dependencies for 5.8.0-gentoo ...
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol __cfg80211_alloc_event_skb
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol wiphy_register
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_remain_on_channel_expired
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_vendor_cmd_reply
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_del_sta_sinfo
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol wiphy_unregister
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_ch_switch_notify
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol ieee80211_get_channel_khz
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_ready_on_channel
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol wiphy_free
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol wiphy_new_nm
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_get_bss
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol ieee80211_freq_khz_to_channel
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol __cfg80211_send_event_skb
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_disconnected
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_michael_mic_failure
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_ibss_joined
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_scan_done
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_roamed
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_put_bss
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_connect_done
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_unlink_bss
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_inform_bss_frame_data
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_new_sta
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol __cfg80211_alloc_reply_skb
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol wiphy_apply_custom_regulatory
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_mgmt_tx_status
depmod: WARNING: //lib/modules/5.8.0-gentoo/net/wireless/8821ce.ko needs unknown symbol cfg80211_rx_mgmt_khz                                                    [ ok ]
 * Adding module to moduledb.
>>> net-wireless/rtl8821ce-driver-5.5.2_p20200630 merged.

**Comment by tomaspinho** [comment]
@furkn1 are you using the latest version in master? Can you perform a full uninstall, make sure you have the latest version and then reinstall? Instructions in the Readme

**Comment by tomaspinho** [comment]
Closing: this issue is related to the Ubuntu rtl8821ce-dkms package. Please report bugs in https://launchpad.net/ubuntu/+source/rtl8821ce/+bugs instead
