### ISSUE TITLE
Slow WiFi connection 

### ISSUE THREAD

**Issue by xtrator** [tomaspinho/rtl8821ce#158]
My connection speed is 100kbps where other devices get 50mbps

**Comment by tomaspinho** [comment]
Are you using Bluetooth? If so, try turning it off.

**Comment by Titaniumtown** [comment]
I'm trying to get someone to use linux, and they are getting this issue as well.

**Comment by by-speece** [comment]
I have this same problem, 
Distro : Arch
Kernel 5.9.8
Bluetooth : not installed (i dont need it)
