### ISSUE TITLE
-Wno-error=date-time build fail on kernel 5.7.0-kali1-amd64

### ISSUE THREAD

**Issue by tarunKoyalwar** [tomaspinho/rtl8821ce#161]
-Werror=date-time/macro “DATE” might prevent reproducible builds

error and build fail for above kernel 

**However**

EXTRA_CFLAGS += -Wno-error=date-time

at top of Makefile Fixed it

**Comment by tomaspinho** [comment]
Kali Linux is not a supported distribution, you're welcome to submit a PR if it doesn't break other users, though. 🙂
