### ISSUE TITLE
Not working on arch linux

### ISSUE THREAD

**Issue by botiapa** [tomaspinho/rtl8821ce#162]
I can't seem to get the module working on arch linux running kernel version 5.8.3-arch1-1. I installed the package from the AUR.

lspci reports that the network controller is using the iwlwifi kernel module. Running `dmesg | grep 8821ce` yields no results. However running `dkms status` returns the following: `rtl8821ce, 1.0.5.r104.g26e3caf, 5.8.3-arch1-1, x86_64: built`

The wifi card doesn't show up when running `ip link`, only the loopback device does. I'm not sure what I'm doing wrong, and would appreciate some help. 

Laptop: Lenovo yoga 530-14ikb

Thanks for working on this driver!

**Comment by tomaspinho** [comment]
When did you install the AUR package? Was it recently?

Have you followed the instructions on the README regarding Lenovo Yoga laptops?

**Comment by botiapa** [comment]
I installed it about 3 hours ago.

If you mean the the part about removing the ideapad_laptop module, then yes. I blacklisted it.

**Comment by tomaspinho** [comment]
Hum... no entries in `dmesg` means the module hasn't been loaded.

- Have you rebooted your machine after you installed the driver?
- Does it show up when you run `lsmod`?
- Can you run `lspci -k` and post here the results?

**Comment by botiapa** [comment]
- Yes I have rebooted it multiple times since installation
- No it doesn't show up.
- Yes sure, here it is: https://hastebin.com/ocewipipef

**Comment by tomaspinho** [comment]
No rtl8821ce seems to be present in your system. You seem to have this instead: https://ark.intel.com/content/www/us/en/ark/products/89450/intel-dual-band-wireless-ac-3165.html

**Comment by botiapa** [comment]
Yup, it was totally my bad. I was blocking the correct module. Thanks for the help and sorry for wasting your time.
