### ISSUE TITLE
No SSIDs for 22 MB/s or 33 MB/s

### ISSUE THREAD

**Issue by meddi** [tomaspinho/rtl8821ce#164]
Hello,

i have compiled the package for the kernel 4.14.70. No common dsitro (Thinstation)
The driver is loaded. Unfortunately I can't see all SSIDs.

iwlist wlan0 bitrate shows just 
wlan0 4 available bit-rates :
          1 Mb/s
          2 Mb/s
          5.5 Mb/s
          11 Mb/s

actually, 22 MB/s and 33 MB/s should be shown there as well, right? 
I used the current version of git.

**Comment by tomaspinho** [comment]
I believe this one was fixed when the bitmasks for these rates were backported into this repository a year or so ago. Please reopen if the current version doesn’t implement this properly.
