### ISSUE TITLE
Add dependencies to install dkms

### ISSUE THREAD

**Issue by iamm3chanic** [tomaspinho/rtl8821ce#174]
Your module works perfect!  
I have **HP pavilion x360**, OS **Fedora32**, with no eth port. And it was too hard without Ethernet to load all dependencies from USB-stick. This is essential for users with no network at all.  
So here is list of packages that I had to pull from https://pkgs.org/ :  
- **dkms**
- cmake
- **make**
- bc
- elfutils
- guile22
- zlibrary
- kernel-devel
- kernel-headers
- fmem-kernel-modules

I'd be glad if you add this note to README.md. Though different distros support different dependencies, that would be absolutely nice if you provide dependencies in some archive when we do _**git clone**_.  
Thanks!

**Comment by tomaspinho** [comment]
You're welcome to open a PR with your changes to the README. Please follow the existing structure. 🙂

**Comment by spielzeugland** [comment]
@tomaspinho what about enabling wiki for everyone to contribute such instructions without Pull Requests?

**Comment by tomaspinho** [comment]
> @tomaspinho what about enabling wiki for everyone to contribute such instructions without Pull Requests?

Wikis were enabled already, I have enabled editing for non-collaborators.

**Comment by iamm3chanic** [comment]
Thanks, I'll write this in wiki

**Comment by Graeme22** [comment]
@iamm3chanic could you elaborate on how to do this? I'd like to install arch on a PC but I'll need to transfer over dependencies via USB. Is it just the ones you mentioned above?

**Comment by iamm3chanic** [comment]
@Graeme22 In arch, it's quite simplier.  
You only need to transfer this [AUR-package](https://aur.archlinux.org/packages/rtl8821ce-dkms-git/) and all dependencies, mentioned there. You can take ithem as a package or as a cloned folder. Then when you transferred deps, you cannot make them via `makepkg -si` cause it will need to install deps from web.  
Use `makepkg -di` for each one and `makepkg -si` for the driver package.  
If still not enough deps, watch which are needed and transfer them too :)  
Hope this helps.

**Comment by iamm3chanic** [comment]
By the way, found another cheat way to install driver when having no ethernet or web.  
Using your phone and function USB-modem. It may not be supported on some devices, but there are apps in Play Market to improve it... So this way you only have to install `dkms`, `git` and the driver will be made easily with its deps.

**Comment by Graeme22** [comment]
@iamm3chanic Thanks for the quick reply. I managed to get everything set up using USB tethering with my Android. Cheers!
