### ISSUE TITLE
Compilation fails on 5.10-rc1

### ISSUE THREAD

**Issue by Kodehawa** [tomaspinho/rtl8821ce#178]
Leaving this as a tracker, since 5.10-rc1 is quite new. 

Using rtl8821ce with RFE2, so I still need this driver :p  

[make.log](https://github.com/tomaspinho/rtl8821ce/files/5448791/make.log)

Thanks you!

**Comment by tomaspinho** [comment]
Why would you be running a release candidate kernel? :sweat_smile: 

I'll see what I can do later

**Comment by Kodehawa** [comment]
> Why would you be running a release candidate kernel? sweat_smile
> 
> I'll see what I can do later

Because am masochist like that :p
Jokes aside, just wanted to test :)

**Comment by tomaspinho** [comment]
@Kodehawa can you try the code https://github.com/tomaspinho/rtl8821ce/pull/181 and report back if it works at all? It's a really stupid fix to compile, but am afraid I don't have the know how to do anything more advanced :/

**Comment by Kodehawa** [comment]
I'll try tomorrow :)

**Comment by Kodehawa** [comment]
Sorry. I had a surgery the day after (I have been able to be in the computer for the past days just fine though, just forgot afterwards probably due to being high in pain meds lol). 
I'll try it now and poke you back in a few.

**Comment by Kodehawa** [comment]
Considering am typing this on 5.10-rc3, I'll go with it works :)

**Comment by tomaspinho** [comment]
Ooof hope the surgery went well! Speedy recovery!

Thanks for writing back, I'm afraid of memory leaks, so would appreciate another report in the next few days if you can.

**Comment by Kodehawa** [comment]
Will do :)

**Comment by Kodehawa** [comment]
Haven't noticed anything odd on daily usage so far. Anything I should be aware of?

**Comment by tomaspinho** [comment]
Thanks for the feedback. I've needed the PR.
