### ISSUE TITLE
Connection unstable on Arch/Fedora 33/Pop!_OS/Ubuntu 20.10

### ISSUE THREAD

**Issue by mirkobrombin** [tomaspinho/rtl8821ce#179]
First of all, thank you very much for your immense work, seriously. (I have stability issues but at least it connects, seriously thanks).

I have tested this module on multiple distributions and it always works:
- Arch Linux
- Fedora 33
- Ubuntu 20.10
- Pop!_OS 20.10
- elementary OS 5

Compared to the module built into the 5.9 kernel, with yours I get better performance in terms of down/up.
Unfortunately, the only flaw I find in all distributions (inexplicably except on elementary os 5), is the constant drop of the connection. At irregular intervals, the ping increases inexplicably, reaching over 500ms.

I found the same problem with different behaviors for each distribution:
- on **Arch Linux** and **Fedora 33** the ping goes up, the connection drops and I have to wait up to a minute for it to reconnect
- on **Pop!_OS and Ubuntu 20.10** ping increases at intervals of 2 and 5 minutes, starting from 20ms and reaching 500ms (when we are lucky) 
- on **elementary OS 5** just works... really idk what is (wrong) but it works without connection drops or unstable ping

**My connection** is stable on other devices (a Xiaomi Notebook Pro with iwlwifi).

In all cases I have verified that no module is loaded other than yours (disabling the one in kernel 5.9 for example). Unfortunately the result does not change.

I have been investigating the problem for months without finding a solution and unfortunately I cannot use elementary as my main distribution due to the instability of the Nvidia drivers.

I am available to provide any details, information and logs in case they are useful to the investigation (in case it begins).

**Comment by tomaspinho** [comment]
Hey, Mirko.

Thanks a lot for the kind words and thorough testing.

This looks like the issues other users have been experiencing with access point scanning while connected to a network. Your network applet is probably initiating scans periodically and that is causing the slow downs or drop outs.

If you're up to that, you could try investigating changing the frequency of scanning or disabling it altogether.

Best.

**Comment by mirkobrombin** [comment]
> Hey, Mirko.
> 
> Thanks a lot for the kind words and thorough testing.
> 
> This looks like the issues other users have been experiencing with access point scanning while connected to a network. Your network applet is probably initiating scans periodically and that is causing the slow downs or drop outs.
> 
> If you're up to that, you could try investigating changing the frequency of scanning or disabling it altogether.
> 
> Best.

Thanks for instant reply. Of course, just Idk how to do this on GNOME.

**Comment by mirkobrombin** [comment]
The advice seems to work, for about 1 hour I have not had network drops or crazy ping problems.

### How to fix
For posterity, here's how I solved it with NetworkManager and GNOME.

In the WiFi settings I set the BSSID in the `network profile > Identity tab`.

I read online that the Connectivity Check option of NetworkManager can be disabled. This by editing the file in `/var/lib/NetworkManager/NetworkManager-intern.conf` and adding the following instructions:

```
[connectivity]
.set.enabled=false
```

Then just reboot or restart the unit `NetworkManager` to fix the problem.

Thanks again @tomaspinho for the tip and great work!

**Comment by tomaspinho** [comment]
Great tip, would you like to open a PR to add that to README? Would be splendid.

**Comment by mirkobrombin** [comment]
> Great tip, would you like to open a PR to add that to README? Would be splendid.

All right. I am also testing on Fedora.

**Comment by ghnk** [comment]
I am using Fedora 34 Workstation Edition,GNOME.
The Wi-Fi signal is unstable after the latest updates a few days ago.
This is my [question](https://ask.fedoraproject.org/t/how-to-fix-an-unstable-wireless-connection/14779/4), but very difficult for me as a normal user.
Can you please help me ?
