### ISSUE TITLE
Kernel 4.19.12-2 Manjaro

### ISSUE THREAD

**Issue by swengkie88** [tomaspinho/rtl8821ce#18]
Hi sir,
I get this error in my manjaro latest build...

`Your kernel headers for kernel 4.19.12-2-MANJARO cannot be found at
/usr/lib/modules/4.19.12-2-MANJARO/build or /usr/lib/modules/4.19.12-2-MANJARO/source.`

Please help sir,, I need my wifi adapter ,,

**Comment by tomaspinho** [comment]
Have you installed the kernel headers package for your distribution?

**Comment by swengkie88** [comment]
ohh ... sory,, its not been installed before ...  and now everything has been installed ... very thank you for your hardwork ..

**Comment by CCCLARITY** [comment]
same error and i got the output 4.19.0-3-MANJARO after command uname -r. 
what can i do for this. 
thx

**Comment by tomaspinho** [comment]
Have you installed the kernel headers package for your distribution?

**Comment by BeautyYuYanli** [comment]
i got the same error but i have installed both`linux419-headers` and`linux-rt-manjaro-headers` on my `linux 4.19.26-1-manjaro` .so how can i deal with it?

**Comment by BeautyYuYanli** [comment]
@BeautyYuYanli i solved my problem by updating all the packages. sorry for disturbing.
