### ISSUE TITLE
Monitor mode

### ISSUE THREAD

**Issue by NotCatz** [tomaspinho/rtl8821ce#182]
Monitor mode cannot be enabled, even tho it is supported by default

**Comment by tomaspinho** [comment]
https://github.com/tomaspinho/rtl8821ce/issues/168
https://github.com/tomaspinho/rtl8821ce/issues/101
https://github.com/tomaspinho/rtl8821ce/issues/20
https://github.com/tomaspinho/rtl8821ce/issues/15
