### ISSUE TITLE
Wifi working worst every time it stops working

### ISSUE THREAD

**Issue by salva09** [tomaspinho/rtl8821ce#184]
Hi, thanks for the work in the driver. I have problem with the wifi, when I recently installed the driver it worked fine, almost perfetly, but after some hours, the wifi stopped working and I had to reboot to make it work again, then at the next time it occured more frequently at the point that rebooting doesn't fix it anymore. It first happened with the driver provided from the ubuntu repositories, then changed to using directly from this repo but happened again. When I get disconnected and click to connect to my network again, it just doesn't connect, and keeps trying.
I'm currently using Pop! os 20.10.
I've tried adding the necesary to stop the scan from NetworkManager in ```/var/lib/NetworkManager/NetworkManager-intern.conf```, disabling any type of power managment for the wifi, and removing and re-enable the module.
Thanks in advance!

**Comment by mirkobrombin** [comment]
Which kernel use provide the latest Pop!_OS release?

**Comment by salva09** [comment]
> Which kernel version provide the latest Pop!_OS release?

5.8

**Comment by salva09** [comment]
This issue got fixed after switching to manjaro
