### ISSUE TITLE
'No Networks' Fedora 33 -IdeaPad L340-Fedora 33 

### ISSUE THREAD

**Issue by azseza** [tomaspinho/rtl8821ce#185]
Model IdeaPad L340-15IRH Gaming
no network is detected, did try to clean up old kernels and reinstall this driver.
did also try switching it on and off via terminal.

**Comment by mirkobrombin** [comment]
Which kernel?

**Comment by dknight** [comment]
Same for Lenovo thinkpad, installed successful without any warnings/errors. But no network
Kernel 5.9.8-200.fc33.x86_64

**Comment by mirkobrombin** [comment]
Is the `rtw88` module blacklisted?

**Comment by dknight** [comment]
Yes I have blacklisted the module
/etc/modprobe.d/blacklist
`blacklist rtw88
blacklist rtw88_8821ce
blacklist rtw88_pci
blacklist rtw88_core
blacklist rtw88_8821c`

lsmod | grep 8821
`l8821ce               1970176  0
cfg80211              843776  3 mac80211,rtl8187,8821ce`

lspci -k
`05:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
        Subsystem: Lenovo Device c024
        Kernel driver in use: rtl8821ce
        Kernel modules: 8821ce
`

But still no networks, trying to investigate further

**Comment by dknight** [comment]
Ok, by some reason it magically started to work.

1. Disabled Secure Boot in BIOS
2. Create file by creating file `/etc/modprobe.d/rtw88_blacklist.conf` with contents:
```
blacklist rtw88
blacklist rtw88_8821ce
blacklist rtw88_pci
blacklist rtw88_core
blacklist rtw88_8821c
```
3. Where you have cloned source from git
```
cd rtl8821ce
make clean
sudo ./dkms-remove.sh
```
4. Reboot
5. Again in source directory
```
sudo ./dkms-install.sh
```

Started to work as a charm. I have no idea why, I tried same procedure about 10 times without no result. Maybe Secure Boot somehow affects this. Absolutely have no idea, just started to work....

**Comment by mirkobrombin** [comment]
It's not magical, it's how it should be hahaha

**Comment by azseza** [comment]
Thanks works fine !

**Comment by azseza** [comment]
Thank you , works just as new !!

**Comment by azseza** [comment]
Thanks works perfectly !!!

**Comment by nunorfidalgo** [comment]
Confirm what @dknight has posted, have the same laptop and has a big help to bring my wifi back in working order. Thx
