### ISSUE TITLE
Error! DKMS tree already contains: rtl8821ce-v5.5.2_34066.20200325 You cannot add the same module/version combo more than once. Error! echo

### ISSUE THREAD

**Issue by rahman7616** [tomaspinho/rtl8821ce#186]
hello sir im a new ..pless help me.some day ago its work perfectly now its show      

:~/rtl8821ce$ sudo ./dkms-install.sh
About to run dkms install steps...
Error! DKMS tree already contains: rtl8821ce-v5.5.2_34066.20200325
You cannot add the same module/version combo more than once.
Error! echo
Your kernel headers for kernel 5.7.0-kali1-amd64 cannot be found at
/lib/modules/5.7.0-kali1-amd64/build or /lib/modules/5.7.0-kali1-amd64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Error! echo
Your kernel headers for kernel 5.7.0-kali1-amd64 cannot be found at
/lib/modules/5.7.0-kali1-amd64/build or /lib/modules/5.7.0-kali1-amd64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Finished running dkms install steps.

**Comment by micwoj92** [comment]
You should not be using Kali Linux.

**Comment by rahman7616** [comment]
thanks for your comment,,,now I'm fix it myself
