### ISSUE TITLE
Wifi doesn't work on kernel 5.9 even after blacklisting rtw_8821ce

### ISSUE THREAD

**Issue by aliymahmoud** [tomaspinho/rtl8821ce#188]
After installing kernel version 5.9.9, wifi stopped working, after searching for the issue, it showed up that kernel 5.9 officially supports realtek. 
But even after removing the dkms and using the official module coming with the kernel, wifi didn't seem to work, so I blacklisted the module 
```
echo "blacklist rtw_8821ce" >> /etc/modprob.d/rtw88_blacklist.conf

```
Then I reinstalled the dkms
```
cd rtl8821ce 
sudo ./dkms-remove.sh
make clean 
#reboot
cd rtl8821ce 
sudo ./dkms-install.sh
```
But still the wifi doesn't work, it keeps searching for networks with no results.
Am I missing something? Thx.

**Comment by darkretailer** [comment]
Please try to shutdown your system for some time (in my case i waited between half an hour till an hour) and boot it up, after i added "rtw_8821ce" to the blacklist.

I tried this many times... blacklisted, removed the blacklist and soon.
Every time i did not wait and make just a reboot, i had problems.
But when i shutdown the system and tested it later it was working.

**Comment by aliymahmoud** [comment]
> Please try to shutdown your system for some time (in my case i waited between half an hour till an hour) and boot it up, after i added "rtw_8821ce" to the blacklist.
> 
> I tried this many times... blacklisted, removed the blacklist and soon.
> Every time i did not wait and make just a reboot, i had problems.
> But when i shutdown the system and tested it later it was working.

    I'm amazed at how did that actually solved the problem.. I didn't shutdown my laptop for ages, never thought it could be the solution.. thank you

**Comment by sergiomb2** [comment]
Well, I'm amazed too,  turning off the computer for a while solved the problem
but only tomaspinho/rtl8821ce worked, I tried the rtw88 provided by the kernel but it didn't work.
So for kernel 4.9.x+ we need add [1] to /etc/modprobe.d/rtw88_blacklist.conf 

[1]
```
blacklist rtw88
blacklist rtw88_8821ce
blacklist rtw88_8821c
blacklist rtw88_pci
blacklist rtw88_core
```

**Comment by degasus** [comment]
I was affected by this as well, just rebooting was not fine. However unpower it for one minute fixed it. Waiting for half an hour is likely too much. Thanks for pointing this out and for maintaining this dkms driver.

**Comment by rkanapka** [comment]
> Please try to shutdown your system for some time (in my case i waited between half an hour till an hour) and boot it up, after i added "rtw_8821ce" to the blacklist.
> 
> I tried this many times... blacklisted, removed the blacklist and soon. Every time i did not wait and make just a reboot, i had problems. But when i shutdown the system and tested it later it was working.

Thanks. Had this error after installing debian 13 into n100 mini pc. Disabled wifi on bios but restarting pc didn't help. After shuting off pc for ~1minute, error was gone and I could login.
