### ISSUE TITLE
Bluetooth not working [0bda:b00a]

### ISSUE THREAD

**Issue by wahsot** [tomaspinho/rtl8821ce#19]
Running Archlinux on HP 4NZ54PA, with your AUR package [rtl8821ce-dkms-git](https://aur.archlinux.org/packages/rtl8821ce-dkms-git/).
```
$ rfkill
ID TYPE      DEVICE      SOFT      HARD
 0 bluetooth hci0   unblocked unblocked
 1 wlan      phy0   unblocked unblocked
```
The MAC address is all zeroes.
```
$ hciconfig -a
hci0:   Type: Primary  Bus: USB
        BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0
        DOWN 
        RX bytes:14 acl:0 sco:0 events:1 errors:0
        TX bytes:3 acl:0 sco:0 commands:1 errors:0
        Features: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
        Packet type: DM1 DH1 HV1 
        Link policy: 
        Link mode: SLAVE ACCEPT 
```
Some related kernel messages.
```
[    0.000000] Linux version 4.19.12-arch1-1-ARCH (builduser@heftig-21538) (gcc version 8.2.1 20181127 (GCC)) #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018
...
[    4.230415] usb 3-2.3: new full-speed USB device number 4 using xhci_hcd
[    4.340266] usb 3-2.3: New USB device found, idVendor=0bda, idProduct=b00a, bcdDevice= 1.10
[    4.340269] usb 3-2.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.340271] usb 3-2.3: Product: Bluetooth Radio 
[    4.340272] usb 3-2.3: Manufacturer: Realtek 
[    4.340273] usb 3-2.3: SerialNumber: 00e04c000001
...
[    9.955545] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    9.983859] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    9.985375] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[    9.985380] cfg80211: failed to load regulatory.db
[   10.018686] 8821ce: loading out-of-tree module taints kernel.
[   10.034138] 8821ce: module verification failed: signature and/or required key missing - tainting kernel
[   10.050022] videodev: Linux video capture interface: v2.00
[   10.070445] kvm: disabled by bios
[   10.073367] RTW: module init start
[   10.073369] RTW: rtl8821ce v5.2.5_1.26055.20180108
[   10.073370] RTW: build time: Dec 29 2018 20:00:46
[   10.073372] RTW: rtl8821ce BT-Coex version = COEX20170310-1212
[   10.073652] RTW: [HALMAC]13348M
[   10.073653] RTW: [HALMAC]HALMAC_MAJOR_VER = 1
[   10.073654] RTW: [HALMAC]HALMAC_PROTOTYPE_VER = 3
[   10.073655] RTW: [HALMAC]HALMAC_MINOR_VER = 6
[   10.073656] RTW: [HALMAC]HALMAC_PATCH_VER = 2
[   10.073664] RTW: [HALMAC]13359M
[   10.073665] RTW: [HALMAC]HALMAC_MAJOR_VER_88XX = 1
[   10.073665] RTW: [HALMAC]HALMAC_PROTOTYPE_88XX = 3
[   10.073666] RTW: [HALMAC]HALMAC_MINOR_VER_88XX = 6
[   10.073667] RTW: [HALMAC]HALMAC_PATCH_VER_88XX = 2
[   10.077638] snd_hda_intel 0000:04:00.1: Handle vga_switcheroo audio client
[   10.085819] Bluetooth: Core ver 2.22
[   10.085894] NET: Registered protocol family 31
[   10.085895] Bluetooth: HCI device and connection manager initialized
[   10.085902] Bluetooth: HCI socket layer initialized
[   10.085905] Bluetooth: L2CAP socket layer initialized
[   10.085914] Bluetooth: SCO socket layer initialized
[   10.094396] RTW: WARN [HALMAC][WARN]Dump logical efuse in suspend mode
[   10.096464] r8169 0000:02:00.0 eno1: renamed from eth0
[   10.098796] RTW: 0x000: 
... a lot of hex values ...
[   10.099281] RTW: rtw_read_efuse_from_file /system/etc/wifi/wifi_efuse_8821ce.map is not readable
[   10.099294] RTW: hal_com_config_channel_plan chplan:0x7F
[   10.107683] RTW: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
...
[   10.130886] RTW: rtw_ndev_init(wlan0) if1 mac_addr=dc:a2:66:62:67:61
[   10.131500] RTW: module init ret=0
[   10.137779] rtl8821ce 0000:03:00.0 wlo1: renamed from wlan0
[   10.141227] usbcore: registered new interface driver btusb
[   10.143287] Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=826c lmp_ver=08 lmp_subver=a99e
[   10.143291] Bluetooth: hci0: RTL: rtl: unknown IC info, lmp subver a99e, hci rev 826c, hci ver 0008
...
[   17.542001] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   17.542002] Bluetooth: BNEP filters: protocol multicast
[   17.542007] Bluetooth: BNEP socket layer initialized
```
Thanks for your work, let me know if there's anything else you need.

**Comment by tomaspinho** [comment]
Hey @wahsot 

What happens when you ` sudo hciconfig hci0 up`?

**Comment by wahsot** [comment]
Hi @tomaspinho,
```
$ sudo hciconfig hci0 up
Can't init device hci0: Invalid argument (22)
```

**Comment by tomaspinho** [comment]
Can you paste here the output of `lsusb -t`?

**Comment by wahsot** [comment]
```
$ lsusb -t
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 10000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
    |__ Port 2: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 1: Dev 3, If 1, Class=Video, Driver=uvcvideo, 480M
        |__ Port 1: Dev 3, If 0, Class=Video, Driver=uvcvideo, 480M
        |__ Port 3: Dev 4, If 0, Class=Wireless, Driver=btusb, 12M
        |__ Port 3: Dev 4, If 1, Class=Wireless, Driver=btusb, 12M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 480M
    |__ Port 3: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 4: Dev 4, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
    |__ Port 4: Dev 3, If 0, Class=Mass Storage, Driver=usb-storage, 480M
```

**Comment by tomaspinho** [comment]
Thanks for the update on the vendor and device IDs. Actually it looks like we don't have the same adapter, mine prints:

```
  idVendor           0x0bda Realtek Semiconductor Corp.
  idProduct          0xc024 
```

**Comment by wahsot** [comment]
I have been digging through the Ubuntu patches
https://patchwork.ozlabs.org/project/ubuntu-kernel/list/?submitter=9280

It keeps referring to 8211CU for bluetooth, should I try [rtl8821cu-dkms-git](https://aur.archlinux.org/packages/rtl8821cu-dkms-git/) to test its bluetooth?

Could this be a kernel issue instead? Should I raise a ticket to Arch?

**Comment by tomaspinho** [comment]
Yes, it may be that you have the CU variant. I don't believe that these adapters have upstream support yet, so official support will take a long while.

**Comment by wahsot** [comment]
I tried 8211CU, the wifi then doesn't work.
What's your kernel / dmesg line in comparison with:
`Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=826c lmp_ver=08 lmp_subver=a99e`

**Comment by tomaspinho** [comment]
```
[    3.317578] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000c lmp_ver=08 lmp_subver=8821
```

**Comment by tomaspinho** [comment]
Wow, amazing work! Would you be so kind as to write up a quick tutorial on how to solve this kind of problem so that I can include it in the README? If you're up for that, a Pull Request is incredibly welcome.

Yes, I get a ton of those errors and Bluetooth devices work well.

**Comment by wahsot** [comment]
## Bluetooth [0bda:b00a] Archlinux Kernel Patch
### Diagnosis
Verify that your Bluetooth is **not** detected as `lmp_subver=8221` & `hci_ref=000c`.
```
$ dmesg | grep 'RTL: rtl:'
[   10.143287] Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=826c lmp_ver=08 lmp_subver=a99e
[   10.143291] Bluetooth: hci0: RTL: rtl: unknown IC info, lmp subver a99e, hci rev 826c, hci ver 0008
```
### Prepare Linux
Follow the steps on Arch Wiki [Kernel/Arch Build System](https://wiki.archlinux.org/index.php/Kernel/Arch_Build_System).
```
$ asp update linux
$ asp checkout linux
$ cd linux/trunk
```
### Patch and Build
Extract this ZIP file to the current directory [linux-4.20-rtl8821ce-b00a.zip](https://github.com/tomaspinho/rtl8821ce/files/2735466/linux-4.20-rtl8821ce-b00a.zip).
Should you have a different `IC_INFO(lmp_subver, hci_rev)`, update it inside "rtl8821ce-b00a.patch".
Should you have a different kernel version to 4.20, don't run `patch` and just open in text editor to humanly patch PKGBUILD.
```
$ patch -p0 -i pkgbuild.diff
$ makepkg -L
```
### Install
Makepkg should have created 3 files: kernel, headers and docs (optional).
Remember to update your bootloader with this new custom kernel.
```
# pacman -U linux-custom{,-headers}-4.20.arch1-1-x86_64.pkg.tar.xz
```

**Comment by thatmadhacker** [comment]
this worked for my computer

**Comment by tomaspinho** [comment]
Great, I've added the link to @wahsot 's tutorial in the README. :bowing_man:

**Comment by wahsot** [comment]
Coming back from Linux's [Bugzilla 201921](https://bugzilla.kernel.org/show_bug.cgi?id=201921):
This bug appears after rebooting from Linux.
When cold-booting the laptop, Bluetooth works with the vanilla kernel.
The patch in this ticket is still relevant if you need to restart your computer.

We could probably just close this ticket here as it's a kernel issue.
Thanks for your time.

**Comment by IceM4nn** [comment]
Hey @wahsot can you show us some guide to do that on debian based distro? where the rtl8821ce-b00a.patch should run?

**Comment by IceM4nn** [comment]
is there a method to patch it without recompile the whole kernel? or is it possible to make it as a dkms module? (for this little bluetooth patch only)

**Comment by IceM4nn** [comment]
Nevermind, I got my bluetooth running now. forgot to enable bluetooth.service. thanks

**Comment by alfabuster** [comment]
OS: Solus x86_64 
Host: TUF Gaming FX505DY_TUF505 1.0 
Kernel: 5.1.14-121.current 

Wi-Fi works great, bluetooth doesn't work...

**Comment by wahsot** [comment]
> Wi-Fi works great, bluetooth doesn't work...

Can you provide Bluetooth kernel logs?
`$ dmesg | grep Bluetooth`

Does it show a different `lmp_subver` / `hci_rev` number after rebooting compared to a fresh start?

**Comment by BurningGrip3** [comment]
Can someone please post a guide on what to do if your kernel version is different than 4.20? Because that part is a bit confusing.
I'm running kernel 5.8.9-arch2-1.

**Comment by roninvanderwerke** [comment]
Same I also get confused when asked to humanly patch. I changed the kernel name in the patch but that doesn't work. I'm on Manjaro 5.8.11-1.

> Can someone please post a guide on what to do if your kernel version is different than 4.20? Because that part is a bit confusing.
> I'm running kernel 5.8.9-arch2-1.

**Comment by BurningGrip3** [comment]
> Can someone please post a guide on what to do if your kernel version is different than 4.20? Because that part is a bit confusing.
> I'm running kernel 5.8.9-arch2-1.

Anyone?

**Comment by williamd5** [comment]
Same issue on Ubuntu 20.04.01 LTS kernel 5.8.0-38-generic. The APT driver doesn't work either.
Anyone got any info?

**Comment by riyuuzaki-git** [comment]
I am having the same issue. On Ubuntu 20.04 

My device is bind to another driver. And it seems that i cannot bind it to the one you published 🙁
`root@LION-SLEW1:~# lspci | grep Realtek 
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter`

The first one is the Bluetooth Device and the second one is the Netword Card, which i found to be one and only one card that does both jobs.

But here is the issue : 

`root@LION-SLEW1:/sys/bus/pci/devices/0000:02:00.0# ls -l | grep driver 
total 0
lrwxrwxrwx 1 root root     0 zan 24 02:00 driver -> ../../../../bus/pci/drivers/r8169`

And this driver is not what it should be

I tried to manually unbind and bind the rtl8821ce driver, but it won't let me.

`root@LION-SLEW1:/sys/bus/pci/devices# echo -n "0000:02:00.0" > /sys/bus/pci/drivers/r8169/unbind
root@LION-SLEW1:/sys/bus/pci/devices# echo -n "0000:02:00.0" > /sys/bus/pci/drivers/rtl8821ce/bind 
-bash: echo: write error: No such device`

I downloaded another driver that seems to be doing the same thing, and tried to bind it, but i got the same result.
`root@LION-SLEW1:/sys/bus/pci/devices# echo -n "0000:02:00.0" > /sys/bus/pci/drivers/rtw_8821ce/bind 
-bash: echo: write error: No such device`


I would be very grateful if anyone can help me please.

**Comment by williamd5** [comment]
For me it resolved after typing `sudo modprobe btrtl` `sudo systemctl restart bluetooth` `sudo bluetoothctl` `power on`

**Comment by riyuuzaki-git** [comment]
> For me it resolved after typing `sudo modprobe btrtl` `sudo systemctl restart bluetooth` `sudo bluetoothctl` `power on`

I tried it but it won't work :(

root@LION-SLEW1:~# sudo modprobe btrtl
root@LION-SLEW1:~# systemctl restart bluetooth
root@LION-SLEW1:~# bluetoothctl power on
No default controller available
root@LION-SLEW1:~#

**Comment by Jangberry** [comment]
I think I begin to see a patern: each time I upgrade my kernel (so dkms do another build) it potentially break the bluetooth (damaged wifi only once). Some times removing it from dkms tree and rebuilding it specifically for the new kernel appart from the upgrade routine is enough but sometimes I need to install or remove btrtl... (what a nightmare)

I run Debian sid, and for instance with Kernel `5.10.0-1` I needed to install btrtl, for `5.10.0-2` nothing has been needed, and finnally for `5.10.0-3` I needed to remove brtrtl (I also tried to reinstall rtl8821ce as a first attempt but it didn't seemed to do much)

Hope it helps for debugging

BTW my computer is an Asus TUF 505DY and almost none of the diagnostics/fixes that works with Lenovo computers works on mine... for instance `dmesg | grep 'RTL: rtl:'` doesn't output anything, I can't (obviously) install lenovo's binaries, etc...

**Comment by vascofaraujo** [comment]
For those on Debian that still have problems, what did the trick for me was installing `firmware-realtek`.

**Comment by damiCodes** [comment]
> For those on Debian that still have problems, what did the trick for me was installing `firmware-realtek`.

Just wanna confirm this works like a charm. Thanks, Vasco.

**Comment by nimaipatel** [comment]
I'm running Arch with LTS kernel and the Bluetooth does stop working out of nowhere sometimes.

```sh
$ bluetoothctl power on
No default controller available
```

However, I've noticed that locking the session using a login manager, closing the lid, waiting for a couple of seconds (say 10), and then unlocking the session seems to just make Bluetooth work somehow. This ritual works every single time and sure beats rebooting.

I'm using awesomewm with lightdm and use `dmtool lock` to lock the session.

**Comment by Viom888** [comment]
# sudo apt-get update
# sudo apt-get install firmware-realtek

I tried this and worked

**Comment by Rustmilian** [comment]
> BTW my computer is an Asus TUF 505DY and almost none of the diagnostics/fixes that works with Lenovo computers works on mine... for instance `dmesg | grep 'RTL: rtl:'` doesn't output anything, I can't (obviously) install lenovo's binaries, etc...

Because that's a bad command. 
use either `dmesg | grep 'RTL:'` or `dmesg | grep Bluetooth` for example.
```
sudo dmesg | rg 'RTL:' 

[   10.813025] Bluetooth: hci0: RTL: examining hci_ver=08 hci_rev=000c lmp_ver=08 lmp_subver=8821
[   10.814570] Bluetooth: hci0: RTL: rom_version status=0 version=1
[   10.814575] Bluetooth: hci0: RTL: loading rtl_bt/rtl8821c_fw.bin
[   10.816196] Bluetooth: hci0: RTL: loading rtl_bt/rtl8821c_config.bin
[   10.816290] Bluetooth: hci0: RTL: cfg_sz 10, total sz 34926
[   11.426197] Bluetooth: hci0: RTL: fw version 0x75b8f098
```
