### ISSUE TITLE
WiFi not working in Linux 5.9.13 on ArchLabs

### ISSUE THREAD

**Issue by PeisongXiao** [tomaspinho/rtl8821ce#193]
I tried blacklisting rtw88 and reinstalling rtl8821ce-dkms multiple times but it still doesn't work. Also, when I removed rtl8821ce-dkms, a message from rmdir told me that dkms was trying to remove a nameless folder like '' (I suspect there's some encoding issues)

**Comment by tomaspinho** [comment]
You need to blacklist rtw88_8821ce. Can you provide the outputs of `lspci -k` and of the installation procedure you used for rtl8821ce?

**Comment by BigmenPixel0** [comment]
Create /etc/modprobe.d/rtw88.conf and add:
blacklist rtw88_8821ce
blacklist rtw88_core
blacklist rtw88
blacklist rtw88_pci

**Comment by BigmenPixel0** [comment]
After you need shutdown on some minutes

**Comment by tomaspinho** [comment]
Please follow https://github.com/tomaspinho/rtl8821ce/blob/master/README.md#wi-fi-not-working-for-kernel--59
