### ISSUE TITLE
network very slow

### ISSUE THREAD

**Issue by zayronxio** [tomaspinho/rtl8821ce#199]
I am using the version rtl8821ce-v5.5.2_34066.20200325 in ubuntu 20.10, I have wifi and bluetooth but it is slow, my internet provider offers me 20mb / s, but it only reaches 720kbps

**Comment by NastyGamer** [comment]
Are you using Wifi and Bluetooth at the same time?

**Comment by tomaspinho** [comment]
If you are, turn off Bluetooth. It's a known limitation.

See: https://github.com/tomaspinho/rtl8821ce/issues/138
