### ISSUE TITLE
Error compiling with debian testing 5.9

### ISSUE THREAD

**Issue by txapito** [tomaspinho/rtl8821ce#200]
I attach screenshot of the error, it happens even if I blacklist module as described by devs.
Thanks.
![IMG_20210108_223142](https://user-images.githubusercontent.com/76683767/104066478-c3e5e300-5201-11eb-8e79-8560b2bfecec.jpg)

**Comment by SatanicRaw** [comment]
Need a make.log file, the error message says where it is, put it here.

**Comment by txapito** [comment]
just solved.
on my laptop, I had to blacklist not only rtw88_8821ce, but also all the dipendences of the module, so here it is my output of /etc/modprobe.d/blacklist.conf:

blacklist rtw88_8821ce
install rtw88_8821ce /bin/true

hope it helps.
