### ISSUE TITLE
Is miracast awaible

### ISSUE THREAD

**Issue by grsm2020** [tomaspinho/rtl8821ce#202]
Hello, thanks for your work. Is miracast awaible in this driver?

**Comment by grsm2020** [comment]
Cannot connect to LG smart TV

**Comment by grsm2020** [comment]
** (gnome-network-displays:19790): DEBUG: 00:16:56.684: Got state change notification from streaming sink to state ND_SINK_STATE_ERROR
tcpdump show nothing trying to connect

**Comment by tomaspinho** [comment]
Unfortunately not.
