### ISSUE TITLE
Cannot add virtual interface command failed: No such device (-19)

### ISSUE THREAD

**Issue by grsm2020** [tomaspinho/rtl8821ce#204]
Trying anything phy pth0 etc

sudo iw wlp1s0 interface add p2p0 type managed

command failed: No such device (-19)

iwconfig
lo        no wireless extensions.

enp2s0    no wireless extensions.

wlp1s0    IEEE 802.11AC  ESSID:"Home Wi-Fi"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:5.18 GHz  Access Point: 3C:84:6A:E5:DC:E1   
          Bit Rate:434 Mb/s   Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=71/100  Signal level=71/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

**Comment by tomaspinho** [comment]
Yeah, there's no support for WiFi Direct or monitor mode for this driver.
