### ISSUE TITLE
Error on install, /bin/sh: 1: bc: not found

### ISSUE THREAD

**Issue by redscience** [tomaspinho/rtl8821ce#207]
I got an error message on install with ./dkms-install.sh

error got back: Error on install, /bin/sh: 1: bc: not found

How can I resolve this problem?

kernel is 5.9.*

Os: Kali

**Comment by SatanicRaw** [comment]
Install bc

**Comment by redscience** [comment]
Got it but How can I install it when my wifi is not run?

**Comment by tomaspinho** [comment]
Connect your computer to the internet via an Ethernet cable or download all Deb packages listed in the Ubuntu requirements in the README and install them via a usb drive.
