### ISSUE TITLE
Bluetooth not working in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by abhishekshree** [tomaspinho/rtl8821ce#208]
I tried every possible way to make the bluetooth driver work but it seem to fail all the time. I need to attend zoom session a lot these days so this is really becoming a major concern for me these days.

Some results from my terminal:
~ lsusb
`Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 04f3:0c00 Elan Microelectronics Corp. ELAN:ARM-M4
Bus 001 Device 002: ID 13d3:56c9 IMC Networks HP TrueVision HD Camera
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
`
<hr>

~ lsmod | grep blue
`bluetooth             577536  8 btrtl,bnep
ecdh_generic           16384  1 bluetooth
`
<hr>
~ systemctl status bluetooth

● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-02-09 01:56:41 IST; 14min ago
       Docs: man:bluetoothd(8)
   Main PID: 3588 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 18911)
     Memory: 2.0M
     CGroup: /system.slice/bluetooth.service
             └─3588 /usr/lib/bluetooth/bluetoothd

Feb 09 01:56:41 caesar systemd[1]: Starting Bluetooth service...
Feb 09 01:56:41 caesar bluetoothd[3588]: Bluetooth daemon 5.53
Feb 09 01:56:41 caesar systemd[1]: Started Bluetooth service.
Feb 09 01:56:41 caesar bluetoothd[3588]: Starting SDP server
Feb 09 01:56:41 caesar bluetoothd[3588]: Bluetooth management interface 1.17 initialized

<hr>

~ rfkill list all 
`
0: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
`

It'd be really appreciated if anyone helps me out here.

**Comment by Zaryob** [comment]
I dont know why but there is problem using both card. I use Fedora rhel debian and ubuntu with different computers and they have rtl8821ce. Only Ubuntu ı cannot use bluetooth when I modprobed 8821ce module.

**Comment by abhishekshree** [comment]
You're saying nothing can be done about it @Zaryob ?

**Comment by Zaryob** [comment]
probably about ubuntu kernel. Try another kernel module for ubuntu (mainline or lts kernel provided by ppa repository of kernel group.)

[More about Ubuntu kernels:](https://ubuntu.com/kernel)

**Comment by CITIZENDOT** [comment]
Did you make it work @abhishekshree ? I have the same issue. Kernel Version 5.5.17-1. Debian based System.

**Comment by abhishekshree** [comment]
No @CITIZENDOT It is a really weird bug.

**Comment by kascesar** [comment]
My bluetooth stop working, lenovo ideapad 330s

**Comment by kascesar** [comment]
> probably about ubuntu kernel. Try another kernel module for ubuntu (mainline or lts kernel provided by ppa repository of kernel group.)
> 
> [More about Ubuntu kernels:](https://ubuntu.com/kernel)

Hi, how do this ?

**Comment by abhishekshree** [comment]
Closing this issue as apparently it can't be fixed just yet.

**Comment by kascesar** [comment]
works well with 5.8.0-53-generic kernel version
