### ISSUE TITLE
Cannot modprobe 8821ce on fedora 34 and 35

### ISSUE THREAD

**Issue by ScardracS** [tomaspinho/rtl8821ce#212]
Running sudo modprobe 8821ce actually give me only one error.

`modprobe: ERROR: could not insert 8821ce: Permission denied`.

I have installed dkms, bc, kernel-headers and kernel-devel but nothing. The kernel is the 5.11 and I have blacklisted both rtw88_*etc* modules

**Comment by ScardracS** [comment]
With same kernel on other OSes this module works normally

**Comment by ScardracS** [comment]
Also secure boot is disabled

**Comment by Zaryob** [comment]
Im using Fedora Rawhide as well. There is not problem on module loading

Are you take root permissions for modprobe (with sudo command or going to root account)

**Comment by ScardracS** [comment]
> Im using Fedora Rawhide as well. There is not problem on module loading
> 
> Are you take root permissions for modprobe (with sudo command or going to root account)

Obviously...

**Comment by tomaspinho** [comment]
Was the module built for the correct kernel version? can you check your `/usr/lib/modules/$(uname -r)` and see if the compiled module is in there? or just run `dkms status`

**Comment by ScardracS** [comment]
I think I can close the issue because I have changed the OS. If I will try again fedora I will post further infos
