### ISSUE TITLE
[QUESTION] GnomeOS

### ISSUE THREAD

**Issue by ScardracS** [tomaspinho/rtl8821ce#213]
I have tried GnomeOS on my HP 15s and, as expected, WiFi doesn't work.

The problem comes when I asked devs for DKMS: they said DKMS probably will not be avaiable for GnomeOS so no RTL8821CE.

Do you know any other way to install it without DKMS?

**Comment by tomaspinho** [comment]
You may try building the model in-tree, if you know how to do that. Otherwise, GnomeOS falls out of support scope because of https://github.com/tomaspinho/rtl8821ce#intent

**Comment by ScardracS** [comment]
What you mean about in-tree? 😅

**Comment by tomaspinho** [comment]
You need to cp this repository inside the kernel tree, in the appropriate directory, and recompile the kernel with this module in it.
