### ISSUE TITLE
Support for Fedora 34 architecture x86_64

### ISSUE THREAD

**Issue by realgrm** [tomaspinho/rtl8821ce#215]
This is just a request for supporting architecture x86_64 on Fedora 34

![image](https://user-images.githubusercontent.com/23300290/109427912-481f4000-79d3-11eb-89bd-0a37066a9a22.png)

Thanks for the amazing work. If it wasn't for it, I probably wouldn't have a working wi-fi on my notebook.

**Comment by tomaspinho** [comment]
Looks like you're in the wrong place, we don't maintain Fedora packages here :)

@sergiomb2 is probably your best bet.

**Comment by sergiomb2** [comment]
Hello,
Fixed.

Sorry @tomaspinho, I didn't create a github repository of "my" akmods because I thought this akmod would be temporary , the user indeed followed the correct link :smile:
