### ISSUE TITLE
wifi not working after windows realtek driver update [dual boot ubuntu/windows]

### ISSUE THREAD

**Issue by anya-x** [tomaspinho/rtl8821ce#216]
Hello,
I am using ubuntu 20.04 LTS with a dual boot windows 10. I updated my wifi driver today and when I boot linux my wifi doesn't work. I have tried uninstalling and reinstalling the driver, it didn't work. Is anyone else experiencing this issue?

Thank you,

**Comment by tomaspinho** [comment]
Try completely powering off your computer and leaving it off for at least 10 seconds before booting Linux. This causes firmware clearance on the WiFi chip which should be causing your issue. There's nothing that can be done about this for the time being.

**Comment by anya-x** [comment]
Oh, I came back to it, and now it works. As you said, I think the WiFi chip was the problem.  Thank you for the help!
