### ISSUE TITLE
Error for kernel 4.15.0-45-generic (v5.2.5_23431.20170824).

### ISSUE THREAD

**Issue by sshahbaj** [tomaspinho/rtl8821ce#22]
I have followed the steps mentioned [here](https://askubuntu.com/questions/1071299/how-to-install-wi-fi-driver-for-realtek-rtl8821ce-on-ubuntu-18-04).

And after executing the last command i am presented with this [message](http://dpaste.com/3P565DC)

After restarting the wifi was not functional. I removed the installation using `sudo ./dkms-remove.sh` and tried reinstalling it using `--force` flag, but it still didn't work.

Please let me know it there is any additional information needed about my system.

**Comment by sergeibux** [comment]
Hi,
I have the same kernel and it's working fine for me.
Just make sure to have all the dependencies.
If you want, you can go to my Github and use this repository to autoinstall all of them.
You just have to run the file by this line.
` sudo ./install-rtl8821ce.sh`
I give you my repository with this file : [https://github.com/sergeibux/Install-rtl8821ce-driver](url)

**Comment by tomaspinho** [comment]
@sergeibux I've added the dependency installation commands to the README. Thank you.

@sshahbaj Try the following:

```
sudo dkms remove rtl8821ce/v5.2.5_23431.20170824 -k 4.15.0-45-generic
sudo dkms uninstall rtl8821ce/v5.2.5_23431.20170824
```
Reboot.

Your system should now be clean of any dkms installation of this driver. Install again with the instructions in the README.md.
