### ISSUE TITLE
Errors when reconnecting WiFi

### ISSUE THREAD

**Issue by CommanderRedYT** [tomaspinho/rtl8821ce#220]
System: AMD Laptop (Ubuntu 20.04 LTS), could also be on other Systems

Bluetooth works perfectly fine, but WiFi has some problems for me...

I can perfectly scan for WiFis and connect to it. But if I already was connected to a network (so switching from one network to another), the "Please enter the password again" (so false password)-Dialog shows up. But if I reboot my machine, I can connect to the WiFi.

Summary: I can only connect to a wifi after (re)booting, but cannot switch wifis

**Comment by micwoj92** [comment]
I'm only having such issues on eduroam networks. Home networks, smartphone hotspot work without issue. Maybe connection manager issue? I am using connman 1.39.

**Comment by CommanderRedYT** [comment]
I tried it with nmcli and the cinnamon network manager... Also, sometimes it asks for a password even if it is successfully connected..

**Comment by geekdiop** [comment]
Hello, can you run this command please : "  journalctl -au NetworkManager --follow ", and show us the logs ?

**Comment by kelebek333** [comment]
You can try to run following commands for disabling network manager's power management.

`echo -e '[connection]\nwifi.powersave = 2' | sudo tee /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf`

`sudo systemctl restart NetworkManager`

**Comment by CommanderRedYT** [comment]
Finally fixed it. Apparently the kernel modules from older kernels where installed but never deleted, so about 8 of them (ubuntu 20.04 & 21.04, also different "subversions") were loaded at the same time causing issues. 
Fix was to delete all of the kernel modules (rtl8821ce) and reinstall the dkms package.
