### ISSUE TITLE
It's incompatible with my router.

### ISSUE THREAD

**Issue by Zel9278** [tomaspinho/rtl8821ce#221]
My router is using E-WMTA2.4, but if I leave it unattended, it suddenly loses connection and I have to reboot the router to get connected.
My OS is kubuntu 20.04 and I am using the apt package of rtl8821ce-dkms.

**Comment by tomaspinho** [comment]
If you're using the apt package then you're not using this repository, I suggest you report that issue on the Ubuntu bug trackers 🙂
