### ISSUE TITLE
Again Wifi not found after update

### ISSUE THREAD

**Issue by RaghuManickam** [tomaspinho/rtl8821ce#222]
Hi

Was working correctly after installation of your driver .

but after latest update the wifi stopped working.

device : Tenda (W311MI) ubuntu : 20.04 kernal version : 5.4.0-72-generic

**Comment by sohaieb** [comment]
Hello, 

to be honest i'm not sure if this can help ,

but just try it and give me a feedback .. 

I tried it after my last update and it worked for me but not sure for other disturs .

[Link To My suggestion](https://github.com/tomaspinho/rtl8821ce/issues/205#issuecomment-774239769)

**Comment by RaghuManickam** [comment]
Hi ,

I tried with rtl8188gu driver . It worked for me . 

Any way thanks for the support!

**Comment by sohaieb** [comment]
> Hi ,
> 
> I tried with rtl8188gu driver . It worked for me .
> 
> Any way thanks for the support!

you are welcome :)
