### ISSUE TITLE
build not work on fedora 33(karnel 5.8.15-301.fc33.x86_64)

### ISSUE THREAD

**Issue by Zel9278** [tomaspinho/rtl8821ce#223]
I've installed the relevant ones, but no luck.
```
[ced@localhost rtl8821ce]$ sudo ./dkms-install.sh
About to run dkms install steps...

Creating symlink /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/source ->
                 /usr/src/rtl8821ce-v5.5.2_34066.20200325

DKMS: add completed.
Error! echo
Your kernel headers for kernel 5.8.15-301.fc33.x86_64 cannot be found at
/lib/modules/5.8.15-301.fc33.x86_64/build or /lib/modules/5.8.15-301.fc33.x86_64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Error! echo
Your kernel headers for kernel 5.8.15-301.fc33.x86_64 cannot be found at
/lib/modules/5.8.15-301.fc33.x86_64/build or /lib/modules/5.8.15-301.fc33.x86_64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Finished running dkms install steps.
```

I also had this error with other archlinux-based os.

**Comment by tomaspinho** [comment]
Did you install the kernel headers?

**Comment by Zel9278** [comment]
yes

**Comment by tomaspinho** [comment]
Can you check their actual path in `/lib/modules`?

**Comment by Zel9278** [comment]
> Can you check their actual path in `/lib/modules`?

this
![Uploading Screenshot from 2021-04-20 13-09-30.png…]()

**Comment by tduck973564** [comment]
My friend had this problem, before doing this run `./dkms-remove.sh`. My solution was `sudo dnf install kernel-devel-$(uname -r) && sudo rm -r /lib/modules/$(uname -r)/build && sudo ln -s /usr/src/kernels/$(uname -r) /lib/modules/$(uname -r)/build`. This installs the correct kernel headers for the kernel version you are on, then reinstates the broken symlink to point to the newly-installed headers.

**Comment by tduck973564** [comment]
A better solution would be to update the whole system and then build again, because I see that you have a slightly older kernel, indicative of a fresh install.

**Comment by Zel9278** [comment]
> A better solution would be to update the whole system and then build again, because I see that you have a slightly older kernel, indicative of a fresh install.

thanks! it's working
