### ISSUE TITLE
Seeking REALTEK 8814AU WIFI DRIVER for RHEL/CENTOS LINUX 8.x Kernel 4.18

### ISSUE THREAD

**Issue by jtome7** [tomaspinho/rtl8821ce#225]
Seeking REALTEK 8814AU WIFI DRIVER for RHEL/CENTOS LINUX 8.x Kernel 4.18 in case anybody might be working on this code.  THANKS!

**Comment by tomaspinho** [comment]
https://github.com/morrownr/8814au looks like your best bet.
