### ISSUE TITLE
My card is supported by Linux 5.12 but native driver crashes.

### ISSUE THREAD

**Issue by Spixmaster** [tomaspinho/rtl8821ce#227]
First of all, I do not need this driver anymore. My WLAN card seems to be supported by Linux kernel 5.12. I do not know anything about RFE which is mentioned regularly with this driver. I can just tell you that the driver for me is provided natively by the kernel.

Although, it connects it causes crashes after that. Sometimes immediately and the other times after a few minutes. The errors are solved if I turn off the wireless connection. By crash, I mean that the whole system just freezes and does not react anymore.

Unfortunately, I need to use LAN for some time. I hope that this will be fixed soon. Another solution is to [blacklist the kernel provided driver](https://github.com/tomaspinho/rtl8821ce#wi-fi-not-working-for-kernel--59).

**Comment by micwoj92** [comment]
Saw you comment on aur page too, do you know how to find out this RFE number? For me only network "crashes", the rest of system is fine but have to reconnect.

**Comment by Spixmaster** [comment]
@micwoj92 I do not know how to find it out. I do not even know what it means. Here is the output of `lspci -k`. I do not see that number there but maybe someone else has an idea.
```
02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
        DeviceName: WLAN
        Subsystem: Hewlett-Packard Company Device 831a
        Kernel driver in use: rtw_8821ce
        Kernel modules: rtw88_8821ce
```

**Comment by unbranched** [comment]
@Spixmaster @micwoj92 
`sudo dmesg|grep rfe`

**Comment by micwoj92** [comment]
It doesn't show anything for me?

**Comment by Spixmaster** [comment]
`dmesg` puts out the kernel's ring buffer whatever that means. It does not show anything for me too which may be caused by the situation that I am currently not able to use WLAN and instead use LAN.

**Comment by unbranched** [comment]
It doesn't show anything because you have no errors. If you're using a kernel <5.12 you should see a message like "rfe N is not supported".

**Comment by micwoj92** [comment]
Right now I am using Linux lts 5.10.34 because of these network issues, do I have to uninstall this driver in order to see that message?

**Comment by Spixmaster** [comment]
I switched to Linux LTS too but not for too long. I think that this driver did not work as it compiles with the package "linux-headers" from the Arch repositories which has version 5.12.1.
From what I understand, use the native driver with Linux LTS v5.10.34 and the error message should appear.

If you want to solve the WLAN card driver issues just install this driver and perhaps [blacklist the kernel provided driver](https://github.com/tomaspinho/rtl8821ce#wi-fi-not-working-for-kernel--59).

**Comment by micwoj92** [comment]
For LTS you need linux-lts-headers and it will work

**Comment by Spixmaster** [comment]
I did not know about this package. My problem with that is that "linux-headers" will be installed as the dependency either way.

**Comment by micwoj92** [comment]
Oh, then you should report it, I see that @tomaspinho is also maintainer. This is not needed and common packaging error, DKMS package already has these headers in optdepends. If it won't be resolved then you can fill orphan request take over the package and fix. I never noticed this because I have 2 kernels installed almost all the time.

**Comment by tomaspinho** [comment]
If you're not running the mainline Arch kernel, why not just install from this repository following instructions? Should assume your LTS  kernel headers correctly

**Comment by alium** [comment]
> Subsystem: Hewlett-Packard Company Device 831a

that is probably RFE2 , same as my (my lspci show the same entry).
If you install linux-lts, you need modify in PKGBUILD to makedepends=('git' 'bc' 'linux-lts-headers').
rtw88_8821ce must be blacklisted.

as i wrote in another topic, native driver for RFE2 in kernel  is not good. I have big problems too. The only driver that works for me without problems is 8821ce.


> First of all, I do not need this driver anymore

you should maybe rather open bug in bugzilla.kernel.org for crashing native driver ;)

**Comment by neutr0nStar** [comment]
Please can you also check if the Bluetooth is working or not ?
