### ISSUE TITLE
How good is the built-in kernel module for rtl8821ce in kernel 5.12

### ISSUE THREAD

**Issue by neutr0nStar** [tomaspinho/rtl8821ce#228]
I had installed ubuntu, running kernel 5.8, but had to switch back to windows because of multiple issues I faced ( like sound card, WIFI, Bluetooth, etc.). But recently I heard that rtl8821ce will be natively supported in Linux kernel 5.12, but currently, no distro ships with it out of the box. So, for those who went the extra mile to try it out, how was it, is it good, or is this driver made by @tomaspinho the best option available ? 

My laptop is HP-14s, Ryzen 5 3450u, it was launched on October 2020, so it's relatively new, I don't even know which RFE version the chip is. But if someone has something to share, Please do so. 

Thankyou @tomaspinho and other developers who made this awesome driver. ;-)

**Comment by tomaspinho** [comment]
All the information about the status of rtw88 (the built-in kernel module) can be found in this issue: https://github.com/tomaspinho/rtl8821ce/issues/142
