### ISSUE TITLE
Error! Bad return status for module build on kernel: 5.12.3-1-default (x86_64)

### ISSUE THREAD

**Issue by x3F-x3F** [tomaspinho/rtl8821ce#229]
Hello!

Running "sudo ./dkms-install.sh" returns:
  Error! Bad return status for module build on kernel: 5.12.3-1-default (x86_64)
  Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/make.log for more information.

[return-full](https://pastebin.com/MXkYT9Py)
[inxi -Fxxxza](https://pastebin.com/kHGS5AQz)
[make.log](https://pastebin.com/mvzHb2Hk)

The installer worked for kernel 5.3. Then we changed from Leap to Tumbleweed and the Installer no longer works. 
I have followed and installed everything based off of readme.md.
I'm guessing I'm missing some pkg, that's expected, but got removed with the upgrade.

Thank you(=

**Comment by dexter2000** [comment]
I've just hit this in Fedora as they have just switched to 5.12.5 in F34.
I found a fix & explanation here: 
https://github.com/cilynx/rtl88x2bu/commit/8316868608bd0fc3de48dd7d5d7ebe4648f5a181

**Comment by x3F-x3F** [comment]
Yep, that seems to be the fix.
Commit: cac892e7db2700b367c981445263c185867247f3

**Comment by sys-adminpt** [comment]
Still having problems with 5.12.5-200 and 5.12.6-200 on fedora 33...

**Comment by sys-adminpt** [comment]
ok... just did a git pull and dkms-install.sh and it's working again...
