### ISSUE TITLE
bluetooth not working after suspend

### ISSUE THREAD

**Issue by brainchild0** [tomaspinho/rtl8821ce#230]
I have installed from 897e7c4, the latest commit in the main branch.

Bluetooth works up until the system suspends, afterward not until reboot.

I am running kernel 5.8.0-53, built for Ubuntu, running Mint 20.1 on a HP dy1 laptop.

**Comment by tomaspinho** [comment]
Yeah, we are aware. And this is documented in the Readme.

**Comment by brainchild0** [comment]
Sorry. I suppose I read it at one point but somehow forgot that the issue   was documented here, and didn't look again before posting. For reference, are you aware of any sources that explain the general issue?

**Comment by stiltgit** [comment]
Hi, I just wanted to report that the problem vanished away for me with Ubuntu 20.04 Kernel 5.4.0-91-generic and rtl8821ce-dkms 5.5.2.1-0ubuntu4~20.04.4
