### ISSUE TITLE
Gentoo Overlay: there are no ebuilds to satisfy "dev-util/dwarves"

### ISSUE THREAD

**Issue by WarwickNew** [tomaspinho/rtl8821ce#233]
Hey,

I'm trying to install the driver on my Gentoo laptop via your overlay but I keep getting the following error:

`emerge: there are no ebuilds to satisfy "dev-util/dwarves".
(dependency required by "net-wireless/rtl8821ce-driver-5.5.2_p20210321::trolltoo" [ebuild])
(dependency required by "net-wireless/rtl8821ce-driver" [argument])
`

It appears that the package doesn't exist anymore with the Gentoo page detailing it, now leading to a 404 error. [https://packages.gentoo.org/packages/dev-util/dwarves/dependencies](https://packages.gentoo.org/packages/dev-util/dwarves/dependencies)

I'm not too clear on what this package does having not worked in the world of drivers, nor messing about with binary formats? so I can't think of a way to fix the package myself.

**Comment by micwoj92** [comment]
It should work if you replace it with https://packages.gentoo.org/packages/dev-util/pahole
