### ISSUE TITLE
firmware failed to leave lps state

### ISSUE THREAD

**Issue by whizsid** [tomaspinho/rtl8821ce#234]
I found these entries in my journalctl

```
sudo journalctl -b -1 -r
```

```
Jul 17 12:29:06 archlinux wpa_supplicant[442]: wlo1: CTRL-EVENT-BEACON-LOSS
Jul 17 12:29:05 archlinux wpa_supplicant[442]: wlo1: CTRL-EVENT-BEACON-LOSS
Jul 17 12:29:04 archlinux wpa_supplicant[442]: wlo1: CTRL-EVENT-BEACON-LOSS
Jul 17 12:29:03 archlinux wpa_supplicant[442]: wlo1: CTRL-EVENT-BEACON-LOSS
Jul 17 12:29:02 archlinux wpa_supplicant[442]: wlo1: CTRL-EVENT-BEACON-LOSS
Jul 17 12:28:51 archlinux kernel: rtw_8821ce 0000:02:00.0: firmware failed to leave lps state
Jul 17 12:28:44 archlinux wpa_supplicant[442]: wlo1: CTRL-EVENT-BEACON-LOSS
Jul 17 12:28:43 archlinux kernel: rtw_8821ce 0000:02:00.0: firmware failed to leave lps state
Jul 17 12:28:34 archlinux wpa_supplicant[442]: wlo1: CTRL-EVENT-BEACON-LOSS
```

**Comment by kelebek333** [comment]
> ```
> Jul 17 12:28:51 archlinux kernel: rtw_8821ce 0000:02:00.0: firmware failed to leave lps state
> ```

Output is not related this repo. You can feedback to that repo. https://github.com/lwfinger/rtw88

If you have installed rtl8821ce driver from this repo, you should blacklist the rtw_8821ce and rtw88_8821ce modules.

**Comment by whizsid** [comment]
@kelebek333 Thank you for the suggestion. I accidentally installed the both modules and it caused to frequently freezing the kernel. I solved it by blacklisting the previous modules as in the above comment.
