### ISSUE TITLE
unstable wifi connection in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by mororo18** [tomaspinho/rtl8821ce#237]
Recently I have been having problems with my WiFi connection stability 

output of `dmesg -w`
[ 7575.241517] rtw_8821ce 0000:02:00.0: sta 24:fd:0d:21:1b:33 with macid 0 left                                                                                   
[ 7579.750265] wlo1: authenticate with 24:fd:0d:21:1b:33                                                                                                          
[ 7580.405208] wlo1: send auth to 24:fd:0d:21:1b:33 (try 1/3)                                                                                                     
[ 7580.418438] wlo1: authenticated                                                                                                                                
[ 7580.421086] wlo1: associate with 24:fd:0d:21:1b:33 (try 1/3)                                                                                                   
[ 7580.438045] wlo1: RX AssocResp from 24:fd:0d:21:1b:33 (capab=0x411 status=0 aid=5)                                                                             
[ 7580.438101] rtw_8821ce 0000:02:00.0: sta 24:fd:0d:21:1b:33 joined with macid 0                                                                                 
[ 7580.438425] wlo1: associated                                                                                                                                   
[ 7581.472246] perf: interrupt took too long (3242 > 3227), lowering kernel.perf_event_max_sample_rate to 61500                                                   
[ 7618.046645] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7698.144522] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7698.292573] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7698.772504] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7698.912570] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7699.368510] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7702.036377] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7702.184370] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7704.044383] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7704.188283] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7705.348267] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7705.500248] rtw_8821ce 0000:02:00.0: timed out to flush queue 1                                                                                                
[ 7705.960338] rtw_8821ce 0000:02:00.0: timed out to flush queue 1
[ 7706.104279] rtw_8821ce 0000:02:00.0: timed out to flush queue 1
[ 7706.560219] rtw_8821ce 0000:02:00.0: timed out to flush queue 1
[ 7707.488234] rtw_8821ce 0000:02:00.0: timed out to flush queue 1

**Comment by kelebek333** [comment]
rtw_8821ce module s not related driverin this repository. If you install rtl8821ce dtiver, you must add rtw_8821ce module to blacklist. https://github.com/tomaspinho/rtl8821ce#wi-fi-not-working-for-kernel--59

**Comment by mororo18** [comment]
yeah, apparently worked for me. I hadn't tried this one yet. Thank you!
