### ISSUE TITLE
Crash after sleep mode

### ISSUE THREAD

**Issue by hashlib** [tomaspinho/rtl8821ce#24]
Wi-Fi crashes after any second-third sleep mode.

dmesg says: 
`[ 8573.082645] rtl8821ce 0000:01:00.0: Event logged [IO_PAGE_FAULT domain=0x0000 address=0xff5ab830 flags=0x0000]`

I'm on 5.0.0 kernel right now, but this issue was on 4.15, 4.18 and 4.19 too.

**Comment by JussiVJ** [comment]
I'm have the same problem and the same dmesg output.

**Comment by tomaspinho** [comment]
As described in https://github.com/tomaspinho/rtl8821ce#disclaimer no further module development will be carried out here. Not having proper sleep management with this module is a known issue and I'm afraid you're out of luck.

**Comment by 9Lukas5** [comment]
I don't want to complain that no development will happen, but don't you think it would be a good idea to keep the issues present open, so that other people don't open new issues but instead see that it's known?^^

**Comment by DimitrisKatsiros** [comment]
## I have a **temporary** solution that worked for me.
This requires removing and inserting the module.

After executing make, copy the _8821ce.ko_ file to a folder of your choice and open a terminal in that folder.

Create a script:
```
vim rebootingWifiAdapter.sh
```

Then paste the following code, defining the _/path/to/folder_ and save the file(_esc and wq_):
```#!/bin/bash
PATH_TO_MODULE='/path/to/folder'  
cd $PATH_TO_MODULE  
rmmod 8821ce  
insmod 8821ce.ko
```

Edit file permissions:
```
chmod 755 rebootingWifiAdapter.sh
```

Copy the file to /etc/pm/sleep.d:
```
sudo cp ./rebootingWifiAdapter.sh /etc/pm/sleep.d/
```

Suspend to test.

**Comment by agguser** [comment]
Seems that just manually run
```
sudo modprobe -r 8821ce; sudo modeprobe 8821ce
```
also works.
