### ISSUE TITLE
Wifi working but not bluetooth on Debian 11

### ISSUE THREAD

**Issue by adolfo-roman** [tomaspinho/rtl8821ce#242]
Hello!

I'm new to Linux, and decided to install Debian 11... I had no problems at all with the installation except for the rtl821ce my computer has. Thanks to this repo I was able to get my wifi running, but so far I have not had any luck with the bluetooth. 

I'm on an HP 15-dw0043dx, I already installed the realtek-firmware package from the Debian website, reset and nothing happened. 

Also i did  "dmesg | grep -i bluetooth" but i'm getting "dmesg: read kernel buffer failed: Operation not permitted" back. I also tried with sudo before the command but no returns after that.

When I press super key and try to look for "bluetooth" I'm not getting any results, so I'm not really sure where can I see a configuration window for my bluetooth or idk since I'm a newbie to this systems.

Any ideas? Thanks!

**Comment by kelebek333** [comment]
Post outputs of following commands.

```
sudo dmesg | egrep -i "blue|firm"
lsusb -tv
rfkill list
```

> dmesg: read kernel buffer failed: Operation not permitted

Tip: Run following commands for dmesg outputs without sudo.

```
sudo mkdir -p /etc/sysctl.d ; sudo touch /etc/sysctl.d/90-dmesg.conf
echo 'kernel.dmesg_restrict = 0' | sudo tee /etc/sysctl.d/90-dmesg.conf
sudo sysctl --system
```
