### ISSUE TITLE
error loading driver 8821ce

### ISSUE THREAD

**Issue by Cris-lml007** [tomaspinho/rtl8821ce#243]
Hello, I am having problems loading the driver for my network card, I already installed the driver from this repository and sending the command lspci -v I got the driver rtw88_8821ce, 8821ce which I suppose that the second is the one that should be loaded and not the first one but when sending the sudo modprobe 8821ce and restarting, no change appears and the whole system freezes and it only remains to restart, I use kali linux

**Comment by dubhater** [comment]
You need to create the file ``/etc/modprobe.d/no-rtw88.conf`` with this line in it:
```
blacklist rtw88_8821ce
```
and reboot. Then the module 8821ce from this repository will be automatically loaded.

**Comment by Cris-lml007** [comment]
In the end, if I manage to get the wifi on, some moments it is somewhat unstable but functional.
