### ISSUE TITLE
Missing 4.14.255-1-MANJARO kernel modules tree for module

### ISSUE THREAD

**Issue by Drarig29** [tomaspinho/rtl8821ce#246]
When I install the AUR package `rtl8821ce-dkms-git`, I get this error:

```
:: Running pre-transaction hooks...
(1/1) Remove upgraded DKMS modules
==> dkms remove --no-depmod rtl8821ce/1.0.5.r130.gca204c6 -k 5.15.2-2-MANJARO
:: Processing package changes...
(1/1) reinstalling rtl8821ce-dkms-git                           [##################################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Install DKMS modules
==> dkms install --no-depmod rtl8821ce/1.0.5.r130.gca204c6 -k 5.15.2-2-MANJARO
==> depmod 5.15.2-2-MANJARO
==> ERROR: Missing 4.14.255-1-MANJARO kernel modules tree for module rtl8821ce/1.0.5.r130.gca204c6.
(3/3) Refreshing PackageKit...
```

I just installed the new 5.15 kernel. I don't know why the error talks about "4.14.255-1-MANJARO".

And I don't know how to check if the driver was installed or not.

I'd be glad to get some help because I really need this driver to get a stable connection.

**Comment by Drarig29** [comment]
Okay, I was indeed running the 5.15 kernel but I still had the package `linux414-headers`. So I think it was trying to use these headers but couldn't find the actual 4.14 kernel.

I removed `linux414-headers` and it works.

**Comment by OyewoleOyedeji** [comment]
@Drarig29 worked for me too, thanks
