### ISSUE TITLE
How would I even install this?

### ISSUE THREAD

**Issue by friendlymaninthisworld** [tomaspinho/rtl8821ce#247]
So a few days ago I tried to install Ubuntu, however I faced a problem with Realtek Wi-Fi driver. Well now the only option is to install it, but I can't install the necessary tools to build it without Wi-Fi. So, how am I supposed to make and install it without make and dkms?

**Comment by 1-minute-to-midnight** [comment]
Ethernet or USB tethering on android phone to your PC

**Comment by friendlymaninthisworld** [comment]
I mean, I bet that could work, but do you think these options could also work? :
- Downloading all the .deb files for make and dkms to a USB from another computer and installing them on host computer.
I think there are too many packages for this one to be possible.
or
- using a semi-sketchy USB Wi-Fi adapter to install dependencies.
I'm not too sure if there are drivers for the Wi-Fi adapter.

Also, linking a tutorial on how to properly tether an android to Ubuntu would be greatly appreciated.

Thanks :)

**Comment by 1-minute-to-midnight** [comment]
I wouldn't recommend the first option. As for the second one, plug the WiFi adapter and check if it works.....it all depends on the WiFi card within it. For android tethering, go to settings>WiFi and Network>Hotspot and Tethering. Then connect your phone cable to your PC and toggle the USB Tethering option. I am currently using android 9....so depending on your version it may vary. Just use the search function in your settings if you can't find it.

**Comment by friendlymaninthisworld** [comment]
Wow, the second option worked like a charm!
Thanks for all the help.
