### ISSUE TITLE
Wi-Fi stopped working after upgrading kernel to 5.15.x in Lenovo Ideapad 330 15ARR

### ISSUE THREAD

**Issue by Ldev007** [tomaspinho/rtl8821ce#249]
Hello guys, I am opening (as well as requesting @tomaspinho  to close it at the same time) this issue only for the sake of other lenovo ideapad 330 15ARR users as evident from the title. It may or may not help other users too.

As many people might be unaware @tomaspinho the star dev has already pushed a commit which attempts to fix the wifi issue for kernel versions > 5.15.x hence to fix the issue being faced by us we must update the driver to latest version by following the tutorial given in readme file.

Once we've updated the driver next step is to reboot the system and that should be enough !

@tomaspinho thanks again for fixing it !

**Comment by tgarder** [comment]
Can confirm the same happened for me on my Lenovo Legion machine, could tether my phone's usb connection though and then:

```
git pull
make clean
sudo ./dkms-install.sh

```
...and then powered off (waited for a few seconds, don't know if that actually made the trick but the first time when I just restarted the problem persisted) and it worked again.

**Comment by Ldev007** [comment]
@tgarder that's weird it should've worked within first attempt maybe cleanup wasn't done properly for old files in first run. As the update is omitting the use of an header file which conflicts during driver's building process and so that should go fine within first attempt anyways kudos to you for getting your WiFi working back again ! These kinda issues makes using linux a bit unsafe (in case if it is the laptop/PC which we are using for work) but interesting and fun at the same time for this cost we get the security and freedom as benefits.
