### ISSUE TITLE
Use repo or patcher for building rtl8821ae

### ISSUE THREAD

**Issue by zlocate** [tomaspinho/rtl8821ce#254]
Greetings.
Please tell me if I can use this repository to build a module for rtl8821ae or at least export the patches that are applied in it.

If yes, where should I start?
Thank you in advance.
I found the repository https://github.com/rapyuta-robotics/rtl8821ae-dkms/ but unfortunately the driver is not built in it on kernels after 5.9.
I'm port this repo patches (set_fs / sed_ds)  but haven't had success yet.

**Comment by SatanicRaw** [comment]
Hello. Since the repository is already ~1.5 years old, other things have changed in this time, except for set_fs / sed_ds, it's probably worth looking at the commits from this repository, which relate to support for new kernels since 5.9.
