### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by Egyember** [tomaspinho/rtl8821ce#255]
The new Arch (01/01/2022) kernel crashes at random times when I use wifi.

**Comment by avevad** [comment]
@Egyember I had the same problem. It looks like the new built-in rtw88_8821ce driver causes the crash, not the rtl8821ce. Try creating `/etc/modprobe.d/rtw_blacklist.conf` with the following content:
```
blacklist rtw88_8821ce
```
And then reboot. Buggy rtw should now be off, and the rtl8821ce will be used instead, like it was before the update
