### ISSUE TITLE
question: merge in linux

### ISSUE THREAD

**Issue by obione-kenobi** [tomaspinho/rtl8821ce#256]
why didn't you merged in the kernel mainline?

**Comment by GunpowderGuy** [comment]
Realtek made their own linux driver but still think this one should be merged. Realtek's is buggy as hell and still makes some system crash

**Comment by crazyaccess** [comment]
+1 on the decission.

**Comment by heqro** [comment]
makes perfect sense. The driver currently sitting in the kernel makes my computer hard freeze.
