### ISSUE TITLE
Reinstall the driver doesn't work

### ISSUE THREAD

**Issue by Denis4l** [tomaspinho/rtl8821ce#259]
After updating to kernel  (on fedora) 5.15.18-100.fc34.x86-64

The procedure is simple, I did it already and it worked fine... but :

On notebook ASUS L410M with realtek 8821CE
removing with dkms-remove.sh is ok -> finished running dkms removal steps
Then make clean seems to be ok : deleting some *.ko files + module.markers and module.order.

And when I install with dkms-install.sh
Returns : Error DKMS tree already contains rtl8821ce-v5.5.2-34066.20200325
You cannot add the same module/version combo more than once.

Is this a problem due to dkms, the driver, myself ?

**Comment by kelebek333** [comment]
Try to run following commands.

```
sudo dkms remove rtl8821ce/v5.5.2-34066.20200325 --all
sudo rm -f /usr/src/rtl8821ce-v5.5.2-34066.20200325
```

Then you can re-try to install.

**Comment by Denis4l** [comment]
There something strange : if I try 
`sudo dkms remove rtl8821ce/v5.5.2-34066.20200325 --all`
The result is : `Error ! The module/version combo : rtl8821ce/v5.5.2-34066.20200325 is not located in the dkms tree.`
anyway, I had removed the files 'sudo rm -rf /usr/src/rtl8821ce-v5.5.2-34066.20200325'

Then, I get the same as before (cf. the file attahed) 
`
[dkms-install.txt](https://github.com/tomaspinho/rtl8821ce/files/8030802/dkms-install.txt)
`

I must have done something wrong somewhere removing properly the driver, but I did not do anything else than running the script dkms-remove.sh. By the way, with dkms, as far as I understand, I should not have to reinstall it while updating the kernel... right ? This is why I thought to annoy you with this problem as an «issue» but I do not know it it is an issue for you.

**Comment by kelebek333** [comment]
```
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/core/rtw_br_ext.c:20:18: erreur fatale: net/ipx.h : Aucun fichier ou dossier de ce type
   20 |         #include <net/ipx.h>
```

Source updated for Linux 5.15. https://github.com/tomaspinho/rtl8821ce/blob/master/core/rtw_br_ext.c#L20-L23

You can try to update build source, then re-try install.

**Comment by Denis4l** [comment]
Ok thinks a lot it works. So, the problem came form the fact that I did not use the last files integrating kernel 5.15 specifications, right ? Sorry for that.

However, I do  not understand a couple of things. For example, where are the files linux/version.h or net/ip.h ? Where can I learn how does these things works.

**Comment by kelebek333** [comment]
ipx support removed with kernel 5.15. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/net?id=6c9b40844751ea30c72f7a2f92f4d704bc6b2927
