### ISSUE TITLE
Does not compile on 5.18

### ISSUE THREAD

**Issue by minneelyyyy** [tomaspinho/rtl8821ce#272]
I cannot tell if this project is dead or not, but it will not compile on Linux 5.18...

[info.txt](https://github.com/tomaspinho/rtl8821ce/files/8767408/info.txt)

**Comment by minneelyyyy** [comment]
Sorry, I saw that support for 5.17 was added 2 months ago. I'm sure you guys are working on 5.18. :+1:

**Comment by goodmountain** [comment]
Hi,
I have a few more details, in case it helps to get this driver going again.
This is the make.log from my compile attempt with 5.18 kernel headers:
[make.log](https://github.com/tomaspinho/rtl8821ce/files/8791668/make.log)
(at least) two functions appear having changed with 5.18 kernel:
- pci_set_dma_mask()
- pci_set_consistent_dma_mask()

This was reported breaking NVIDIA and VMWare as well - VMWare got patched - check here:
http://rglinuxtech.com/?p=3015

Kind regards.

**Comment by Spixmaster** [comment]
I just tested Linux 5.18 and I can use the the driver "rtw88_8821ce" which is provided by Linux. I do not need this driver anymore.

**Comment by tomaspinho** [comment]
Fix for this is here: https://github.com/tomaspinho/rtl8821ce/pull/275
Can someone test and report back? Thanks

**Comment by leisiji** [comment]
I have tested #275, it can be compiled successfully and work well on Linux 5.18.
