### ISSUE TITLE
driver not compiling for kernel 5.18

### ISSUE THREAD

**Issue by adeldude13** [tomaspinho/rtl8821ce#274]
im not sure if its a kernel issue of i missed up but here is the make log that was generated by dkms install [here](https://pastebin.com/raw/hvLWhryk)

**Comment by Spixmaster** [comment]
Yes, compilation fails like mentioned in #272 .

**Comment by adeldude13** [comment]
oh sry i did not notice that somebody already opened the same issue before me

**Comment by tomaspinho** [comment]
Closing this as a duplicate.
