### ISSUE TITLE
Wifi not working after suspending the os

### ISSUE THREAD

**Issue by NastyGamer** [tomaspinho/rtl8821ce#28]
When suspending the os, the wifi doesn't work after any more.
Im using **Ubuntu 18.04**.

**Comment by hashlib** [comment]
I'm using
`sudo modprobe 8821ce -r`
`sudo modprobe 8821ce`
to reboot it. And it works correctly after that.

**Comment by NastyGamer** [comment]
> I'm using
> `sudo modprobe 8821ce -r`
> `sudo modprobe 8821ce`
> to reboot it. And it works correctly after that.

Thanks for the tip. It now works flawlessly

**Comment by NastyGamer** [comment]
> I'm using
> `sudo modprobe 8821ce -r`
> `sudo modprobe 8821ce`
> to reboot it. And it works correctly after that.

For some reason i don't have the modprobe 8821ce

**Comment by hashlib** [comment]
Why? If the driver is installed, it should work.

**Comment by NastyGamer** [comment]
I'm so stupid...
All that time I was looking for rtl8821ce, not 8821ce...
Of course it's there and it's working flawlessly.
Sorry for wasting your guy's time
