### ISSUE TITLE
dkms install fails with gcc 12.1.0-3

### ISSUE THREAD

**Issue by holyspiritomb** [tomaspinho/rtl8821ce#286]
> 
> `DKMS make.log for rtl8821ce-1.0.5.r140.gbe733dc for kernel 5.18.14-AMD (x86_64)
> Mon Jul 25 04:24:56 PM EDT 2022
> make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.18.14-AMD/build M=/var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build  modules
> make[1]: Entering directory '/usr/lib/modules/5.18.14-AMD/build'
>   CC [M]  /var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build/core/rtw_cmd.o
>   CC [M]  /var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build/core/rtw_security.o
>   CC [M]  /var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build/core/rtw_debug.o
>   CC [M]  /var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build/core/rtw_io.o
> cc1: error: incompatible gcc/plugin versions
> cc1: error: incompatible gcc/plugin versions
> cc1: error: failed to initialize plugin ./scripts/gcc-plugins/stackleak_plugin.so
> cc1: error: failed to initialize plugin ./scripts/gcc-plugins/stackleak_plugin.so
> make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build/core/rtw_cmd.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build/core/rtw_security.o] Error 1
> cc1: error: incompatible gcc/plugin versions
> cc1: error: failed to initialize plugin ./scripts/gcc-plugins/stackleak_plugin.so
> make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build/core/rtw_debug.o] Error 1
> cc1: error: incompatible gcc/plugin versions
> cc1: error: failed to initialize plugin ./scripts/gcc-plugins/stackleak_plugin.so
> make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build/core/rtw_io.o] Error 1
> make[1]: *** [Makefile:1838: /var/lib/dkms/rtl8821ce/1.0.5.r140.gbe733dc/build] Error 2
> make[1]: Leaving directory '/usr/lib/modules/5.18.14-AMD/build'
> make: *** [Makefile:2244: modules] Error 2
> `

I temporarily downgraded gcc and gcc-libs to 12.1.0-2 from my package cache. When I then ran `sudo pacman -U rtl8821ce-dkms-git-1.0.5.r140.gbe733dc-1-x86_64.pkg.tar.zst`, the dkms install was successful.

os: Arch
kernel: 5.18.14-AMD
dkms: 3.0.5-2
current gcc and gcc-libs: 12.1.0-3

**Comment by tomaspinho** [comment]
This is a problem with your gcc installation. unfortunately I can't help with this.
