### ISSUE TITLE
default log level

### ISSUE THREAD

**Issue by stas00** [tomaspinho/rtl8821ce#3]
May I suggest to modify Makefile to change the default log level from 4 (info) to 3 (warning)? Otherwise its default fills up GBs of useless noise in /var/log/syslog. See https://askubuntu.com/a/1067788/803807 . 

    - CONFIG_RTW_LOG_LEVEL = 4
    + CONFIG_RTW_LOG_LEVEL = 3

Thank you for providing this dkms build - it's super useful!!!

**Comment by tomaspinho** [comment]
You could have just opened a Pull request :stuck_out_tongue: 
I'll take care of it.

**Comment by stas00** [comment]
Oh, I wasn't sure whether it was right. Thank you for patching it, Tomas.
