### ISSUE TITLE
cant build module on linux version 6.0 testing arch

### ISSUE THREAD

**Issue by urparvezali** [tomaspinho/rtl8821ce#301]

**Comment by urparvezali** [comment]
same issue was at the linux version 5.19.2

**Comment by JaR0din** [comment]
What was the solution to fixing this issue? I am having a similar issue as well I noticed the gcc versions were different and it was acting like it. All the errors in my make.log were syntax. Indentations and the like

**Comment by dominix** [comment]
I don't know for @urparvezali  but on my side I have had troubles because the kernel modules was blacklisted because of my dkms package use. 
with the remove of the dkms package kernel module works well on pop! os 22.04 kerne 6.0.3
