### ISSUE TITLE
Ubuntu 22.10 - Doesn't recognize device

### ISSUE THREAD

**Issue by cryptogateway** [tomaspinho/rtl8821ce#306]
Hello!. I have a Wi-Fi USB adapter based on a Realtek RTL8811 chip, the drivers are compiled and installed, but this device is not detected, I tried it on Ubuntu 14/16 everything is fine there. Tell me, has anyone encountered this problem?

<a href="https://ibb.co/DVdjFd5"><img src="https://i.ibb.co/Vj6kG62/Screenshot-from-2022-11-19-17-11-20.png" alt="Screenshot-from-2022-11-19-17-11-20" border="0"></a>

<a href="https://ibb.co/qFmqN8m"><img src="https://i.ibb.co/1JRyrNR/Screenshot-from-2022-11-19-17-10-08.png" alt="Screenshot-from-2022-11-19-17-10-08" border="0"></a>

**Comment by dubhater** [comment]
rtl8821ce handles only PCI devices.

``dkms status`` only says "added", so I don't think rtl8821CU is compiled. Try ``dkms install rtl8821CU`` or something like that.

**Comment by cryptogateway** [comment]
Tried installing: sudo dkms install rtl8821ce/v5.5.2_34066.20200325

<a href="https://ibb.co/FDSgBWG"><img src="https://i.ibb.co/TgVmHTz/Screenshot-from-2022-11-19-19-23-52.png" alt="Screenshot-from-2022-11-19-19-23-52" border="0"></a>

**Comment by dubhater** [comment]
rtl8821ce is not going to help you. What you need is rtl8821CU.
