### ISSUE TITLE
Cannot install rtl8821ce driver on cachyos. Seems not works with 6.1 kernel version

### ISSUE THREAD

**Issue by Phiphever** [tomaspinho/rtl8821ce#307]
here the make.log
[make.log](https://github.com/tomaspinho/rtl8821ce/files/10221482/make.log)

**Comment by HanYangCoder** [comment]
I also have the same issue on OpenSUSE Tumbleweed version 20221222, I checked the make.log and we have similar logs as well. This was also on 6.1 so I reverted back to 6.0.12-1 for now which this driver works well.

Hope this would be an easy fix for the maintainers, please don't forget to enjoy the holidays as well! 😄 🎄

**Comment by TheCourierNV** [comment]
There's a pull request [here](https://github.com/tomaspinho/rtl8821ce/pull/308) that implements a fix for Linux 6.1.1; I have been using it for the past few days and it works.

You could have also found it by reading the comment feed [on the page for the AUR package](https://aur.archlinux.org/packages/rtl8821ce-dkms-git)

I hope I didn't come across rudely, I just want to let you know where you could have found relevant info about this :^P

**Comment by HanYangCoder** [comment]
Applied the pull request with the fix and it works like normal, thanks a lot sir! Hope I wouldn't forget to switch back when it's merged to this repo. I should've checked the pull requests too lol.

**Comment by tomaspinho** [comment]
MR for 6.1 has been merged.
