### ISSUE TITLE
driver doesn't load

### ISSUE THREAD

**Issue by CaneMandarinesco** [tomaspinho/rtl8821ce#310]
os: 6.1.1-arch1-1
laptop: hp-15seq0013nl

just installed driver following these steps: 
- installed the driver with aur
- blacklisted the old driver with /etc/modprobe.d/blacklist.conf
- run mkinitcpio
- reboot

but the new driver doesn't show up on lsmod and wlan0 interface is not loaded

hopefully the driver that comes with 6.1.1 works pretty much (but i had some issues with 5g wifi), but i would like to test this driver.

journalctl:
> Dec 22 17:42:54 davidelaptop systemd[1]: sys-subsystem-net-devices-wlan.device: Job sys-subsystem-net-devices-wlan.device/start timed out.
Dec 22 17:42:54 davidelaptop systemd[1]: Timed out waiting for device /sys/subsystem/net/devices/wlan.
Dec 22 17:42:54 davidelaptop systemd[1]: Dependency failed for dhcpcd on wlan.
Dec 22 17:42:54 davidelaptop systemd[1]: dhcpcd@wlan.service: Job dhcpcd@wlan.service/start failed with result 'dependency'.
Dec 22 17:42:54 davidelaptop systemd[1]: sys-subsystem-net-devices-wlan.device: Job sys-subsystem-net-devices-wlan.device/start failed with result 'timeout'.
Dec 22 17:42:54 davidelaptop systemd[1]: sys-subsystem-net-devices-wlan0.device: Job sys-subsystem-net-devices-wlan0.device/start timed out.
Dec 22 17:42:54 davidelaptop systemd[1]: Timed out waiting for device /sys/subsystem/net/devices/wlan0.
Dec 22 17:42:54 davidelaptop systemd[1]: Dependency failed for dhcpcd on wlan0.
Dec 22 17:42:54 davidelaptop systemd[1]: dhcpcd@wlan0.service: Job dhcpcd@wlan0.service/start failed with result 'dependency'.
Dec 22 17:42:54 davidelaptop systemd[1]: sys-subsystem-net-devices-wlan0.device: Job sys-subsystem-net-devices-wlan0.device/start failed with result 'timeout'.
Dec 22 17:42:54 davidelaptop systemd[1]: Reached target Network.
Dec 22 17:42:54 davidelaptop systemd[1]: Starting Permit User Sessions...
Dec 22 17:42:54 davidelaptop systemd[1]: Finished Permit User Sessions.
Dec 22 17:42:54 davidelaptop audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-user-sessions comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 22 17:42:54 davidelaptop kernel: audit: type=1130 audit(1671727374.804:34): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-user-sessions comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 22 17:42:54 davidelaptop systemd[1]: Started Getty on tty1.
Dec 22 17:42:54 davidelaptop audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=getty@tty1 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 22 17:42:54 davidelaptop systemd[1]: Reached target Login Prompts.
Dec 22 17:42:54 davidelaptop systemd[1]: Reached target Multi-User System.
Dec 22 17:42:54 davidelaptop systemd[1]: Reached target Graphical Interface.
Dec 22 17:42:54 davidelaptop systemd[1]: Startup finished in 8.403s (firmware) + 1.764s (loader) + 3.561s (kernel) + 1min 30.677s (userspace) = 1min 44.405s.
Dec 22 17:42:54 davidelaptop kernel: audit: type=1130 audit(1671727374.804:35): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=getty@tty1 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

**Comment by TheCourierNV** [comment]
There's a pull request [here](https://github.com/tomaspinho/rtl8821ce/pull/308) that implements a fix for Linux 6.1.1; I have been using it for the past few days and it works.

You could have also found it by reading the comment feed [on the page for the AUR package](https://aur.archlinux.org/packages/rtl8821ce-dkms-git)

I hope I didn't come across rudely, I just want to let you know where you could have found relevant info about this :^P

**Comment by CaneMandarinesco** [comment]
Thanks, i'll let you know if it works. but i'd like to point that this driver didn't work either for older Linux version on the same machine.

**Comment by CaneMandarinesco** [comment]
i'm sorry, didn't want to close the issue.
anyway, thanks. i'll try #308 and let you know if it works
