### ISSUE TITLE
Install Fails on CentOS 7 (TPLink Archer T2E PCI-Express card)

### ISSUE THREAD

**Issue by airbusman5514** [tomaspinho/rtl8821ce#319]
I'm in a bit of a pickle. I installed a TPLink Archer T2E card into my open PCI-express slot on my computer running CentOS 7. When tried to install the drivers for the b821 chipset, it kept showing a bad return status on the dkms build.

Adding to my complications is the kernel. I have to use the 3.10 kernel that came with CentOS. I upgraded to the 5.4 or whatever the newest one is, but it killed my Ethernet, which is my only link to the internet until I can get this adapter working.

Any help is appreciated.

![image](https://user-images.githubusercontent.com/28398677/226719244-1fde8fdd-0758-41c4-bdd7-3cce7f76b544.png)

**Comment by tomaspinho** [comment]
Linux 3.10 is almost 10 years old. CentOS is a distribution also not supported by this repository. I suggest you use a more recent kernel and distribution.
