### ISSUE TITLE
Wifi/Internet Connection speed decreases whenever I use Bluetooth with my headphones.

### ISSUE THREAD

**Issue by mh-saeed** [tomaspinho/rtl8821ce#328]
My system is using the same repo driver.
Whenever I turn on my Bluetooth and connect it with my headphones my Internet speed decreases.
 
![image](https://github.com/tomaspinho/rtl8821ce/assets/49342183/a84b947c-29d7-4feb-b389-434d7f21a503)

How can I fix it?

**Comment by dubhater** [comment]
You can fix it by using a separate Bluetooth or wifi adapter, one you plug into a USB port. It's kind of normal that the speed drops when you use Bluetooth because the antenna is shared.

**Comment by mh-saeed** [comment]
Ok, got it ...
