### ISSUE TITLE
kernel panic version >= 6.5.3

### ISSUE THREAD

**Issue by leandrocunha526** [tomaspinho/rtl8821ce#335]
I installed it with merge request (#332) here and installed this version of the Kernel here (6.5.3), when I turned off the machine I had a kernel panic twice and when I removed the module this did not happen again. With version 6.4.x or earlier this did not occur.

**Comment by Spixmaster** [comment]
Yes, you are right. That fix does not work. You may want to try out [this one](https://github.com/tomaspinho/rtl8821ce/issues/331#issuecomment-1724502847).

**Comment by leandrocunha526** [comment]
@Spixmaster From what you can see, this pull request you sent solves the problem and should be merged urgently.

**Comment by Crany-web** [comment]
> @Spixmaster从您所看到的，您发送的这个拉取请求解决了问题，应该紧急合并。

Hello, these problems occurred after I upgraded the Archlinux kernel to 6.5.x, but I am not very familiar with the kernel knowledge. Can you give me a specific solution? I would like to thank you very much.

**Comment by leandrocunha526** [comment]
> > @Spixmaster从您所看到的，您发送的这个拉取请求解决了问题，应该紧急合并。
> 
> Hello, these problems occurred after I upgraded the Archlinux kernel to 6.5.x, but I am not very familiar with the kernel knowledge. Can you give me a specific solution? I would like to thank you very much.

Repository clone where the indicated solution is located. I did this to test and considering that we already have something good ready.

**Comment by Crany-web** [comment]
> > > @Spixmaster从您所看到的，您发送的这个拉取请求解决了问题，应该紧急合并。
> > 
> > 
> > Hello, these problems occurred after I upgraded the Archlinux kernel to 6.5.x, but I am not very familiar with the kernel knowledge. Can you give me a specific solution? I would like to thank you very much.
> 
> Repository clone where the indicated solution is located. I did this to test and considering that we already have something good ready.

In other words, I only need to wait for the rtl8821ce-dkms-git update in the AUR to update the kernel to 6.5.x?

**Comment by leandrocunha526** [comment]
> > > > @Spixmaster从您所看到的，您发送的这个拉取请求解决了问题，应该紧急合并。
> > > 
> > > 
> > > Hello, these problems occurred after I upgraded the Archlinux kernel to 6.5.x, but I am not very familiar with the kernel knowledge. Can you give me a specific solution? I would like to thank you very much.
> > 
> > 
> > Repository clone where the indicated solution is located. I did this to test and considering that we already have something good ready.
> 
> In other words, I only need to wait for the rtl8821ce-dkms-git update in the AUR to update the kernel to 6.5.x?

@Crany-web This has been fixed in the repository: https://github.com/a1akris/rtl8821ce/tree/fix/331/strlen

**Comment by leandrocunha526** [comment]
#334 merged, close.
