### ISSUE TITLE
Problem with wifi 5ghz

### ISSUE THREAD

**Issue by dani9631** [tomaspinho/rtl8821ce#34]
In Ubuntu all version and derivate of Ubuntu,in Terminal withcommand iwlist search channel 5 ghz but in network manager search only wifi 2,4 ghz.
Can you resolve this problem in all kernel however from linux Kernel 4.15 to linux Kernel 5.0
P.S Practically until last version of Linux Kernel downloadable.
Please :-)

**Comment by tomaspinho** [comment]
As described in https://github.com/tomaspinho/rtl8821ce#disclaimer no further module development will be carried out here. If you can't make 5Ghz work, I'm afraid you're out of luck.

**Comment by Bleuzen** [comment]
Same problem.
Changing the wifi 5 ghz channel in my router did help. For some reason, some higher channels do not work. So it seeems that the driver does not support all 5 ghz wifi channels.

**Comment by tomaspinho** [comment]
Wondering if this could be because of US/EU/Japanese regulations considering the use of the spectrum. Have you tried changing regions in your WiFi applets?

**Comment by Bleuzen** [comment]
Maybe. Here is a part of `iw list` output:
![image](https://user-images.githubusercontent.com/12885163/58749695-57cdc580-8489-11e9-80cc-8fbbcfefaf3b.png)
Channels 36 - 48 and 149 - 165 work. All the others do not work, because they are disabled.

I tried setting the region:
`iw reg set EU`
and
`iw reg set US`
and
`iw reg set JP`
but the disabled channels stay the same.

How can I enable them?

**Comment by tomaspinho** [comment]
Taking a look at the code in

https://github.com/tomaspinho/rtl8821ce/blob/f6fd76fb39451ee4d2a6abde13cfcb4593685f49/os_dep/linux/wifi_regd.c

it looks like all regulatory domain changes are in fact ignored by the code in the driver. I don't have this chip anymore, so there's no way to debug it on my end, but if anyone is willing to play with it, I would take a look at that file in conjunction with flags set in 

https://github.com/tomaspinho/rtl8821ce/blob/f6fd76fb39451ee4d2a6abde13cfcb4593685f49/include/hal_ic_cfg.h
