### ISSUE TITLE
Stopped working with linux 6.6.5

### ISSUE THREAD

**Issue by graccoFG** [tomaspinho/rtl8821ce#340]
After updating the kernel to 6.6.5 it stopped working. it tells me it can't connect to wifi and the pc no longer responds to any commands. I had to downgrade kernel.

**Comment by jothi-prasath** [comment]
For temporary fix downgrade the Linux and linux-headers

**Comment by graccoFG** [comment]
Fixed with update to 6.6.5-3 kernel
