### ISSUE TITLE
Able to be ported to macOS?

### ISSUE THREAD

**Issue by SuperAviation001** [tomaspinho/rtl8821ce#355]
Title says it all. Is this driver able to be ported to macOS or have anything in it that can aid the porting to macOS (as a .kext)

**Comment by tomaspinho** [comment]
In a word, no.

A more comprehensive answer would be that an experienced Darwin Kernel developer would be able to look into these sources and replicate them for macOS. But this would be a bad reference given the existence of the newer `rtw88` module developed by Realtek.
