### ISSUE TITLE
No signal strength monitoring

### ISSUE THREAD

**Issue by sashamishchenko** [tomaspinho/rtl8821ce#40]
In kernels 5.1+ still have not signal strength monitoring...(((
My widget in KDE5.15 show no signal. Switching to kernel 5.0 resolve issue.
from logs:
wpa_supplicant[741]: ioctl[SIOCSIWAP]: Operation not permitted
wpa_supplicant[741]: ioctl[SIOCSIWENCODEEXT]: Invalid argument
wpa_supplicant[741]: ioctl[SIOCSIWENCODEEXT]: Invalid argument
wpa_supplicant[741]: bgscan simple: Failed to enable signal strength monitoring

**Comment by tomaspinho** [comment]
How's this issue with the latest version of the driver @sashamishchenko ?

**Comment by bsmith7581** [comment]
I'm still getting this error with the latest version of this driver on kernel 5.10.4.

**Comment by geoiii68** [comment]
I am ignoring this log entry. It does not seem to effect boot time and when it is all done singnal strength monitoring is on. ubuntu 20.04
