### ISSUE TITLE
Arch installation instructions can break an Arch system

### ISSUE THREAD

**Issue by Head-on-a-Stick** [tomaspinho/rtl8821ce#41]
The command listed in README.md to install the Arch Linux headers & dkms package performs what is known as a *partial upgrade* — `pacman -Sy` should *never* be used to install packages in an Arch system.

See https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported

The command should be:
```
pacman -Syu linux-headers dkms
```

**Comment by tomaspinho** [comment]
PRs are welcome 😀

**Comment by tomaspinho** [comment]
Thanks for the PR. Closing as it's already merged.
