### ISSUE TITLE
sudo modprobe 8821ce error

### ISSUE THREAD

**Issue by nadif15** [tomaspinho/rtl8821ce#43]
modprobe: FATAL: Module 8821ce not found in directory /lib/modules/4.19.0-kali3-amd64

**Comment by hashlib** [comment]
Are you sure that you successfully instaled the module?
Did you install it using DKMS? If not, are you sure that you have installed the module on the kernel that you are using right now?

**Comment by nadif15** [comment]
yes i did

**Comment by tomaspinho** [comment]
As per Readme:
```
It's targetting Linux > 4.14 and is being developed for ArchLinux and Ubuntu 18.10. No support will be provided for other Linux distributions or Linux Kernel versions outside of that range.
```

Closing.

**Comment by Adarshgabani** [comment]
i have the same issue FATAL: Module 8821CE not found in directory
