### ISSUE TITLE
Can't find SSIDs on channels 149-165

### ISSUE THREAD

**Issue by pookymaster** [tomaspinho/rtl8821ce#47]
On a Lenovo Ideapad. The drivers work, and I can connect to my 5ghz SSID on channels 30-51, but not 149-165. I don't know if this is a limitation of the driver, but this chipset is supposed to be able to connect to an SSID on those channels. I ran the command suggestion in the ideapad section of the write up on the drivers, and rebooted, but I still am not able to pickup the SSID I want to connect to.

**Comment by hashlib** [comment]
The same as #34

**Comment by pookymaster** [comment]
Not really the same as #34. That person's issue is that they're not finding DSF channels. From what I can tell, this chipset is not compatible with DSF.

**Comment by hashlib** [comment]
I think that you can't find any help here because of this: https://github.com/tomaspinho/rtl8821ce/blob/master/README.md#disclaimer

There is one new driver in Linux Kernel that will support rtl8821ce soon.

**Comment by tomaspinho** [comment]
Hi @pookymaster ! I'm in the process of merging much newer sources for this driver at #54. Would you mind trying those and see if it fixed this problem?

**Comment by hashlib** [comment]
@tomaspinho, new version of driver fixed this issue for me.

**Comment by pookymaster** [comment]
I found that the current version works for me. I can't remember if it was
after a clean install or not.

**Comment by tomaspinho** [comment]
Ok guys, I'm closing this one. Thanks for all your help!
