### ISSUE TITLE
dkms: command not found

### ISSUE THREAD

**Issue by priyansh-07** [tomaspinho/rtl8821ce#49]
On Lenovo IdeaPad 130-15ikb, i ran sudo ./dkms-install.sh and it gives the following error : 
About to run dkms install steps...
./dkms-install.sh : line 16: dkms: command not found
./dkms-install.sh : line 17: dkms: command not found
./dkms-install.sh : line 18: dkms: command not found
Finished running dkms install steps.
I'm using Ubuntu 19.04

**Comment by tomaspinho** [comment]
Please read the docs thoroughly next time.
https://github.com/tomaspinho/rtl8821ce#ubuntu--debian
