### ISSUE TITLE
Got bluetooth, but no wifi

### ISSUE THREAD

**Issue by miguelgondu** [tomaspinho/rtl8821ce#5]
Hi, tomaspinho.

Thanks for maintaining this driver.

I have a fresh Ubuntu 18.04 installation in a HP Pavilion 15. If I run `lspci | grep Network` I get

```
01:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
```

So I figured I could install your driver. Something weird happened: now I have bluetooth, but I still lack wifi. Do you know how could I perhaps fix this? Please let me know if I could give you more info about my pc and my ubuntu installation.

**Comment by tomaspinho** [comment]
Hey, Miguel

Can you please run lscpi -k and send me the section about your 
rtl8821ce? Just to check if the module is in use.

Have you disabled UEFI security checks in regarding to loading unsigned 
modules? You may need that too.

Best,

Tomás

**Comment by miguelgondu** [comment]
Hi, Tomás.

I woke up to the problem solved. Weird, since I rebooted my machine several times yesterday. Now I'm writing this from my wifi.

It indeed was using your driver:
```
01:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
	Subsystem: Hewlett-Packard Company RTL8821CE 802.11ac PCIe Wireless Network Adapter
	Kernel driver in use: rtl8821ce
	Kernel modules: 8821ce
```

Thanks,

Miguel.
