### ISSUE TITLE
Wifi Disabled

### ISSUE THREAD

**Issue by BumRummy** [tomaspinho/rtl8821ce#52]
Iw config says
Wlan0 unassociated Nickname:"<WIFI@REALTEK>"
Mode: Auto Frequency 2.412 GHz Access Point: Not Associated
Sensitivity:0/0 Retry: off RTS thr:off
Fragment thr: off
Power Management: off Link Quality=0/100 Signal level=0dBm Noise level=0 dBm RX invalid nwid:0 RX Invalid Crypt:0 Rx Invalid frag:0 Tx excessive retries:0 Invalid misc:0 Missed Beacon:0

Any help would be greatly appreciated!

**Comment by tomaspinho** [comment]
How's this issue with the latest version of the driver @BumRummy ?

**Comment by shaardul** [comment]
```
lo        no wireless extensions.

wlp2s0    unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

enp1s0    no wireless extensions.
```

I tried today and we still have this

**Comment by shaardul** [comment]
it was a wifi hard block problem and got fixed by
```echo "blacklist ideapad_laptop" | sudo tee /etc/modprobe.d/ideapad.conf```

**Comment by BumRummy** [comment]
Ah, thank you very much.

**Comment by tomaspinho** [comment]
This was already documented in the Readme, nobody reads the docs... 😓

**Comment by BumRummy** [comment]
I promise I read them all, I guess I overlooked this. Sorry but thanks for
your help!

**Comment by tomaspinho** [comment]
It's alright, don't worry! 😄
