### ISSUE TITLE
Wireless adapter doesn't work

### ISSUE THREAD

**Issue by hashlib** [tomaspinho/rtl8821ce#56]
My module was turned on but not connected for half an hour. It was working for about 2-3 minutes. Dmesg didn't say anything. I tried to turn it off and on again. 
After that dmesg was full of 
`[ 9326.931635] RTW: pci_write_data_h2c_normal: alloc ReservedPagePacket fail!`
` [ 9326.931642] RTW: _alloc_mgtxmitframe(wlp1s0) alloc xmitbuf fail`

I tried to do `sudo modprobe 8821ce -r` `sudo modprobe 8821ce` but it didn't make everything right. Dmesg log after modprobe: [issue.log](https://github.com/tomaspinho/rtl8821ce/files/3476754/issue.log)
After reboot it works normally.

**Comment by tomaspinho** [comment]
Did your machine go to sleep at any time?

**Comment by hashlib** [comment]
No, it was only locked up for a bit.

**Comment by hashlib** [comment]
Maybe my laptop really went to sleep mode, because right now I have the same problem and the same dmesg output after sleep.

**Comment by iseymur** [comment]
i use fedora 30
when i installed wifi from last update
root@dhcppc12 rtl8821ce-master]# ./dkms-install.sh 
About to run dkms install steps...

Creating symlink /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/source ->
                 /usr/src/rtl8821ce-v5.5.2_34066.20190614

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.2.9-200.fc30.x86_64.........(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.2.9-200.fc30.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.2.9-200.fc30.x86_64.........(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.2.9-200.fc30.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.
Finished running dkms install steps.
