### ISSUE TITLE
In case of problems with connecting to wifi networks, you could disable PCIe power savings

### ISSUE THREAD

**Issue by fantomas** [tomaspinho/rtl8821ce#6]
I have HP Pavilion - 15-cs0511sa and Ubuntu 18.04. I installed this driver (10x!) and I was able to see the networks. But I had problems connecting. After a research it happened that I should disable the PCIe power savings. I used this guide https://askubuntu.com/a/1041830/882226. Now I am connecting to the wifi as expected.

**Comment by tomaspinho** [comment]
Hey @fantomas. Good to know you've found a workaround for your specific use-case. Why is this an issue, though?

**Comment by fantomas** [comment]
It is not a direct issue with the driver. I have spent some hours debugging and thought that it could be helpful to somebody. Someone could think that there is something wrong with the driver, as you start seeing the networks, but you are unable to connect. 

Anyway if you have time in the future you can check if it is possible your driver to work also with PCIe power savings.  You can add label 'enhancement' (https://help.github.com/articles/about-labels/#using-default-labels) or you can close it.

**Comment by tomaspinho** [comment]
Ok, added the information to the README. Closing.
