### ISSUE TITLE
Can't build on Arch Linux

### ISSUE THREAD

**Issue by ItsMoonPy** [tomaspinho/rtl8821ce#65]
Log:
`About to run dkms install steps...

Creating symlink /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/source ->
                 /usr/src/rtl8821ce-v5.5.2_34066.20190614

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.2.9-arch1-1-ARCH......(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.2.9-arch1-1-ARCH (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.2.9-arch1-1-ARCH......(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.2.9-arch1-1-ARCH (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.
Finished running dkms install steps.`

/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log: 
`DKMS make.log for rtl8821ce-v5.5.2_34066.20190614 for kernel 5.2.9-arch1-1-ARCH (x86_64)
Пн авг 19 05:35:31 UTC 2019
/bin/sh: bc: команда не найдена
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.2.9-arch1-1-ARCH/build M=/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build  modules
make[1]: вход в каталог «/usr/lib/modules/5.2.9-arch1-1-ARCH/build»
/bin/sh: bc: команда не найдена
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_io.o
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c:17:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/wifi.h:1030: предупреждение: «IEEE80211_MAX_AMPDU_BUF» переопределён
 1030 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c:17:
./include/linux/ieee80211.h:1441: замечание: это расположение предыдущего определения
 1441 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_cmd.c:17:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/wifi.h:1030: предупреждение: «IEEE80211_MAX_AMPDU_BUF» переопределён
 1030 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_cmd.c:17:
./include/linux/ieee80211.h:1441: замечание: это расположение предыдущего определения
 1441 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_security.c:17:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/wifi.h:1030: предупреждение: «IEEE80211_MAX_AMPDU_BUF» переопределён
 1030 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_security.c:17:
./include/linux/ieee80211.h:1441: замечание: это расположение предыдущего определения
 1441 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_io.c:47:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/wifi.h:1030: предупреждение: «IEEE80211_MAX_AMPDU_BUF» переопределён
 1030 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_io.c:47:
./include/linux/ieee80211.h:1441: замечание: это расположение предыдущего определения
 1441 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c: В функции «dump_drv_version»:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c:45:62: ошибка: макрос «__DATE__» может помешать повторным сборкам [-Werror=date-time]
   45 |  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                                              ^
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:60,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c:17:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c:45:44: ошибка: макрос «__TIME__» может помешать повторным сборкам [-Werror=date-time]
   45 |  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                            ^~~~~~~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/rtw_debug.h:114:34: замечание: в определении макроса «RTW_PRINT»
  114 |    _dbgdump(DRIVER_PREFIX fmt, ##arg);\
      |                                  ^~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c:45:2: замечание: в расширении макроса «RTW_PRINT_SEL»
   45 |  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |  ^~~~~~~~~~~~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c:45:54: ошибка: макрос «__DATE__» может помешать повторным сборкам [-Werror=date-time]
   45 |  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                                      ^~~~~~~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/rtw_debug.h:114:34: замечание: в определении макроса «RTW_PRINT»
  114 |    _dbgdump(DRIVER_PREFIX fmt, ##arg);\
      |                                  ^~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c:45:2: замечание: в расширении макроса «RTW_PRINT_SEL»
   45 |  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |  ^~~~~~~~~~~~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.c:45:44: ошибка: макрос «__TIME__» может помешать повторным сборкам [-Werror=date-time]
   45 |  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                            ^~~~~~~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/rtw_debug.h:224:25: замечание: в определении макроса «RTW_PRINT_SEL»
  224 |    _seqdump(sel, fmt, ##arg) /*rtw_warn_on(1)*/; \
      |                         ^~~
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_ieee80211.o
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_ioctl_query.c:17:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/wifi.h:1030: предупреждение: «IEEE80211_MAX_AMPDU_BUF» переопределён
 1030 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_ioctl_query.c:17:
./include/linux/ieee80211.h:1441: замечание: это расположение предыдущего определения
 1441 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_ioctl_set.c:17:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/wifi.h:1030: предупреждение: «IEEE80211_MAX_AMPDU_BUF» переопределён
 1030 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_ioctl_set.c:17:
./include/linux/ieee80211.h:1441: замечание: это расположение предыдущего определения
 1441 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_mlme.o
cc1: некоторые предупреждения считаются ошибками
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.o] Ошибка 1
make[2]: *** Ожидание завершения заданий…
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_ieee80211.c:20:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/wifi.h:1030: предупреждение: «IEEE80211_MAX_AMPDU_BUF» переопределён
 1030 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_ieee80211.c:20:
./include/linux/ieee80211.h:1441: замечание: это расположение предыдущего определения
 1441 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/../hal/phydm/phydm_types.h:201,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/../hal/phydm/phydm_precomp.h:29,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/hal_data.h:20,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_mlme.c:17:
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/wifi.h:1030: предупреждение: «IEEE80211_MAX_AMPDU_BUF» переопределён
 1030 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/../hal/phydm/phydm_types.h:201,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/../hal/phydm/phydm_precomp.h:29,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/include/hal_data.h:20,
                 from /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_mlme.c:17:
./include/linux/ieee80211.h:1441: замечание: это расположение предыдущего определения
 1441 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
make[1]: *** [Makefile:1597: _module_/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build] Ошибка 2
make[1]: выход из каталога «/usr/lib/modules/5.2.9-arch1-1-ARCH/build»
make: *** [Makefile:2237: modules] Ошибка 2
`

help plz
Lenovo Ideapad 330

**Comment by tomaspinho** [comment]
Install `bc`, try again

**Comment by kimerza** [comment]
thank you tomaspinho it's work
