### ISSUE TITLE
Unknown symbol cfg80211_ on modprobe

### ISSUE THREAD

**Issue by skinnersBoxy** [tomaspinho/rtl8821ce#68]
The driver builds and installs without a hitch, but on either `modprobe 8821ce` or boot there are a lot of dmesg outputs of the form
```
8821ce: Unknown symbol __cfg80211_alloc_event_skb (err -2)
8821ce: Unknown symbol wiphy_register (err -2)
8821ce: Unknown symbol cfg80221_remain_on_channel_expired (err -2)
...
8821ce: Unknown symbol ieee80211_frequency_to_channel (err -2)
...
```
There is no ethernet port on this laptop so I have to copy the messages manually. Let me know if you need to know all of them, but they all take the form __cfg80211 or cfg80211 or wiphy or ieee80211.

I got the plugin to work on kernel 4.15 but I'm trying on kernel 4.18 because my trackpad won't work before then. I did uninstall and reinstall when I switched kernels.

**Comment by skinnersBoxy** [comment]
Installing Ubuntu 19 fixed the issue for whatever reason.

**Comment by KyomaHooin** [comment]
You have to insert cfg80211 module before 8821ce:
```
modprobe cfg80211
modprobe 8821ce
```
