### ISSUE TITLE
Wifi working, no Bluetooth found

### ISSUE THREAD

**Issue by maybir** [tomaspinho/rtl8821ce#69]
Hi.
After installing your driver (you are a godsend, man!) wifi started working, but bluetooth is still non-existing. I saw the "BlueTooth is not working" tutorial but I think my situation is different, because I see no indication bluetooth physically exists (although I'm supposed to have "Intel® 802.11b/g/n/ac (1x1) Wi-Fi® and Bluetooth® 4.2 Combo" according to the purchased spec).

```
$ rfkill
ID TYPE DEVICE      SOFT      HARD
 0 wlan phy0   unblocked unblocked

$ hciconfig -a
$

$ lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 10000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/12p, 480M
    |__ Port 5: Dev 2, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 5: Dev 2, If 1, Class=Video, Driver=uvcvideo, 480M
```

Is there a possibility I have bluetooth and this is just a driver problem?
Will following the tutorial help?

TIA,
May

**Comment by hashlib** [comment]
Hello. It isn't working after a clean boot too?

**Comment by maybir** [comment]
No, it isn't working after clean boot.

**Comment by harryyoud** [comment]
Errrr.... just to double check, what model of wireless radio is in your computer? You mention "Intel® 802.11b/g/n/ac (1x1) Wi-Fi® and Bluetooth® 4.2 Combo", but this driver is for Realtek chips starting RTL8821C

Maybe share the result of `lspci` on your system?

**Comment by sososophie97** [comment]
Same problem here. WiFi is working fine but no sign of bluetooth.

    $ lspci | grep 8821
    02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter

**Comment by harryyoud** [comment]
Okay @sososophie97, you have the correct chip, and you should find Bluetooth under `lsusb -t`

**Comment by tomaspinho** [comment]
@sososophie97 what's your laptop make and model? Some Lenovo Yoga configurations trigger the usage of the lenovo-laptop package that is incompatible with this module (check README).
