### ISSUE TITLE
please help, i want to install this wifi driver but i got a problem.

### ISSUE THREAD

**Issue by devinahan** [tomaspinho/rtl8821ce#70]
root@kali:~/Desktop/rtl8821ce# ls
clean            Dockerfile      include        PKGBUILD     wlan0dhcp
core             get_sources.sh  Kconfig        platform
dkms.conf        hal             Makefile       README.md
dkms-install.sh  halmac.mk       modules.order  rtl8821c.mk
dkms-remove.sh   ifcfg-wlan0     os_dep         runwpa
root@kali:~/Desktop/rtl8821ce# sudo ./dkms-install.sh
About to run dkms install steps...

Creating symlink /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/source ->
                 /usr/src/rtl8821ce-v5.5.2_34066.20190614

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=4.19.0-kali4-amd64.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.0-kali4-amd64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=4.19.0-kali4-amd64.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.0-kali4-amd64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.
Finished running dkms install steps.

**Comment by harryyoud** [comment]
Okay, number one, don't go compiling things as root.

Number two, why not read what the dkms install has just outputted:
```
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/make.log for more information.
```

So go rerun the dkms-install.sh script and then **attach** (please don't copy-paste) the contents of that make.log file it tells you to consult

**Comment by tomaspinho** [comment]
Stale issue, closing.
