### ISSUE TITLE
PANIC! kernel NULL pointer dereference, address 0000000000000000

### ISSUE THREAD

**Issue by meganukebmp** [tomaspinho/rtl8821ce#77]
Machine: ASUS FX505DT
CPU: Ryzen 7 3700H
GPU: Nvidia GTX1650
OS: Arch Linux Linux 5.2.14
Driver version: Current Upstream

Issue: Kernel panic on random occasions

bad dereference in memcpy at https://github.com/tomaspinho/rtl8821ce/blob/6b9a569657afb530020c3489ff88886ad7b157ce/core/rtw_mlme.c#L4302

Issue attached as image (sorry, can't export log)
![IMG_20190913_125334](https://user-images.githubusercontent.com/5718823/64913152-30022500-d73b-11e9-9c38-4a41e129139f.jpg)
![IMG_20190913_125516](https://user-images.githubusercontent.com/5718823/64913153-309abb80-d73b-11e9-8e0c-6a8f52db0375.jpg)
![IMG_20190913_125459](https://user-images.githubusercontent.com/5718823/64913154-309abb80-d73b-11e9-80d2-042a06c7bf90.jpg)

**Comment by tomaspinho** [comment]
Unfortunately this is the kind of thing that is way too out of my wheelhouse to help with 😞, especially since I don't really own the hardware anymore.

**Comment by meganukebmp** [comment]
No worries, reporting for the sake of documenting it.
