### ISSUE TITLE
ModProbe Error RTL8821CE

### ISSUE THREAD

**Issue by danrod03** [tomaspinho/rtl8821ce#79]
I copy all the commands and make error when run the module 
When Install About to run dkms install steps...

Creating symlink /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/source ->
                 /usr/src/rtl8821ce-v5.5.2_34066.20190614

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.0.0-27-generic............
Signing module:
 - /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/5.0.0-27-generic/x86_64/module/8821ce.ko
Nothing to do.
cleaning build area...

DKMS: build completed.

8821ce.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.0.0-27-generic/updates/dkms/

depmod...

DKMS: install completed.
Finished running dkms install steps.
[make.log](https://github.com/tomaspinho/rtl8821ce/files/3617142/make.log)

But when run sudo modprobe 8821ce
modprobe: ERROR: could not insert '8821ce': Operation not permitted

**Comment by tomaspinho** [comment]
Is your kernel cryptographically signed? Are you running secure boot? If so, disable those first.

**Comment by LanderElizondo** [comment]
I managed to install it following this video.
I hope it helps: 
https://youtu.be/vPfLVsyQU_A

On the other hand, I'm having some trouble because it creates tons of logs. Would you be so kind to tell me how to silence it?

**Comment by danrod03** [comment]
SOlVED, i only make a apt update after installing and work my wifi.

**Comment by abc-ziv** [comment]
modprobe: ERROR: could not insert '8821ce': Operation not permitted
和您出现了一样的问题。目前不清楚如何解决。
