### ISSUE TITLE
forgotten wifi password

### ISSUE THREAD

**Issue by Lewiscowles1986** [tomaspinho/rtl8821ce#8]
Strange thing I noticed on my machine is that the adapter dropped off if unused, and the laptop seems to create a whole new interface when it comes back up.

Any clues? I can re-compile (I compiled in tmp)

Ubuntu 18.04 vanilla

`uname -a`
> Linux lewis-HP-Pavilion-Laptop-15-cs0xxx 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[lspci.txt](https://github.com/tomaspinho/rtl8821ce/files/2493233/lspci.txt)
[cpuinfo.txt](https://github.com/tomaspinho/rtl8821ce/files/2493234/cpuinfo.txt)

**Comment by Lewiscowles1986** [comment]
Hi Tomas, I don't understand why pci power would lose the adapter password.

I have not encountered the issue since as I mostly use the device at work. I was wondering if there was some way to preserve the adapter name between power off. I don't mind the wlan losing power every now and then, I'd just prefer when it came back up it remembered the device assignment.

Thanks for authoring this.

**Comment by tomaspinho** [comment]
The only reason I would see for your adapter turning off and coming back up with a different name would be PCI power management turning it off and then it being re-assigned. Device names are usually assigned by the kernel, but your udev rules may be at play here.

Unfortunately I can't provide support for this as this is not a module concern. Closing issue.
