### ISSUE TITLE
Can`t install on Manjaro with core 5.3

### ISSUE THREAD

**Issue by warcadaw** [tomaspinho/rtl8821ce#82]
Hello, I have some trouble with installation drivers for network controller rtl8821ce.
With core 4.1 installation goes without problems
With core 5.3 installation ends with error

[make.log](https://github.com/tomaspinho/rtl8821ce/files/3628038/make.log)
(I apologize for the Russified make.log =) )

***

And one more question:
Can the driver rtl8821ce causes total freezes of the operating system? (REISUB does not help, even the ctrl+alt+F2 console does not open). helps only reboot.
I have such a problem but can't localize it. On one of the forums someone claimed that he had such a problem with the Realtek Network controller

**Comment by meganukebmp** [comment]
To your freeze situation. Likely https://github.com/tomaspinho/rtl8821ce/issues/77. I experience freezes as well, can only catch them if I'm on TTY when they happen

**Comment by Strit** [comment]
I am experiencing this too.
Module compiles fine for kernels 5.3.7 and below, but fails for kernel 5.3.8 and above.
Here's the pacman log for it:
```
[2019-11-11T11:29:53+0100] [ALPM-SCRIPTLET] ==> dkms install rtl8821ce/1.0.5.r70.g9d8699f -k 4.19.82-1-MANJARO
[2019-11-11T11:30:40+0100] [ALPM-SCRIPTLET] ==> dkms install rtl8821ce/1.0.5.r70.g9d8699f -k 5.3.10-1-MANJARO
[2019-11-11T11:30:43+0100] [ALPM-SCRIPTLET] Error! Bad return status for module build on kernel: 5.3.10-1-MANJARO (x86_64)
[2019-11-11T11:30:43+0100] [ALPM-SCRIPTLET] Consult /var/lib/dkms/rtl8821ce/1.0.5.r70.g9d8699f/build/make.log for more information.
```
I don't have the make.log from the failed build, since I need my wifi for work. But I can get it after work, if it's needed.

**Comment by tomaspinho** [comment]
Will try and make this on Manjaro tonight.

**Comment by tomaspinho** [comment]
Just managed to build this module successfully on Manjaro with kernel 5.3.10. Make sure you have fully removed the module and reinstalled as per instructions in the README.

**Comment by Strit** [comment]
Your right. It was again a version mismatch in GCC.

After correcting that, it builds fine.
