### ISSUE TITLE
When ubuntu 18.04.3 LTS is updated then the driver does not work

### ISSUE THREAD

**Issue by omiraval** [tomaspinho/rtl8821ce#83]
I installed the driver in my laptop HP-ProBook-450-G5 with ubuntu 18.04.3 LTS but when the SO is updated, I have to install again. I used the following commands:

git clone https://github.com/tomaspinho/rtl8821ce.git
cd rtl8821ce/
sudo make clean
sudo make all
sudo make install
sudo modprobe -a 8821ce

**Comment by tomaspinho** [comment]
Possibly because dkms was not run and did not build the module for the new kernel. There's nothing we can do from our side.
