### ISSUE TITLE
kernel 5.3 device probe error

### ISSUE THREAD

**Issue by tanxiang** [tomaspinho/rtl8821ce#84]
9月 22 21:25:29 p4ryzen7 kernel: RTW: rtw_read_efuse_from_file /system/etc/wifi/wifi_efuse_8821ce.map is not readable
9月 22 21:25:29 p4ryzen7 kernel: RTW: hal_com_config_channel_plan chplan:0x7F
9月 22 21:25:29 p4ryzen7 kernel: RTW: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
9月 22 21:25:29 p4ryzen7 kernel: ------------[ cut here ]------------
9月 22 21:25:29 p4ryzen7 kernel: WARNING: CPU: 1 PID: 342 at net/wireless/core.c:868 wiphy_register.cold+0x37/0x435 [cfg80211]
9月 22 21:25:29 p4ryzen7 kernel: Modules linked in: nls_iso8859_1 fjes(-) aes_x86_64 drm_kms_helper crypto_simd nls_cp437 snd_hda_codec vfat cryptd fat glue_helper pcc_cpufreq(-) 8821ce(OE+) drm snd_hda_core snd_hwdep snd_pcm pcspkr agpg>
9月 22 21:25:29 p4ryzen7 kernel: CPU: 1 PID: 342 Comm: systemd-udevd Tainted: G           OE     5.3.0-arch1-1-ARCH #1
9月 22 21:25:29 p4ryzen7 kernel: Hardware name: HP HP Laptop 14s-dp0xxx/85E0, BIOS F.38 03/13/2019
9月 22 21:25:29 p4ryzen7 kernel: RIP: 0010:wiphy_register.cold+0x37/0x435 [cfg80211]
9月 22 21:25:29 p4ryzen7 kernel: Code: 0b b8 ea ff ff ff e9 2c 17 fa ff 48 c7 c7 f8 96 73 c0 e8 18 c1 7c e6 0f 0b e9 07 1c fa ff 48 c7 c7 f8 96 73 c0 e8 05 c1 7c e6 <0f> 0b b8 ea ff ff ff e9 01 17 fa ff 48 c7 c7 f8 96 73 c0 e8 ed c0
9月 22 21:25:29 p4ryzen7 kernel: RSP: 0018:ffffa2904065b930 EFLAGS: 00010246
9月 22 21:25:29 p4ryzen7 kernel: RAX: 0000000000000024 RBX: 000000000000030e RCX: 0000000000000000
9月 22 21:25:29 p4ryzen7 kernel: RDX: 0000000000000000 RSI: ffff92ced0a57708 RDI: 00000000ffffffff
9月 22 21:25:29 p4ryzen7 kernel: RBP: ffffa2904065b9b0 R08: 000000000000055c R09: 0000000000000001
9月 22 21:25:29 p4ryzen7 kernel: R10: 0000000000000000 R11: 0000000000000001 R12: ffff92cec0b8e300
9月 22 21:25:29 p4ryzen7 kernel: R13: ffffa2904065b940 R14: ffffa290404b4b60 R15: ffffffffc0ab512f
9月 22 21:25:29 p4ryzen7 kernel: FS:  00007fe363d9e840(0000) GS:ffff92ced0a40000(0000) knlGS:0000000000000000
9月 22 21:25:29 p4ryzen7 kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
9月 22 21:25:29 p4ryzen7 kernel: CR2: 00007f2f5d4df670 CR3: 0000000387b00000 CR4: 00000000003406e0
9月 22 21:25:29 p4ryzen7 kernel: Call Trace:
9月 22 21:25:29 p4ryzen7 kernel:  rtw_wiphy_register+0x22/0x4c [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  rtw_cfg80211_ndev_res_register+0x15/0x56 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  rtw_os_ndev_register+0x10c/0x186 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  rtw_os_ndevs_register+0x9a/0x11e [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  rtw_os_ndevs_init+0x24/0x38 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  rtw_drv_init+0x3b6/0xaf9 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  local_pci_probe+0x42/0x80
9月 22 21:25:29 p4ryzen7 kernel:  ? pci_match_device+0xc5/0x100
9月 22 21:25:29 p4ryzen7 kernel:  pci_device_probe+0x104/0x1a0
9月 22 21:25:29 p4ryzen7 kernel:  really_probe+0xf0/0x380
9月 22 21:25:29 p4ryzen7 kernel:  driver_probe_device+0xb6/0x100
9月 22 21:25:29 p4ryzen7 kernel:  device_driver_attach+0x53/0x60
9月 22 21:25:29 p4ryzen7 kernel:  __driver_attach+0x8a/0x150
9月 22 21:25:29 p4ryzen7 kernel:  ? device_driver_attach+0x60/0x60
9月 22 21:25:29 p4ryzen7 kernel:  ? device_driver_attach+0x60/0x60
9月 22 21:25:29 p4ryzen7 kernel:  bus_for_each_dev+0x89/0xd0
9月 22 21:25:29 p4ryzen7 kernel:  bus_add_driver+0x14a/0x1e0
9月 22 21:25:29 p4ryzen7 kernel:  driver_register+0x6c/0xb0
9月 22 21:25:29 p4ryzen7 kernel:  ? 0xffffffffc0bab000
9月 22 21:25:29 p4ryzen7 kernel:  rtw_drv_entry+0x74/0x1000 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  do_one_initcall+0x59/0x234
9月 22 21:25:29 p4ryzen7 kernel:  do_init_module+0x5c/0x230
9月 22 21:25:29 p4ryzen7 kernel:  load_module+0x218f/0x2400
9月 22 21:25:29 p4ryzen7 kernel:  ? __se_sys_init_module+0x114/0x180
9月 22 21:25:29 p4ryzen7 kernel:  __se_sys_init_module+0x114/0x180
9月 22 21:25:29 p4ryzen7 kernel:  do_syscall_64+0x5f/0x1c0
9月 22 21:25:29 p4ryzen7 kernel:  entry_SYSCALL_64_after_hwframe+0x44/0xa9
9月 22 21:25:29 p4ryzen7 kernel: RIP: 0033:0x7fe3655b8b3e
9月 22 21:25:29 p4ryzen7 kernel: Code: 48 8b 0d 55 f3 0b 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 49 89 ca b8 af 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 22 f3 0b 00 f7 d8 64 89 01 48
9月 22 21:25:29 p4ryzen7 kernel: RSP: 002b:00007ffd00feaa68 EFLAGS: 00000246 ORIG_RAX: 00000000000000af
9月 22 21:25:29 p4ryzen7 kernel: RAX: ffffffffffffffda RBX: 0000563fbaf828b0 RCX: 00007fe3655b8b3e
9月 22 21:25:29 p4ryzen7 kernel: RDX: 00007fe36520b84d RSI: 0000000000414e10 RDI: 0000563fbb94b100
9月 22 21:25:29 p4ryzen7 kernel: RBP: 00007fe36520b84d R08: 000000000000005f R09: 0000563fbaf8dcc0
9月 22 21:25:29 p4ryzen7 kernel: R10: 0000563fbad87010 R11: 0000000000000246 R12: 0000563fbb94b100
9月 22 21:25:29 p4ryzen7 kernel: R13: 0000563fbaf82cc0 R14: 0000000000020000 R15: 0000563fbaf828b0
9月 22 21:25:29 p4ryzen7 kernel: ---[ end trace 0801c730d76c6d62 ]---
9月 22 21:25:29 p4ryzen7 kernel: ------------[ cut here ]------------
9月 22 21:25:29 p4ryzen7 kernel: WARNING: CPU: 1 PID: 342 at /var/lib/dkms/rtl8821ce/1.0.5.r43.g6274276/build/os_dep/linux/os_intfs.c:1514 rtw_os_ndev_register+0xb1/0x186 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel: Modules linked in: nls_iso8859_1 fjes(-) aes_x86_64 drm_kms_helper crypto_simd nls_cp437 snd_hda_codec vfat cryptd fat glue_helper 8821ce(OE+) drm snd_hda_core snd_hwdep snd_pcm pcspkr agpgart snd_timer r>
9月 22 21:25:29 p4ryzen7 kernel: CPU: 1 PID: 342 Comm: systemd-udevd Tainted: G        W  OE     5.3.0-arch1-1-ARCH #1
9月 22 21:25:29 p4ryzen7 kernel: Hardware name: HP HP Laptop 14s-dp0xxx/85E0, BIOS F.38 03/13/2019
9月 22 21:25:29 p4ryzen7 kernel: RIP: 0010:rtw_os_ndev_register+0xb1/0x186 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel: Code: 4d 39 fd 0f 85 a4 00 00 00 48 89 ef e8 8f 02 b9 e6 85 c0 0f 94 c0 0f b6 c0 e9 9f 00 00 00 48 c7 c7 48 8c ac c0 e8 94 65 52 e6 <0f> 0b e9 b6 00 00 00 c6 83 38 4c 00 00 01 e9 b7 00 00 00 0f b6 8b
9月 22 21:25:29 p4ryzen7 kernel: RSP: 0018:ffffa2904065b9e0 EFLAGS: 00010246
9月 22 21:25:29 p4ryzen7 kernel: RAX: 0000000000000024 RBX: ffffa290404b1000 RCX: 0000000000000000
9月 22 21:25:29 p4ryzen7 kernel: RDX: 0000000000000000 RSI: ffff92ced0a57708 RDI: 00000000ffffffff
9月 22 21:25:29 p4ryzen7 kernel: RBP: ffff92cecd6ea000 R08: 0000000000000591 R09: 0000000000000001
9月 22 21:25:29 p4ryzen7 kernel: R10: 0000000000000000 R11: 0000000000000001 R12: ffffa290404b49c2
9月 22 21:25:29 p4ryzen7 kernel: R13: 0000000000000000 R14: ffffa290404b4b60 R15: ffffffffc0ab512f
9月 22 21:25:29 p4ryzen7 kernel: FS:  00007fe363d9e840(0000) GS:ffff92ced0a40000(0000) knlGS:0000000000000000
9月 22 21:25:29 p4ryzen7 kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
9月 22 21:25:29 p4ryzen7 kernel: CR2: 00007f2f5d4df670 CR3: 0000000387b00000 CR4: 00000000003406e0
9月 22 21:25:29 p4ryzen7 kernel: Call Trace:
9月 22 21:25:29 p4ryzen7 kernel:  rtw_os_ndevs_register+0x9a/0x11e [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  rtw_os_ndevs_init+0x24/0x38 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  rtw_drv_init+0x3b6/0xaf9 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  local_pci_probe+0x42/0x80
9月 22 21:25:29 p4ryzen7 kernel:  ? pci_match_device+0xc5/0x100
9月 22 21:25:29 p4ryzen7 kernel:  pci_device_probe+0x104/0x1a0
9月 22 21:25:29 p4ryzen7 kernel:  really_probe+0xf0/0x380
9月 22 21:25:29 p4ryzen7 kernel:  driver_probe_device+0xb6/0x100
9月 22 21:25:29 p4ryzen7 kernel:  device_driver_attach+0x53/0x60
9月 22 21:25:29 p4ryzen7 kernel:  __driver_attach+0x8a/0x150
9月 22 21:25:29 p4ryzen7 kernel:  ? device_driver_attach+0x60/0x60
9月 22 21:25:29 p4ryzen7 kernel:  ? device_driver_attach+0x60/0x60
9月 22 21:25:29 p4ryzen7 kernel:  bus_for_each_dev+0x89/0xd0
9月 22 21:25:29 p4ryzen7 kernel:  bus_add_driver+0x14a/0x1e0
9月 22 21:25:29 p4ryzen7 kernel:  driver_register+0x6c/0xb0
9月 22 21:25:29 p4ryzen7 kernel:  ? 0xffffffffc0bab000
9月 22 21:25:29 p4ryzen7 kernel:  rtw_drv_entry+0x74/0x1000 [8821ce]
9月 22 21:25:29 p4ryzen7 kernel:  do_one_initcall+0x59/0x234
9月 22 21:25:29 p4ryzen7 kernel:  do_init_module+0x5c/0x230
9月 22 21:25:29 p4ryzen7 kernel:  load_module+0x218f/0x2400
9月 22 21:25:29 p4ryzen7 kernel:  ? __se_sys_init_module+0x114/0x180
9月 22 21:25:29 p4ryzen7 kernel:  __se_sys_init_module+0x114/0x180
9月 22 21:25:29 p4ryzen7 kernel:  do_syscall_64+0x5f/0x1c0
9月 22 21:25:29 p4ryzen7 kernel:  entry_SYSCALL_64_after_hwframe+0x44/0xa9
9月 22 21:25:29 p4ryzen7 kernel: RIP: 0033:0x7fe3655b8b3e
9月 22 21:25:29 p4ryzen7 kernel: Code: 48 8b 0d 55 f3 0b 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 49 89 ca b8 af 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 22 f3 0b 00 f7 d8 64 89 01 48
9月 22 21:25:29 p4ryzen7 kernel: RSP: 002b:00007ffd00feaa68 EFLAGS: 00000246 ORIG_RAX: 00000000000000af

**Comment by senorsnor** [comment]
I have the same issue with both 5.3 and 5.3.1 on Arch Linux. See https://pastebin.com/kLQzQrPA for log entries relating to this module.

**Comment by senorsnor** [comment]
Never mind, just saw bug #55 which is the same issue and fixed in revision 59. I still used an older version. After re-building the module with latest HEAD everything works fine. So at least for me the issue is fixed. Sorry for the spam ..
