### ISSUE TITLE
Device can be registerd but cannot be brought up

### ISSUE THREAD

**Issue by bvkin** [tomaspinho/rtl8821ce#85]
Hello,

I'm trying to use this driver on my laptop running arch linux. So far I've been able to build and register it with dkms.
```
$ dkms status
rtl8821ce, v5.5.2_34066.20190614, 5.3.1-arch1-1-ARCH, x86_64: installed
```
The device also appears to be in use according to `lspci`
```
$ lspci -v
.
.
02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
        Subsystem: Lenovo RTL8821CE 802.11ac PCIe Wireless Network Adapter
        Flags: bus master, fast devsel, latency 0, IRQ 128
        I/O ports at 3000 [size=256]
        Memory at b1100000 (64-bit, non-prefetchable) [size=64K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [148] Device Serial Number 00-e0-4c-ff-fe-c8-21-01
        Capabilities: [158] Latency Tolerance Reporting
        Capabilities: [160] L1 PM Substates
        Capabilities: [170] Precision Time Measurement
        Capabilities: [17c] Vendor Specific Information: ID=0003 Rev=1 Len=054 <?>
        Kernel driver in use: rtl8821ce
        Kernel modules: 8821ce
```
The problem that I'm facing however is that I'm unable to bring the device up once it's registered. 
```
$ ip link set dev wlp2s0 up
$ ip link show
.
.             
3: wlp2s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DORMANT group default qlen 1000
    link/ether 8e:fe:33:94:b7:5e brd ff:ff:ff:ff:ff:ff
```
The result is the same no matter how many times I run the command. And trying to bring it up gives no errors or warnings. 

Apologies, I know this is not much information to go off of. Managing drivers is not an area that I'm very familiar with. Please let me know if there's anything else that I can provide which could be useful.

Thanks!

**Comment by bvkin** [comment]
I've managed to bring it up by using NetworkManager.
```
$ nmcli connection add con-name <connection-name> type <connection-type> device <device-name>
$ nmcli con modify <connection-name> wifi-sec.key-mgmt wpa-psk
$ nmcli con modify <connection-name> wifi-sec.psk <password>
```
However I'm still confused why I was not able to do so using `iproute2`. Should you be able to bring up a device without a network configured? Is this a bug?

**Comment by tomaspinho** [comment]
Nope, you need to be authenticated to have a wi-fi "link". I'd rather just use a UI applet, makes things much easier.
