### ISSUE TITLE
Does not seem to work with kernel 5.3.4 on Arch based system

### ISSUE THREAD

**Issue by SGOrava** [tomaspinho/rtl8821ce#88]
Hello, I am reporting this for a "friend", so please stone him not me.

Only useful message I got from him is:

`8821ce: module verification failed: signature and/or required key missing - tainting kernel`

And kernel version: 5.3.4

And that it does not work.

**Comment by Matthew-Hine** [comment]
Just want to report I'm getting the same problems here. Output of `dmesg |grep -i 8821ce
`

`[    3.523081] 8821ce: loading out-of-tree module taints kernel.
[    3.608829] 8821ce: module verification failed: signature and/or required key missing - tainting kernel
[    3.901246] rtl8821ce 0000:02:00.0 wlo1: renamed from wlan0
`

**Comment by Matthew-Hine** [comment]
Hey, totally spitballing here - I left a comment here showing I was also getting this error message, but I am also incredibly dumb.

@SGOrava Has your friend restarted // enabled his Network Manager service?

I get the same error by using `dmesg | grep 8821ce` 
`[    3.066303] 8821ce: loading out-of-tree module taints kernel.`
`[    3.132499] 8821ce: module verification failed: signature and/or required key missing - tainting kernel`
`[    3.453028] rtl8821ce 0000:02:00.0 wlo1: renamed from wlan0`

However, by restarting my NetworkManager service after the install everything kind of sprung to life - no bluetooth currently but about to noisy through the rest of the issues

**Comment by SGOrava** [comment]
I am also surprised you went missing.

He tried to reinstall the modules from AUR x times and rebooted also x times.
Doing something with NetworkManager... we did not get that far.
After some time trying and not getting any results we went for LTS (4.19) kernel, were it worked.

**Comment by tomaspinho** [comment]
These logs regarding signatures and keys are normal, this module is not signed after all. The rest of the logs don't really tell me anything, though.

**Comment by restlessmodem** [comment]
I encountered a similar issue and solved it by running `rfkill unblock all`.

**Comment by keii25** [comment]
Regards. How did it go with the installation under Kernel 4.19?
