### ISSUE TITLE
Can't connect to 5GHz network

### ISSUE THREAD

**Issue by last-partizan** [tomaspinho/rtl8821ce#9]
Hello, i have microtik router and two networks with same password.
I can successfully connect to 2.4GHz network, but connections to 5GHz is failing.

It was working some time ago and stopped after router update (and probably kernel update, but i don't remember exectly).
Other devices like phone can connect without problems to 5GHz network.
Passwords to both networks is the same, and i sure it's correct when i'm connecting to 5GHz net.

Here is logs from wpa_supplicant.service and dmesg.

[wpa.log](https://github.com/tomaspinho/rtl8821ce/files/2542984/wpa.log)
[dmesg.log](https://github.com/tomaspinho/rtl8821ce/files/2542971/dmesg.log)

How can i debug this issue further?

**Comment by Khariton** [comment]
I have stable working 5GHz connection to my tp-link router.

**Comment by tomaspinho** [comment]
All I can read from your logs is association errors, probably caused by a misconfiguration on the client or AP side. So far, I haven't hit the same problem.

**Comment by Khariton** [comment]
Dear Tomás Pinho,

The email sent to sasha@mishchenko.tk with subject
"Re: [tomaspinho/rtl8821ce] Can't connect to 5GHz network (#9)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to sasha@mishchenko.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by last-partizan** [comment]
Is there a way to find out what is misconfigured?

**Comment by Khariton** [comment]
Dear partizan,

The email sent to sasha@mishchenko.tk with subject
"Re: [tomaspinho/rtl8821ce] Can't connect to 5GHz network (#9)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to sasha@mishchenko.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by tomaspinho** [comment]
@last-partizan have you tried to change the settings on router or client side yet? Have you had any success?

**Comment by last-partizan** [comment]
Not really, i was trying to change "Security profile" (disable/enable WEP, and something like that) but i did not give any changes. (And probably shouldn't becouse security profile is shared between 2Ghz and 5Ghz network)

Besides that, what can i try to change?

**Comment by tomaspinho** [comment]
Have you tried changing 5GHz channels yet? I've just tested connecting to 2 different 5GHz access points, from Cisco and Aruba, at work with success.

**Comment by last-partizan** [comment]
Just tried to reset interface settings, and now it's working again.

Thanks.
