### ISSUE TITLE
some include file not found on elementary OS

### ISSUE THREAD

**Issue by mamahnxarya201** [tomaspinho/rtl8821ce#90]
when i try to run dkms -install on elementary os 5 it returns bad code and when i check at the log file it shows up this

`./include/linux/linkage.h:8:10 fatal erorr : asm/linkage.h no such file or directory
#include <asm/linkage.h>`
before this show up,stdarg.h was missing too and i fix it by adding cflags in make file 
i try add linkage.h from linux header directory bur not worked 

trying with 5.3.6 compiled succesfully but the problem still exist in 4.15  & 5.3.7

**Comment by tomaspinho** [comment]
Are you sure you have the correct kernel headers installed for those Kernel versions that you can't compile against?

**Comment by mamahnxarya201** [comment]
yes iam very sure and i already checked
