### ISSUE TITLE
Error Build

### ISSUE THREAD

**Issue by Minzords** [tomaspinho/rtl8821ce#93]
`[florian@MinzordOS rtl8821ce]$ sudo make all -j8

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.3.7-arch1-1-ARCH/build M=/mnt/Driver/rtl8821ce  modules
make[1] : on entre dans le répertoire « /usr/lib/modules/5.3.7-arch1-1-ARCH/build »
/mnt/Driver/rtl8821ce/Makefile:2171: //rtl8821c.mk: Aucun fichier ou dossier de ce type
make[2]: *** Aucune règle pour fabriquer la cible « //rtl8821c.mk ». Arrêt.
make[1]: *** [Makefile:1626: _module_/mnt/Driver/rtl8821ce] Error 2
make[1] : on quitte le répertoire « /usr/lib/modules/5.3.7-arch1-1-ARCH/build »
make: *** [Makefile:2242: modules] Error 2
`

I have this error on Debian Arch....

**Comment by harryyoud** [comment]
You should be running `sudo ./dkms-install.sh`, not directly with `make`
