### ISSUE TITLE
Wifi is fine but Bluetooth not working (on Debian)

### ISSUE THREAD

**Issue by Tireur2cables** [tomaspinho/rtl8821ce#94]
Hi, thanks a lot for the driver but as you said on the readme Bluetooth isn't working on my Lenovo Yoga 530 laptop (lol). There are some issues for that problem but it seems to be just for ArchLinux and I am on Debian. Do you have an adapted solution for a Debian user ?
If you need some more infomations on my system just ask ;)
Thank you!

**Comment by tomaspinho** [comment]
Hey, just run the commands in https://github.com/tomaspinho/rtl8821ce#lenovo-yoga-laptops

**Comment by Tireur2cables** [comment]
Yes I tried but it didn't work for me. I also tried by doing this : "modprobe.blacklist=ideapad_laptop" in /etc/default/grub (which is actually necessary if I want the wifi). But again it doesn't solve the bluetooth problem.
Do you have another idea?
Thanks

**Comment by tomaspinho** [comment]
Have you tried following https://github.com/tomaspinho/rtl8821ce/issues/19#issuecomment-452196840

**Comment by Tireur2cables** [comment]
No but is it adpated to a Debian system ? Because it seeams to be for Arch.

**Comment by tomaspinho** [comment]
You'll need to follow the same procedure, but using the tools from Debian

**Comment by Tireur2cables** [comment]
I'm ok with that but the zip file contains patch for ArchLinux and I don't know how to deal with it to have a patch for Debian. Or maybe I'm wrong and I just don't know appropriate tools.

**Comment by piratedeepak** [comment]
`sudo apt-get install bluetooth`
`etc/init.d bluetooth start`

**Comment by Tireur2cables** [comment]
Nice try but it didn't seem to work for me.

**Comment by kelebek333** [comment]
> No but is it adpated to a Debian system ? Because it seeams to be for Arch.

I prepared a repo from latest btrtl kernel source and I tried to add [this](https://github.com/tomaspinho/rtl8821ce/issues/19#issuecomment-452196840) patch.

You can try to install btrtl driver from this backport repository. https://github.com/kelebek333/backport-btrtl-dkms/tree/master#how-to-install

**Comment by Tireur2cables** [comment]
Thanks! But I just tried and it didn't work. It seems to disable the bluetooth device because I can't press the button activate in bluetooth.
![Capture du 2019-11-06 19-55-39](https://user-images.githubusercontent.com/43277447/68328493-ac780b00-00cf-11ea-81fe-fdb83458f053.png)

**Comment by kelebek333** [comment]
Did it look like this before installing the backports driver?

Did you check the status of BT device with the following command?

`rfkill list`

**Comment by Tireur2cables** [comment]
No I was able to active BT before but it just did nothing
It seems like I have no more BT device :
$ sudo rfkill list 
  0: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
but I don't know how to understead that : 
sudo dmesg | egrep 'blue|Blue'
    [    1.704975] usb 1-4: Product: Bluetooth Radio 
    [    2.232580] Bluetooth: Core ver 2.22
    [    2.232600] Bluetooth: HCI device and connection manager initialized
    [    2.232607] Bluetooth: HCI socket layer initialized
    [    2.232611] Bluetooth: L2CAP socket layer initialized
    [    2.232622] Bluetooth: SCO socket layer initialized
    [    8.519840] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
    [    8.519846] Bluetooth: BNEP filters: protocol multicast
    [    8.519854] Bluetooth: BNEP socket layer initialized

**Comment by crysman** [comment]
my colleague also reports **non-functional bluetooth on latest LTS Ubuntu** - any solution, yet? I haven(t tried myself to adapt the Arch guide proposed here https://github.com/tomaspinho/rtl8821ce/issues/94#issuecomment-548163225 but I would appreciate some info first, if available, thank you very much!

debug info OS:
```
~/rtl8821ce$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic
~/rtl8821ce$ uname -a
Linux hp 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

debug info network device:
```
02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
```

**Comment by crysman** [comment]
Hello, please, could you give me some small hint how to push this forward? I am very aware you are not obliged to do anything since you most probably do it in your free time, We can experiment ourselves, we just need a first step hint in order not to fall into bad ways. Thank you very much, I appreciate your work.

**Comment by tomaspinho** [comment]
@crysman let's try and rewrite that guide for Ubuntu together, then 😄 
Can you please run `dmesg | grep 'RTL: rtl:'` and post the output here? Thanks.

**Comment by Tireur2cables** [comment]
Hope I can help too. But for me the command `dmesg | grep 'RTL: rtl:'` tells me I don't have the rights to do it so I tried with `sudo dmesg | grep 'RTL: rtl:'` and it didn't display anythinng. :(

**Comment by crysman** [comment]
@Tireur2cables that's weird, none of the two commands included require su
and, by the way, you should not run sudo whenever something does not work, that will cause you a lot of trouble

**Comment by crysman** [comment]
@tomaspinho I will give it here once I get to that computer, thank you

**Comment by crysman** [comment]
@tomaspinho  here are outputs:
`dmesg | grep 'RTL: rtl:'` : NULL
`dmesg | grep 'rtl:'` : NULL
`dmesg | grep -i 'realtek'` : NULL
`dmesg | grep "rtl[0-9]*"` : 

> [    3.210401] RTW: rtl8821ce v5.5.2_34066.20190614_COEX20180712-3232
> [    3.210402] RTW: rtl8821ce BT-Coex version = COEX20180712-3232
> [    3.239144] RTW: rtl8821c_fw_dl Download Firmware from array success
> [    3.240897] RTW: rtl8821ce_init_txbd_ring entries num:128
> [    3.240899] RTW: rtl8821ce_init_txbd_ring queue:0, ring_addr:000000001864051f
> [    3.240899] RTW: rtl8821ce_init_txbd_ring entries num:128
> [    3.240900] RTW: rtl8821ce_init_txbd_ring queue:1, ring_addr:00000000ad20cae9
> [    3.240901] RTW: rtl8821ce_init_txbd_ring entries num:128
> [    3.240902] RTW: rtl8821ce_init_txbd_ring queue:2, ring_addr:000000008ab3f0f5
> [    3.240902] RTW: rtl8821ce_init_txbd_ring entries num:128
> [    3.240903] RTW: rtl8821ce_init_txbd_ring queue:3, ring_addr:0000000069fa1fa6
> [    3.240904] RTW: rtl8821ce_init_txbd_ring entries num:2
> [    3.240905] RTW: rtl8821ce_init_txbd_ring queue:4, ring_addr:00000000cac80744
> [    3.240905] RTW: rtl8821ce_init_txbd_ring entries num:128
> [    3.240906] RTW: rtl8821ce_init_txbd_ring queue:5, ring_addr:00000000bf609426
> [    3.240906] RTW: rtl8821ce_init_txbd_ring entries num:128
> [    3.240907] RTW: rtl8821ce_init_txbd_ring queue:6, ring_addr:00000000fc6655e7
> [    3.240908] RTW: rtl8821ce_init_txbd_ring entries num:128
> [    3.240909] RTW: rtl8821ce_init_txbd_ring queue:7, ring_addr:0000000038474697
> [    3.565153] rtl8821ce 0000:02:00.0 wlo1: renamed from wlan0
> [    5.794979] RTW: rtl8821c_hal_init_main: successful
> [    9.734307] RTW: ==> rtl8821ce_hal_deinit
> [    9.734500] RTW: rtl8821ce_hal_deinit <==
> [   10.254983] RTW: rtl8821c_hal_init_main: successful
> [   10.484183] RTW: rtl8821c_dl_rsvd_page(wlo1):+ hw_port=0 mstatus(1)

Thanks for help!

**Comment by tomaspinho** [comment]
Please also search for any bluetooth related messages instead: `dmesg | grep -i bluetooth`

**Comment by crysman** [comment]
@tomaspinho nothing (no output)

**Comment by Syniurge** [comment]
@crysman
> my colleague also reports **non-functional bluetooth on latest LTS Ubuntu** - any solution, yet? I haven(t tried myself to adapt the Arch guide proposed here [#94 (comment)](https://github.com/tomaspinho/rtl8821ce/issues/94#issuecomment-548163225) but I would appreciate some info first, if available, thank you very much!
> 
> debug info OS:
> 
> ```
> ~/rtl8821ce$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description: Ubuntu 18.04.3 LTS
> Release: 18.04
> Codename: bionic
> ~/rtl8821ce$ uname -a
> Linux hp 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> debug info network device:
> 
> ```
> 02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
> ```

Have you tried a newer kernel yet? I've only used Bluetooth a couple of times but it worked on my Ubuntu 18.04-powered Yoga 530 without any special configuration other than having a 5.2 or 5.3 kernel from:
https://kernel.ubuntu.com/~kernel-ppa/mainline

Direct links to the latest 5.3 kernel .deb: 
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.3.18/linux-headers-5.3.18-050318_5.3.18-050318.201912181133_all.deb
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.3.18/linux-headers-5.3.18-050318-generic_5.3.18-050318.201912181133_amd64.deb
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.3.18/linux-image-unsigned-5.3.18-050318-generic_5.3.18-050318.201912181133_amd64.deb
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.3.18/linux-modules-5.3.18-050318-generic_5.3.18-050318.201912181133_amd64.deb

**Comment by Tireur2cables** [comment]
Here are outputs for `dmesg | grep 'rtl[0-9]*'` : 
[    2.485582] RTW: rtl8821ce v5.2.5_1.26055.20180108
[    2.488007] RTW: rtl8821ce BT-Coex version = COEX20170310-1212
[    2.730906] btusb: disagrees about version of symbol btrtl_setup_realtek
[    2.730910] btusb: Unknown symbol btrtl_setup_realtek (err -22)
[    2.768635] btusb: disagrees about version of symbol btrtl_setup_realtek
[    2.769516] btusb: Unknown symbol btrtl_setup_realtek (err -22)
[    2.806945] btusb: disagrees about version of symbol btrtl_setup_realtek
[    2.808813] btusb: Unknown symbol btrtl_setup_realtek (err -22)
[    2.846584] btusb: disagrees about version of symbol btrtl_setup_realtek
[    2.848715] btusb: Unknown symbol btrtl_setup_realtek (err -22)
[    2.896125] rtl8821ce 0000:01:00.0 wlp1s0: renamed from wlan0

and for me the command `dmesg | grep 'rtl[0-9]*'` display : 
[    2.040030] usb 1-4: Product: Bluetooth Radio 
[    2.521880] Bluetooth: Core ver 2.22
[    2.525709] Bluetooth: HCI device and connection manager initialized
[    2.525749] Bluetooth: HCI socket layer initialized
[    2.528453] Bluetooth: L2CAP socket layer initialized
[    2.531369] Bluetooth: SCO socket layer initialized
[   10.222661] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   10.222667] Bluetooth: BNEP filters: protocol multicast
[   10.222674] Bluetooth: BNEP socket layer initialized

**Comment by zokej** [comment]
uname -r:
5.3.0-26-generic
dmesg | grep 'rtl[0-9]*' display :
nothing

WiFi OK, Bluetooth is not working

Ubuntu 18.04.3

**Comment by Kmphs** [comment]
Here's someone else struggling with Bluetooth. But let me start off by saying I'm very happy with this driver for it got my WiFi working, so thanks a lot for that!!!

As for the Bluetooth, which I hope we can manage to get working as well....
I'm on a Lenovo IdeaPad L340-15IRH Gaming, running Debian 10 (buster)
```
root@Laptop:~# uname -a
Linux Laptop 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```

I did try to disable the ideapad-laptop module, as in the readme. Alas, it didn't help.
Also I checked the solution of @wahsot  which already goes wrong in the very first step Diagnosis, as Bluetooth is detected as `lmp_subver=8221` & `hci_ref=000c.`. Consequently, I did not try the rest of his solution:

```
root@Laptop:~# dmesg | grep 'RTL: rtl:'
[    4.181277] Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=000c lmp_ver=08 lmp_subver=8821
[    4.182266] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8821c_fw.bin
```

Now I assume the problem can be pinpointed here, where it indicates issues with the firmware:
```
root@Laptop:~# dmesg | egrep 'blue|Blue'
[    2.917802] usb 1-14: Product: Bluetooth Radio 
[    4.111502] Bluetooth: Core ver 2.22
[    4.111515] Bluetooth: HCI device and connection manager initialized
[    4.111518] Bluetooth: HCI socket layer initialized
[    4.111520] Bluetooth: L2CAP socket layer initialized
[    4.111526] Bluetooth: SCO socket layer initialized
[    4.181277] Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=000c lmp_ver=08 lmp_subver=8821
[    4.182264] Bluetooth: hci0: RTL: rom_version status=0 version=1
[    4.182266] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8821c_fw.bin
[    4.182290] bluetooth hci0: firmware: failed to load rtl_bt/rtl8821c_fw.bin (-2)
[    4.182348] bluetooth hci0: Direct firmware load for rtl_bt/rtl8821c_fw.bin failed with error -2
[    4.182351] Bluetooth: hci0: RTL: firmware file rtl_bt/rtl8821c_fw.bin not found
[    4.515688] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    4.515689] Bluetooth: BNEP filters: protocol multicast
[    4.515694] Bluetooth: BNEP socket layer initialized
```

But this is where I get stuck.
Any help would be greatly appreciated!

Some additional output, let me know if there's any other output you need.

```
root@Laptop:~# rfkill list
0: ideapad_wlan: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: ideapad_bluetooth: Bluetooth
	Soft blocked: no
	Hard blocked: no
2: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
3: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
```

```
root@Laptop:~# lspci
00:00.0 Host bridge: Intel Corporation 8th Gen Core 4-core Processor Host Bridge/DRAM Registers [Coffee Lake H] (rev 07)
00:01.0 PCI bridge: Intel Corporation Skylake PCIe Controller (x16) (rev 07)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 630 (Mobile)
00:04.0 Signal processing controller: Intel Corporation Skylake Processor Thermal Subsystem (rev 07)
00:08.0 System peripheral: Intel Corporation Skylake Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:15.0 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller (rev 10)
00:15.1 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:17.0 SATA controller: Intel Corporation Cannon Lake Mobile PCH SATA AHCI Controller (rev 10)
00:1d.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port (rev f0)
00:1d.4 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port (rev f0)
00:1d.5 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port (rev f0)
00:1e.0 Communication controller: Intel Corporation Device a328 (rev 10)
00:1f.0 ISA bridge: Intel Corporation Device a30d (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1c91 (rev a1)
06:00.0 Non-Volatile memory controller: Intel Corporation Device f1a8 (rev 03)
07:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
08:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)
```

**Comment by wahsot** [comment]
Hey, sorry I haven't been responding as I don't use Debian, but I have been reading this trough.

From the kernel log, it says it cannot find the firmware file:

> Bluetooth: hci0: RTL: firmware file rtl_bt/rtl8821c_fw.bin not found

Have you installed Debian's firmware-realtek package?

https://packages.debian.org/buster/firmware-realtek

**Comment by Tireur2cables** [comment]
@wahsot Thanks for your idea!
I just installed firmware-realtek package and now here are my outputs for `dmesg | grep -i bluetooth'` : 
`
[    2.046947] usb 1-4: Product: Bluetooth Radio 
[    2.571448] Bluetooth: Core ver 2.22
[    2.571468] Bluetooth: HCI device and connection manager initialized
[    2.571473] Bluetooth: HCI socket layer initialized
[    2.571476] Bluetooth: L2CAP socket layer initialized
[    2.571486] Bluetooth: SCO socket layer initialized
[    2.686618] Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=000c lmp_ver=08 lmp_subver=8821
[    2.689652] Bluetooth: hci0: RTL: rom_version status=0 version=1
[    2.690285] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8821c_fw.bin
[    2.695468] bluetooth hci0: firmware: failed to load rtl_bt/rtl8821c_fw.bin (-2)
[    2.697066] bluetooth hci0: Direct firmware load for rtl_bt/rtl8821c_fw.bin failed with error -2
[    2.705627] Bluetooth: hci0: RTL: firmware file rtl_bt/rtl8821c_fw.bin not found
[    7.807038] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    7.807040] Bluetooth: BNEP filters: protocol multicast
[    7.807045] Bluetooth: BNEP socket layer initialized
`
And I there are so much more lines now. So I think there is something to do with those lines : 
`
[    2.690285] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8821c_fw.bin
[    2.695468] bluetooth hci0: firmware: failed to load rtl_bt/rtl8821c_fw.bin (-2)
[    2.697066] bluetooth hci0: Direct firmware load for rtl_bt/rtl8821c_fw.bin failed with error -2
[    2.705627] Bluetooth: hci0: RTL: firmware file rtl_bt/rtl8821c_fw.bin not found
`
But I don't really know what.
Thanks for helping!

**Comment by wahsot** [comment]
The error still suggest the file cannot be found.
Can you confirm the following path does not exist?

`/lib/firmware/rtl_bt/rtl8821c_fw.bin`

**Comment by Tireur2cables** [comment]
Yes the file doesn't exist.  
In that folder I have :  
```  
rtl8192ee_fw.bin  
rtl8723a_fw.bin  
rtl8761a_fw.bin  
rtl8821a_fw.bin  
rtl8822b_fw.bin  
rtl8192eu_fw.bin  
rtl8723b_fw.bin  
rtl8812ae_fw.bin  
rtl8822b_config.bin  
```    
but I don't have `rtl8821c_fw.bin`.

**Comment by Kmphs** [comment]
Thanks @wahsot
I understand this is originally not meant for Debian, but at least with this package the wifi works, and I hope the Bluetooth will too ;-) Thanks for the help so far!

I installed the firmware-realtek package. Now there's a Bluetooth adapter, it scans for devices and finds them. So this is progress!

It's not yet a complete solve, for it seems unable to pair with any device.
**The setup of [devicename] has failed**
is the error the Bluetooth Device Wizard consistently gives.

I've tried for several phones and headsets, all giving the same result. Any thoughts on where to look next for a solution?

**Comment by tomaspinho** [comment]
@kmphs can you show us the logs in your dmesg around the time of those failures?

**Comment by Kmphs** [comment]
Yes, I fixed it. At least for audio - not sure yet about file transfer.
 Continueing from my previous post.
Tried pairing again: again unsuccesful.

dmesg didn't show anything useful. So I checked syslog.
```
less /var/log/syslog
```

Relevant error said:
```
bluetoothd[655]: a2dp-sink profile connect failed for 20:32:7D:7B:D9:B7: Protocol not available
```

And that error message led me to this Debian-specific page [https://wiki.debian.org/BluetoothUser/a2dp](url)
I followed the instructions there and my headset works.

Also found a similar site about Arch Linux; no idea if it works but since this was originally written for Arch I feel obliged to share it as well: [https://wiki.archlinux.org/index.php/Bluetooth_Headset](url)

I have yet to try file sharing. But I know now if it doesn't work, it's about a protocol and not a driver issue any more.
Thanks for all you help!!!

**Comment by Tireur2cables** [comment]
Big update for me.  
I moved to `Debian 10 (buster)`,  
then I installed the driver and blacklisted `ideapad_laptop` module (because I'm on a Yoga laptop)  
After a reboot Wifi was working but not bluetooth so  I installed `firmware-realtek` package as @wahsot suggested.  
An other reboot and both bluetooth and wifi were working.  
I tested Music and file sharing because this is all I would do with bluetooth I guess and it works.  
Big thanks for both wifi and bluetoth dirver!  
@wahsot thank you very much for your great ideas!  
@tomaspinho you're a hero to me.

**Comment by tomaspinho** [comment]
Good to know everything worked out in the end!
Sorry it took so long. 😅

And I'm not anyone's hero, just a stubborn Linux user 🤣

I'm gonna close this one.

**Comment by Mathuthiru** [comment]
Hi Iam new to Debian...I have the same problem like @Tireur2cables had once...any one give me the steps to solve this problem that will be helpful... because I didn't understand any of the above conversation....my WiFi works fine and Bluetooth is not connecting...and my mini pc has same rtl8821ce 802.11ac pcie adapter....

**Comment by Tireur2cables** [comment]
Hi @Mathuthiru !
I am on the latest release of debian and all I had to do in order to activate the bluetooth was to install this driver and the packet `firmware-realtek`. So if you already installed this driver you just have to tap `sudo apt-get install firmware-realtek` and reboot your pc. ;)

**Comment by Mathuthiru** [comment]
Thanks a lot @Tireur2cables I have installed firmware for realtek ....after rebooting both of my WiFi and Bluetooth work's fine....once again thanks for this conversation of yours because it is the only solution I can find on Google.....
