### ISSUE TITLE
Building on CentOS 8 fails due to incompatible pointer types

### ISSUE THREAD

**Issue by robert-scheck** [tomaspinho/rtl8821ce#97]
Building only works with `export USER_EXTRA_CFLAGS=-Wno-error=incompatible-pointer-types`, otherwise it fails due to the warning raised.

```
[root@tux rtl8821ce]# export USER_EXTRA_CFLAGS=-Wno-error=incompatible-pointer-types
[root@tux rtl8821ce]# ./dkms-install.sh

  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/pci_ops_linux.o
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/os_intfs.c:1479:22: warning: initialization of 'u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, s
truct sk_buff *, struct net_device *))' {aka 'short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *)
)'} from incompatible pointer type 'u16 (*)(struct net_device *, struct sk_buff *, void *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))' {aka 'short unsigned int (*)(struct net_device *,
struct sk_buff *, void *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))'} [-Wincompatible-pointer-types]
  .ndo_select_queue = rtw_select_queue,
                      ^~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/os_dep/linux/os_intfs.c:1479:22: note: (near initialization for 'rtw_netdev_ops.ndo_select_queue')
[…]
```

CentOS 8 has (a patched) Kernel 4.18.0.

**Comment by tomaspinho** [comment]
Looks like your distribution has a kernel with backported changes to the `ndo_select_queue` struct. You will need to keep a forked version of this module with changes in the following code in `os_intfs.c` to match the fields in your kernel headers.

```
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4,19,0))
static u16 rtw_select_queue(struct net_device *dev, struct sk_buff *skb
    , struct net_device *sb_dev
    #if (LINUX_VERSION_CODE < KERNEL_VERSION(5,2,0))
    , select_queue_fallback_t fallback
    #endif
)
#else
static u16 rtw_select_queue(struct net_device *dev, struct sk_buff *skb
#if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 13, 0)
	, void *accel_priv
	#if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 14, 0)
	, select_queue_fallback_t fallback
	#endif
#endif
```

**Comment by jmarianek** [comment]
I've compiled module on CentOS8 successfully, but after boot it causes error:
WARNING: CPU: 6 PID: 480 at /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/os_dep/linux/os_intfs.c:3138
WARNING: CPU: 5 PID: 480 at /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/os_dep/linux/os_intfs.c:1678
WARNING: CPU: 5 PID: 480 at net/wireless/core.c:867 wiphy_register+0x68a/0x940 [cfg80211]

Please could you help me?

**Comment by csongit** [comment]
> Looks like your distribution has a kernel with backported changes to the `ndo_select_queue` struct. You will need to keep a forked version of this module with changes in the following code in `os_intfs.c` to match the fields in your kernel headers.
> 
> ```
> #if (LINUX_VERSION_CODE >= KERNEL_VERSION(4,19,0))
> static u16 rtw_select_queue(struct net_device *dev, struct sk_buff *skb
>     , struct net_device *sb_dev
>     #if (LINUX_VERSION_CODE < KERNEL_VERSION(5,2,0))
>     , select_queue_fallback_t fallback
>     #endif
> )
> #else
> static u16 rtw_select_queue(struct net_device *dev, struct sk_buff *skb
> #if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 13, 0)
> 	, void *accel_priv
> 	#if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 14, 0)
> 	, select_queue_fallback_t fallback
> 	#endif
> #endif
> ```

What should I do to match the fields in my kernel headers? I have 4.18.0-193.28.1.el8_2.x86_64 on Centos. I changed 4,19 to 4,18, but that didn't help me. So I removed the installation, activated debugging, ran ./dkms-install.sh
 and here is my 
[make.log](https://github.com/tomaspinho/rtl8821ce/files/5603378/make.log)
